{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="sysconf-main">
        <ul class="tabs-without-js">
            <li><a href="statistics.php">流量趋势</a></li>
            <li class="active"><a href="statistics.php?act=detail">pv明细</a></li>
        </ul>
        <div class="tab_container">
            <div id="tab2" class="tab_content" style="">
                <p>
                <div class="pull-left">
                    <label>选择日期：</label>
                    <input class="text-input w150" type="text" id="date" name="date" value="{$day}">&nbsp;
                    <!--                        <button class="btn-primary btn" type="button" id="sure">确定</button>-->
                </div>
                </p>
                <p class="clear"></p>
                <table class="table">
                    <thead>
                    <tr>
                        <th>IP</th>
                        <th>访问时间</th>
                        <th>网页来源</th>
                        <th>受访</th>
                        <th>User Agent</th>
                    </tr>
                    </thead>
                    <tbody>
                    {if $pv_list}
                    {foreach from=$pv_list item=pv}
                    <tr>
                        <td>{$pv.ip}</td>
                        <td>{$pv.request_time_str}</td>
                        <td>{$pv.source}</td>
                        <td>{$pv.destination}</td>
                        <td>{$pv.agent}</td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr>
                        <td style="padding: 50px 0" colspan="5" align="center">无访问记录</td>
                    </tr>
                    {/if}

                    <tr>
                        <td colspan="5">
                            <div class="pull-right">
                                <div class="pages">
                                    <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                                    {if $go_first}
                                    <a href="?act=detail&page=1">首页</a>
                                    {/if}
                                    {if $has_prev}
                                    <a href="?act=detail&page={$page - 1}">上一页</a>
                                    {/if}
                                    {if $has_many_prev}
                                    ...
                                    {/if}
                                    {foreach from=$show_page item=pageNum}
                                    {if $pageNum eq $page}
                                    <b>{$page}</b>
                                    {else}
                                    <a href="?act=detail&page={$pageNum}">{$pageNum}</a>
                                    {/if}
                                    {/foreach}
                                    {if $has_many_next}
                                    ...
                                    {/if}
                                    {if $go_last}
                                    <a href="?act=detail&page={$totalPage}">末页</a>
                                    {/if}
                                    {if $has_next}
                                    <a href="?act=detail&page={$page + 1}">下一页</a>
                                    {/if}
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{include file="library/footer.lbi"}
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
</script>
<!-- END 日历控件 -->
<script type="text/javascript">
    $(function() {
        $('#date').click(function() {
            var date = {
                elem: '#date',
                format: 'YYYY-MM-DD',
                istime: false,
                istoday: true,
                choose: function (datas) {
                    var url = 'statistics.php?act=detail';
                    if (datas) {
                        url += '&date=' + datas;
                        window.location.href = url;
                    }
                }
            };
            laydate(date);
        });
    });
</script>
</body>
</html>