{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<script type="text/javascript">
    var uv_data = {$uv_target};
    var pv_data = {$pv_target};
</script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="sysconf-main">
        <ul class="tabs-without-js">
            <li class="active"><a href="statistics.php">流量趋势</a></li>
            <li>
                <a href="statistics.php?act=detail">pv明细</a></li>
        </ul>
        <div class="tab_container">
            <div id="tab1" class="tab_content" style="">
                <p>
                    <div class="pull-left">
                        <label>选择日期：</label>
                        <input class="text-input w150" type="text" id="date" name="date" value="{$day}">&nbsp;
<!--                        <button class="btn-primary btn" type="button" id="sure">确定</button>-->
                    </div>
                </p>
                <p class="clear"></p>
                {if $total neq 0}
                <div id="chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                {else}
                <div>无访问记录</div>
                {/if}
            </div>

        </div>
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
</script>
<!-- END 日历控件 -->
{include file="library/footer.lbi"}
<script src="js/highcharts/highcharts.js"></script>
<script src="js/highcharts/modules/exporting.js"></script>
<script src="js/statistics/view.js"></script>
</body>
</html>