{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">编辑产品类型</h5>
        <div class="clear"></div>
    </div>
    <div class="basicInfo-main">
        <form id="typeEditForm" method="post" action="">
            <fieldset>
                <p>
                    <label class="l-title">类型名称：</label>
                    <input class="text-input w300" type="text" maxlength="64" id="type_name" name="type_name" value="{$type.name}" placeholder="请输入类型名"/>
                </p>
                <p>
                    <label class="l-title"></label>
                    <button class="btn btn-primary" type="submit">提交</button>&nbsp;
                    <a class="btn btn-primary" href="type.php">返回</a>
                    <input type="hidden" name="opera" value="edit" />
                    <input type="hidden" name="id" value="{$type.id}" />
                </p>

            </fieldset>
        </form>
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>