{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">类型列表</h5>
        <div class="pull-right">
            <a href="?act=add" class="btn btn-primary">添加类型</a>
        </div>
        <div class="clear"></div>
    </div>
    <div class="article-main">
        <table class="table">
            <thead>
            <tr>
                <th>类型名称</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {if $type_list}
            {foreach from=$type_list item=type}
            <tr>
                <td>{$type.name}</td>
                <td class="text-right">
                    <a href="?act=edit&id={$type.id}">编辑</a>
                    | <a href="?act=attr&id={$type.id}">类型属性</a>
                    | <a href="?act=add-attr&id={$type.id}">添加属性</a>
                    | <a onclick="javascript:if(confirm('确认要删除？')) return true; else return false;" href="?act=delete&id={$type.id}">删除</a></td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="2" align="center">您还没有产品类型，立即点击 “<a href="?act=add" target="_blank">这里</a>” 添加产品类型！</td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>