{include file="library/header.lbi"}
<body>
<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />

{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">消费券管理{if $order_status neq ''}-{$order_status}{/if}</h5>
        <div class="pull-right">
            <a class="btn btn-primary" href="virtual_order.php">全部</a>&nbsp;
            <a class="btn btn-primary" href="virtual_order.php?status=1">有效</a>&nbsp;
            <a class="btn btn-primary" href="virtual_order.php?status=2">已使用</a>&nbsp;
            <a class="btn btn-primary" href="virtual_order.php?status=3">已过期</a>&nbsp;
            <a class="btn btn-primary" href="virtual_order.php?status=4">失效</a>&nbsp;
            <a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;
        </div>
        <div class="clear"></div>
    </div>
    <div class="article-main-header">
        <form action="" method="get" />
        <fieldset>
            <p>
            <div class="pull-left">
                显示
                <select name="count" class="w75">
                    <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                    <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                    <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                    <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                </select>
                项结果
            </div>
<!--            <div class="pull-right">-->
<!--                <label>起始日期：</label>-->
<!--                <input class="text-input w150" type="text" id="" name="st" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD'})"{/literal} value="{$st}">&nbsp;-->
<!--                <label>结束日期：</label>-->
<!--                <input class="text-input w150" type="text" id="" name="et" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD'})"{/literal} value="{$et}">&nbsp;-->
<!--                <input type="hidden" name="status" value="{$status}"/>-->
<!--                <button type="submit" class="btn btn-default">搜索</button>-->
<!--            </div>-->
            </p>
        </fieldset>
        </form>
        <div class="clear"></div>
    </div>

    <div class="article-main">
        <table class="table">
            <thead>
            <tr>
                <th>消费券信息</th>
                <th>商家</th>
                <th>消费券状态</th>
                <th>联系方式</th>
            </tr>
            </thead>
            <tbody>
            {if $total neq 0}
            {foreach from=$content_list item=content}
            <tr>
                <td colspan="4">订单编号：{$content.order_sn}</td>
            </tr>
            <tr>
                <td>
                    <div class="pull-left">
                        <img src="..{$content.img}" width="50" height="50"/>
                    </div>
                    <div class="pull-left">
                        <em> {$content.product_name} </em><br />
                        <em> 有效期： {$content.begin_time_str} ~ {$content.end_time_str}</em>
                    </div>
                </td>
                <td>
                    {$content.shop_name}
                </td>
                <td>{$content.status_str}</td>
                <td>
                    {$content.mobile}<br />
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="4" align="center">
                {if $status eq 0}
                    尚未有客户下单！
                {/if}
                {if $status eq 1}
                    没有可用的消费券
                {/if}
                {if $status eq 2}
                    没有已使用的消费券
                {/if}
                {if $status eq 3}
                    没有已过期的消费券
                {/if}
                {if $status eq 4}
                    没有失效的消费券
                {/if}
                </td>
            </tr>
            {/if}
            <tr>
                <td colspan="4">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&count={$count}&status={$status}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&count={$count}&status={$status}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&count={$count}&status={$status}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&count={$count}&status={$status}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&count={$count}&status={$status}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->

<script type="text/javascript">
    $(function() {
        $('select[name=count]').change(function () {
            var st = $('input[name=st]').val();
            var et = $('input[name=et]').val();

            var count = $(this).val();
            var url = 'virtual_order.php?count=' + count;
            if( st ) {
                url += '&st=' + st;
            }
            if( et ) {
                url += '&et=' + et;
            }
            {if $status}
                var status = $('input[name=status]').val();
                url += ( status == 0 ) ? '' : '&status=' + status;
                {/if}
                    window.location.href = url;
                });
            });
</script>

{include file="library/footer.lbi"}
<script type="text/javascript" src="js/order/view.js">

</script>
</body>
</html>