{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">
            商户管理
            {if $status && $status eq 1}
            -待审核
            {/if}
            {if $status && $status eq 2}
            -运营中
            {/if}
            {if $status && $status eq 3}
            -已冻结
            {/if}
        </h5>
        <div class="pull-right">
            <a class="btn btn-primary" href="business.php">全部</a>&nbsp;
            <a class="btn btn-primary" href="business.php?status=1">待审核</a>&nbsp;
            <a class="btn btn-primary" href="business.php?status=2">运营中</a>&nbsp;
            <a class="btn btn-primary" href="business.php?status=3">已冻结</a>&nbsp;
            <a class="btn btn-primary" href="business.php?act=auth">认证信息</a>&nbsp;
            <a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;
        </div>
        <div class="clear"></div>
    </div>
    <div class="article-main">
        <div class="article-main-header">
            <form action="" method="get" />
            <fieldset>
                <p>
                <div class="pull-left">
                    显示
                    <select name="count" class="w75">
                        <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                        <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                        <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                        <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                    </select>
                    项结果
                </div>
                <div class="pull-right">
                    <label>搜索：</label>
                    <input class="text-input w150" type="text" id="small-input" name="keyword" value="{$keyword}">&nbsp;
                    <button type="submit" class="btn btn-default">搜索</button>
                    {if $status}<input type="hidden" name="status" value="{$status}"/>{/if}
                </div>
                </p>
            </fieldset>
            </form>
            <div class="clear"></div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>商户帐号</th>
                <th>店铺信息</th>
                <th>公司名称</th>
                <th>地址</th>
                <th>状态</th>
                <th>账户</th>
                <th>联系方式</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {if $total neq 0}
            {foreach from=$business_list item=business}
            <tr>
                <td>{$business.business_account}</td>
                <td>
                    店名：{$business.shop_name}<br />
                    主营行业：{$business.industry_name}<br />
                    主营分类：{$business.cate_name}
                </td>
                <td>
                    {$business.company}
                </td>
                <td>
                    {$business.province_name}&nbsp;{$business.city_name}&nbsp;{$business.district_name}&nbsp;{$business.group_name}<br />
                    {$business.address}
                </td>
                <td>{$business.status_str}</td>
                <td>
                    余额：{$business.balance}<br />
                    担保交易：{$business.trade}
                </td>
                <td>
                    联系人：{$business.contact}<br />
                    手机：{$business.mobile}<br />
                    邮箱：{$business.email}<br />
                </td>
                <td class="text-right">
                    {if $business.status eq 1}
                    <a href="?act=exam&account={$business.business_account}">审核</a>
                    {/if}
                    {if $business.status eq 2}
                    <a onclick="javascript:if(confirm('确认要冻结商户？')) return true; else return false;" href="?act=frozen&account={$business.business_account}">冻结</a>
                    {/if}
                    {if $business.status eq 3}
                    <a onclick="javascript:if(confirm('确认要为商户解除冻结？')) return true; else return false;" href="?act=frozen&account={$business.business_account}">解除冻结</a>
                    {/if}
                </td>
            </tr>
            {/foreach}
            {else}
            {if $keyword eq ''}
            <tr>
                <td style="padding: 50px 0" colspan="8" align="center">暂无商户记录</td>
            </tr>
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="8" align="center">
                    <span class="text-size-24 blue icon-info-1" style="vertical-align: middle"></span>
                    <div class="text-size-18 tip-text inline-block">没有查询到符合条件的记录</div>
                </td>
            </tr>
            {/if}
            {/if}

            <tr>
                <td colspan="8">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&keyword={$keyword}&count={$count}{if $status}&status={$status}{/if}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&keyword={$keyword}&count={$count}{if $status}&status={$status}{/if}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&keyword={$keyword}&count={$count}{if $status}&status={$status}{/if}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&keyword={$keyword}&count={$count}{if $status}&status={$status}{/if}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&keyword={$keyword}&count={$count}{if $status}&status={$status}{/if}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- END content -->
<script type="text/javascript">
    $(function(){
        $('select[name=count]').change(function(){
            var keyword = $('input[name=keyword]').val();
            var count = $(this).val();
            var url = 'business.php?count=' + count + '&keyword=' + keyword;
            {if $status}
            var status = $('input[name=status]').val();
            url += status;
            {/if}
            window.location.href = url;
        });
    });
</script>
{include file="library/footer.lbi"}
</body>
</html>