{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}-修改密码</h5>
        <div class="clear"></div>
    </div>
    <div class="self-main">
        <form id="self-form" password="self-form" method="post" onsubmit="return do_submit();">
            <fieldset>
                <p class="clear">
                    <label class="l-title">原密码:</label>
                    <input class="text-input w300" type="password" id="password" password="password" placeholder="请输入原密码" value=""/>
                    <span class="error-input" id="password-error">{if isset($error.password)}{$error.password}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">新密码:</label>
                    <input class="text-input w300" type="password" id="new_password" password="new_password" placeholder="请输入新密码" value=""/>
                    <span class="error-input" id="new_password-error">{if isset($error.new_password)}{$error.new_password}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">再一次输入密码:</label>
                    <input class="text-input w300" type="password" id="confirm" password="confirm" placeholder="再一次输入密码" value=""/>
                    <span class="error-input" id="confirm-error">{if isset($error.confirm)}{$error.confirm}{/if}</span>
                </p>
                <p>
                    <label class="l-title"></label>
                    <a class="btn btn-primary" id="submit-btn" href="javascript:;">
                        提交<img src="images/btn_loading.gif" class="btn-loading-img"/>
                    </a>&nbsp;
                    <input type="hidden" password="opera" value="edit"/>
                    <a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>
            </fieldset>
        </form>
    </div>
</div>
<div id="mask"></div>
<script type="text/javascript">
    $(function() {
        $("#submit-btn").click(do_submit);
    });
    /**
     * 这个解决方案可以作为Ajax提交表单的模板
     * 1、form的提交操作托管给do_submit处理;
     * 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
     * 3、仅支持post方式提交表单;
     * 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码<div id="mask"></div>
     **/
    function do_submit() {
        //参数校验
        var flag = true;
        var password = $("#password").val().trim();
        var new_password = $("#new_password").val().trim();
        var confirm = $("#confirm").val().trim();

        if(password == "") {
            $("#password-error").text("-请输入原密码");
            flag = false;
        } else {
            $("#password-error").text("");
        }

        if(new_password == "") {
            $("#new_password-error").text("-请输入新密码");
            flag = false;
        } else {
            $("#new_password-error").text("");
        }

        if(confirm == "") {
            $("#confirm-error").text("-再一次输入密码");
            flag = false;
        } else {
            $("#confirm-error").text("");
        }

        if(flag) {
            flag = true;
            //启用过渡效果
            $(".btn-loading-img").show();
            $("#submit-btn").addClass("btn-disabled");
            $("#mask").show();

            var params = { "opera":"password", "password":password, "new_password":new_password, "confirm":confirm};
            var url = "self.php";
            $.post(url, params, do_response, "json");
        }

        return flag;
    }

    function do_response(result) {
        //关闭过渡效果
        $(".btn-loading-img").hide();
        $("#submit-btn").removeClass("btn-disabled");
        $("#mask").hide();
        document.forms['self-form'].reset();
        //处理返回结果
        if(result.error == 0) {
            alert(result.msg);
        } else {
            if(result.msg != "") {
                alert(result.msg);
            }
            if(result.errmsg) {
                for(var id in result.errmsg) {
                    $("#"+id+"-error").text(result.errmsg[id]);

                }
            }
        }
    }
    /*----------------  Ajax end ---------------------*/
</script>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>
