{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{if $type eq 0}会员-{else}商户-{/if}账户明细</h5>
        <div class="pull-right">
            <a href="account.php?type=0" class="btn btn-primary">会员</a>
            <a href="account.php?type=1" class="btn btn-primary">商户</a>
            <a href="javascript:history.go(-1)" class="btn btn-primary">返回</a>
        </div>
        <div class="clear"></div>
    </div>
    <div class="article-main-header">
        <form action="" method="get" />
        <fieldset>
            <p>
            <div class="pull-left">
                显示
                <select name="count" class="w75">
                    <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                    <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                    <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                    <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                </select>
                项结果
            </div>
            <div class="pull-right">
                <label>起始日期：</label>
                <input class="text-input w150" type="text" id="" name="st" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD'})"{/literal} value="{$st}">&nbsp;
                <label>结束日期：</label>
                <input class="text-input w150" type="text" id="" name="et" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD'})"{/literal} value="{$et}">&nbsp;
                <button type="submit" class="btn btn-default">搜索</button>
                <input type="hidden" name="type" value="{$type}"/>
            </div>
            </p>
        </fieldset>
        </form>
        <div class="clear"></div>
    </div>
    <div class="withdraw-record">
        <table class="table">
            <thead>
            <tr>
            {if $type eq 0}
                <th>帐号</th>
                <th>变动时间</th>
                <th>余额</th>
                <th>积分</th>
                <th>佣金</th>
                <th>待发积分</th>
                <th>待发佣金</th>
                <th>操作员</th>
                <th>备注</th>
            {else}
                <th>商家帐号</th>
                <th>变动时间</th>
                <th>余额</th>
                <th>担保交易</th>
                <th>操作员</th>
                <th>备注</th>
            {/if}
            </tr>
            </thead>
            <tbody>
            {if $total neq 0}
            {foreach from=$exchange_list item=exchange}
            {if $type eq 0}
            <tr>
                <td><a href="?act=detail&type={$type}&account={$exchange.account}">{$exchange.account}</td>
                <td>{$exchange.add_time_str}</td>
                <td>{$exchange.balance}</td>
                <td>{$exchange.integral}</td>
                <td>{$exchange.reward}</td>
                <td>{$exchange.integral_await}</td>
                <td>{$exchange.reward_await}</td>
                <td>{$exchange.operator}</td>
                <td>{$exchange.remark}</td>
            </tr>
            {else}
            <tr>
                <td><a href="?act=detail&type={$type}&account={$exchange.business_account}">{$exchange.business_account}</a></td>
                <td>{$exchange.add_time_str}</td>
                <td>{$exchange.balance}</td>
                <td>{$exchange.trade}</td>
                <td>{$exchange.operator}</td>
                <td>{$exchange.remark}</td>
            </tr>
            {/if}
            {/foreach}
            {else}
            {if $st eq '' && $et eq ''}
            <tr>
                <td style="padding: 50px 0" colspan="7" align="center">未有交易产生！</td>
            </tr>
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="7" align="center">
                    <span class="text-size-24 blue icon-info-1" style="vertical-align: middle"></span>
                    <div class="text-size-18 tip-text inline-block">没有查询到符合条件的记录</div>
                </td>
            </tr>
            {/if}
            {/if}
            <tr>
                <td colspan="{if $type eq 0}9{else}6{/if}">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&st={$st}&count={$count}&et={$et}&type={$type}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&st={$st}&count={$count}&et={$et}&type={$type}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&st={$st}&count={$count}&et={$et}&type={$type}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&st={$st}&count={$count}&et={$et}&type={$type}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&st={$st}&count={$count}&et={$et}&type={$type}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>


</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->

{include file="library/footer.lbi"}
</body>
</html>