{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">编辑主营行业</h5>
        <!--        <div class="pull-right"><a class="btn btn-primary" href="?act=passwd">修改密码</a></div>-->
        <div class="clear"></div>
    </div>
    <div class="basicInfo-main">
        <form id="industryEditForm" method="post" action="">
            <fieldset>
                <p>
                    <label class="l-title">分类名：</label>
                    <input class="text-input w300" type="text" maxlength="64" id="industry_name" name="industry_name" value="{$industry.name}" placeholder="请输入分类名"/>
                </p>
                <p>
                    <label class="l-title"></label>
                    <button class="btn btn-primary" type="submit">保存</button>
                    <input type="hidden" name="opera" value="edit" />
                    <input type="hidden" name="id" value="{$industry.id}" />
                </p>

            </fieldset>
        </form>
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>