{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<style>
{literal}
    .select-image {
        cursor: pointer;
    }
{/literal}
</style>

<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />
<script type="text/javascript" >
</script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">添加虚拟产品</h5>
        <div class="clear"></div>
    </div>
    <div class="adminUser-main">
        <form id="productAddForm" name="productAddForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">名称：</label>
                    <input class="text-input w300" type="text" id="name" name="name" placeholder="请输入产品名称">
                    <input type="checkbox" id="status" name="status" value="1"><em>发布</em>
                </p>
                <p class="clear">
                    <label class="l-title">产品分类：</label>
                    <select name="category" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$category_list item=category}
                        <option value="{$category.id}">{$category.name}</option>
                        {/foreach}
                    </select>
                </p>
                <!--
                <p class="clear">
                    <label class="l-title">消费内容：</label>
                    <input style="cursor: pointer;" class="text-input" type="button" id="add-content" value="增加消费内容" />
                </p>
                -->
                <p class="clear" id="show-content">
                </p>
                <p class="clear">
                    <label class="l-title">库存：</label>
                    <input class="text-input w150" type="text" id="inventory" name="single_inventory" placeholder="请输入产品库存">
                </p>
                <p class="clear">
                    <label class="l-title">售价：</label>
                    <input class="text-input w150" type="text" id="price" name="price" placeholder="请输入售价">
                </p>
                <p>
                    <label class="l-title">市场价：</label>
                    <input class="text-input w150" type="text" id="shop_price" name="shop_price" placeholder="请输入市场价">
                </p>
                <p>
                    <label class="l-title">最低售价：</label>
                    <input class="text-input w150" type="text" name="lowest_price" placeholder="请输入最低销售价">
                </p>
                <p>
                    <label class="l-title">产品图片：</label>
                    <input type="hidden" name="img" id="img" placeholder="">
                    <img class="select-image" alt="" src="../upload/image/no-image.png" height="200px">&nbsp;
                </p>
                <p>
                    <label class="l-title">产品简介：</label>
                    <textarea name="desc" rows="5" cols="93"></textarea>
                </p>
                <p>
                    <label class="l-title">产品详情：</label>
                    <textarea name="detail"></textarea>
                </p>
                <p>
                    <label class="l-title">促销价：</label>
                    <input class="text-input w150" type="text" name="promote_price" placeholder="促销价">
                </p>
                <p>
                    <label class="l-title">开始时间：</label>
                    <input class="text-input w300" type="text" name="promote_begin" placeholder="开始时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal} />
                </p>
                <p>
                    <label class="l-title">结束时间：</label>
                    <input class="text-input w300" type="text" name="promote_end" placeholder="结束时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal}>
                </p>
                <p>
                    <label class="l-title">产品排序：</label>
                    <input class="text-input w150" type="text" name="order_view" placeholder="" value="50">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="add" />
                    <button class="btn btn-primary" type="submit">添加</button> &nbsp;<a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>

            </fieldset>
        </form>
    </div>
    <div id="modal-consume-content" class="modal modal-large">
        <div class="modal-dialog">
            <div class="modal-head">
                <h1 class="modal-title">消费内容</h1>
                <a href="javascript: void(0)" class="close-modal" rel="modal:close">&times;</a>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button class="btn btn-primary" type="button" id="confirm">确定</button>&nbsp;
                    <a class="btn btn-primary" rel="modal:close">取消</a>
                </div>
            </div>
        </div>
    </div>
    <div id="modal-edit-consume-content" class="modal modal-large">
        <div class="modal-dialog">
            <div class="modal-head">
                <h1 class="modal-title">消费内容</h1>
                <a href="javascript: void(0)" class="close-modal" rel="modal:close">&times;</a>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button class="btn btn-primary" type="button" id="edit-confirm">确定</button>&nbsp;
                    <a class="btn btn-primary" rel="modal:close">取消</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->
<!-- kindeditor编辑器 -->
<script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
    KindEditor.ready(function(K) {
        var editor1 = K.create("textarea[name='detail']", {
            height: '400px',
            width: '60%',
            cssPath: '../plugins/kindeditor/plugins/code/prettify.css',
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php',
            allowFileManager: true,
            afterCreate: function () {
                var self = this;
                K.ctrl(document, 13, function () {
                    self.sync();
                    K('form[name=productAddForm]')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function () {
                    self.sync();
                    K('form[name=productAddForm]')[0].submit();
                });
            }
        });
        var editor = K.editor({
            allowFileManager: true,
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php'
        });
        K('.select-image').click(function() {
            editor.loadPlugin('image', function() {
                editor.plugin.imageDialog({
                    imageUrl : '',
                    clickFn : function(url, title, width, height, border, align) {
                        if( !width ) {
                            width = 200 + 'px';
                        }
                        if( !height ) {
                            height = 200 + 'px';
                        }

                        K('#img').val(url.replace("{$smarty.const.BASE_DIR}", ""));
                        K('.select-image').attr('src', "../"+url.replace("{$smarty.const.BASE_DIR}", ""));
                        K('.select-image').css('display', 'block');
                        K('.select-image').attr('width', width);
                        K('.select-image').attr('height', height);
                        editor.hideDialog();
                    }
                });
            });
        });
    });
</script>
<script type="text/javascript" src="js/virtual_product/add.js"></script>
{include file="library/footer.lbi"}
</body>
</html>