{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="pull-right"><a class="btn btn-primary" href="?act=add">添加活动</a></div>
        <div class="clear"></div>
    </div>
    <div class="adpos-main">
        <table class="table">
            <thead>
            <tr>
                <th>活动编号</th>
                <th>活动名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {if $adpos_list}
            {foreach from=$adpos_list item=adpos}
            <tr>
                <td>{$adpos.id}</td>
                <td>{$adpos.name}</td>
                <td>
                    <a href="?act=edit&id={$adpos.id}">编辑</a>
                    | <a href="javascript:delete_adpos({$adpos.id});">删除</a>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="3" align="center">您还没有发起活动，立即点击 “<a href="?act=add">这里</a>” 添加活动！</td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
function delete_adpos(id) {
    if(confirm("确定要删除?")) {
        window.location.href = "?act=delete&id="+id;
    }
}
</script>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>
