{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<link rel="stylesheet" href="css/zTreeStyle.css" type="text/css">
<script type="text/javascript">
    var zNodes = {$data};
</script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">会员网络图</h5>
        <!--        <div class="pull-right"><a class="btn btn-primary" href="?act=add">添加内容</a>&nbsp;<a class="btn btn-primary" href="?act=cycle">回收站</a></div>-->
        <div class="clear"></div>
    </div>
    <div class="content_wrap">
        <div class="zTreeDemoBackground left">
            <ul id="treeDemo" class="ztree"></ul>
        </div>
    </div>
</div>
<script type="text/javascript" src="js/jquery.ztree.core-3.5.min.js"></script>
<script type="text/javascript">
    var account = "{$account}";
    var zNodes = {$data};
    {literal}
    var setting = {
        async: {
            enable: true,
            url:"ajax.php",
            autoParam:["account"],
            otherParam:{"current":account,"opera":"get_children"},
            dataFilter: filter
        }
    };

    function filter(treeId, parentNode, responseData) {
        console.log(treeId);
        console.log(responseData.data);
        if ( responseData.error ) {
            alert(responseData.message);
            return null;
        }
        return responseData.data;
    }

    $(document).ready(function(){
        $.fn.zTree.init($("#treeDemo"), setting, zNodes);
    });
    {/literal}
</script>
{include file="library/footer.lbi"}
</body>
</html>