<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/php; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>收货地址</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        {if $act eq 'list'}
        <!--右侧收货地址 开始-->
        <div class="address">
            <div class="address-list">
                {if $address_list}
                {foreach from=$address_list item=address}
                <div class="address-item">
                    <div class="addr-inner">
                        <div class="addr-hd">
                            <span class="name">{$address.consignee}</span>
                            {if $address.is_default}
                            <em>默认地址</em>
                            {/if}
                        </div>
                        <div class="addr-con">
                            <ul>
                                <li>{$address.detail_address_1}</li>
                                <li class="addr-detail">{$address.detail_address_2}</li>
                                <li>{$address.mobile}</li>
                                <li class="addr-btn">
                                    <div class="fr">
                                        <a href="address.php?act=edit&id={$address.id}"><i class="icon" title="编辑">&#xe621;</i></a>
                                        <a href="javascript:delete_address_confirm({$address.id});"><i class="icon" title="删除">&#xe620;</i></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                {/foreach}
                {else}
                您尚未添加任何地址
                {/if}
                <div style="clear: both;"></div>
                <div class="address-item-add">
                    <a href="address.php?act=add" title="添加新的收货地址">
                        <div class="add-inner">
                            <span class="icon">&#xe61f;</span>
                            <p>添加新的收货地址</p>
                        </div>
                    </a>
                </div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <!--右侧收货地址 结束-->
        {/if}
        {if $act eq 'add'}
        <!--新增收货地址 开始-->
        <div class="address">
            <dl class="addr-item">
                <dt><em>*</em>收货人：</dt>
                <dd>
                    <input type="text" id="consignee" placeholder="姓名，如：张三、Lily" class="addr-input fl input_focus" maxlength="12">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt><em>*</em>地址：</dt>
                <dd>
                    <div class="citySelect">
                        <select id="province" class="sele">
                            <option>请选择省</option>
                            {foreach from=$province item=p}
                            <option value="{$p.id}">{$p.name}</option>
                            {/foreach}
                        </select>
                        <select id="city" class="sele">
                            <option value="0">请选择市</option>
                        </select>
                        <select id="district" class="sele">
                            <option value="0">请选择区</option>
                        </select>
                        <select id="group" class="sele hide">
                            <option value="0">请选择商圈</option>
                        </select>
                    </div>
                    <input id="address" class="addr-input row fl input_focus" type="text" placeholder="街道名称或小区名称" maxlength="30">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt><em>*</em>手机号码：</dt>
                <dd>
                    <input id="mobile" type="text" placeholder="手机号码（重要必填）" class="addr-input fl input_focus" maxlength="11">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt>邮编：</dt>
                <dd>
                    <input id="zipcode" type="text" placeholder="选填" class="addr-input fl input_focus" maxlength="11">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt>&nbsp;</dt>
                <dd><label><input id="is_default" type="checkbox" class="check">设为默认收货地址</label></dd>
                <div style="clear: both;"></div>
            </dl>
            <div class="operation">
                <a href="javascript:save_address();" class="sure">保存</a>
                <a href="javascript:history.go(-1);" class="cancel">取消</a>
                <div style="clear: both;"></div>
            </div>
        </div>
        <!--新增收货地址 结束-->
        {/if}
        {if $act eq 'edit'}
        <!--编辑收货地址 开始-->
        <div class="address">
            <dl class="addr-item">
                <dt><em>*</em>收货人：</dt>
                <dd>
                    <input type="text" id="consignee" value={$address.consignee} placeholder="姓名，如：张三、Lily" class="addr-input fl input_focus" maxlength="12">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt><em>*</em>地址：</dt>
                <dd>
                    <div class="citySelect">
                        <select id="province" class="sele">
                            <option>请选择省</option>
                            {foreach from=$province item=p}
                            <option value="{$p.id}" {if $p.id eq $address.province}selected="selected"{/if}>{$p.name}</option>
                            {/foreach}
                        </select>
                        <select id="city" class="sele">
                            <option value="0">请选择市</option>
                        </select>
                        <select id="district" class="sele">
                            <option value="0">请选择区</option>
                        </select>
                        <select id="group" class="sele hide">
                            <option value="0">请选择商圈</option>
                        </select>
                    </div>
                    <input id="address" value="{$address.address}" class="addr-input row fl input_focus" type="text" placeholder="街道名称或小区名称" maxlength="30">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt><em>*</em>手机号码：</dt>
                <dd>
                    <input id="mobile" value="{$address.mobile}" type="text" placeholder="手机号码（重要必填）" class="addr-input fl input_focus" maxlength="11">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt>邮编：</dt>
                <dd>
                    <input id="zipcode" value="{$address.zipcode}" type="text" placeholder="选填" class="addr-input fl input_focus" maxlength="11">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="addr-item">
                <dt>&nbsp;</dt>
                <dd><label><input id="is_default" type="checkbox" class="check" {if $address.is_default eq 1}checked="checked"{/if}>设为默认收货地址</label></dd>
                <div style="clear: both;"></div>
            </dl>
            <div class="operation">
                <input type="hidden" name="address_id" value="{$address.id}" id="address_id"/>
                <a href="javascript:save_address();" class="sure">保存</a>
                <a href="javascript:history.go(-1);" class="cancel">取消</a>
                <div style="clear: both;"></div>
            </div>
        </div>
        <!--编辑收货地址 结束-->
        {/if}
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
{if $act eq 'list'}
<script type="text/javascript">
    function delete_address_confirm(eid) {
        if( confirm('确定删除该收货地址？') ) {
            delete_address(eid);
        } else {
            return false;
        }
    }

    function delete_address(id) {
        id = parseInt(id);
        var msg = "";

        if(isNaN(id) || id <= 0) {
            msg += "-参数错误<br/>";
        }

        if(msg == "") {
            var url = "address.php";
            var data = { "opera":"delete", "eid":id };

//            show_mask();
            $.post(url, data, delete_address_handler, "json");
        } else {
            alert(msg);
        }
    }

    function delete_address_handler(response) {
//        hide_mask();

        alert(response.msg);
        if(response.error == 0) {
//            $("#dialog_close_btn").attr("href", "javascript:window.location.reload();");
//            $("#dialog_close").click(function() {
                window.location.reload();
//            });
        }
    }
</script>
{/if}
{if $act eq 'add' || $act eq 'edit'}
<script type="text/javascript">
    var city = {$city_json};
    var district = {$district_json};
    var group = {$group_json};

    function save_address() {
        var province = $("#province").val();
        var city = $("#city").val();
        var district = $("#district").val();
        var group = $("#group").val();
        var mobile =$("#mobile").val();
        var consignee = $("#consignee").val();
        var address = $("#address").val();
        var is_default = document.getElementById("is_default").checked;
        var msg = "";

        province = parseInt(province);
        city = parseInt(city);
        district = parseInt(district);
        group = parseInt(group);

        {if $act eq 'edit'}
        var address_id = $("#address_id").val();
        address_id = parseInt(address_id);
        {/if}

        if(consignee == "") {
            msg += "-请填写收货人\n";
        }

        if(isNaN(province) || province <= 0) {
            msg += "-请选择省份\n";
        }

        if(isNaN(city) || city <= 0) {
            msg += "-请选择城市\n";
        }

        if(isNaN(district) || district <= 0) {
            msg += "-请选择地区\n";
        }

        if(address == "") {
            msg += "-请填写街道地址\n";
        }

        if(mobile == "") {
            msg += "-请填写手机号码\n";
        }

        if(msg != "") {
            alert(msg);
        } else {
//            show_mask();

            var url = "address.php";
            var data = { "opera":"{$act}", "province":province, "city":city, "district":district, "group":group, "address":address,
                "mobile":mobile, "consignee":consignee, "is_default":is_default{if $act eq 'edit'},"address_id":address_id{/if} };

            $.post(url, data, save_address_handler, "json");
        }
    }

    function save_address_handler(response) {
//        hide_mask();
        alert(response.msg);
        if(response.error == 0) {
            window.localStorage.setItem("need_refresh", 1);
            var is_default = document.getElementById("is_default").checked;

            if(is_default) {
                window.localStorage.setItem("address_id", response.id);
            }
//            $("#dialog_close").bind("click", function() { window.history.back(); });
//            $("#dialog_close_btn").bind("click", function() { window.history.back(); });
            window.history.back();
        }
    }

    $(function(){

        {if $act eq 'edit'}
        for(var i in city[{$address.province}]) {
            $("#city").append('<option value="'+city[{$address.province}][i].id+'">'+city[{$address.province}][i].name+'</option>');
        }

        $("#city").val({$address.city});

        for(var i in district[{$address.city}]) {
            $("#district").append('<option value="'+district[{$address.city}][i].id+'">'+district[{$address.city}][i].name+'</option>');
        }

        $("#district").val({$address.district});

        for(var i in group[{$address.district}]) {
            $("#group").append('<option value="'+group[{$address.district}][i].id+'">'+group[{$address.district}][i].name+'</option>');
        }

        $("#group").val({$address.group});
        {/if}


        $("#province").bind("change", function() { select_province($(this).val()); });
        $("#city").bind("change", function() { select_city($(this).val()); });
        $("#district").bind("change", function() { select_district($(this).val()); });
    });

    function select_province(id) {
        document.getElementById("city").length = 1;
        document.getElementById("district").length = 1;
        document.getElementById("group").length = 1;

        for(var i in city[id]) {
            $("#city").append('<option value="'+city[id][i].id+'">'+city[id][i].name+'</option>');
        }
    }

    function select_city(id) {
        document.getElementById("district").length = 1;
        document.getElementById("group").length = 1;

        for(var i in district[id]) {
            $("#district").append('<option value="'+district[id][i].id+'">'+district[id][i].name+'</option>');
        }
    }

    function select_district(id) {
        document.getElementById("group").length = 1;
        var flag = false;
        for(var i in group[id]) {
            flag = true;
            $("#group").append('<option value="'+group[id][i].id+'">'+group[id][i].name+'</option>');
        }
    }
</script>
{/if}
</body>
</html>