<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
    <style>
        {literal}
        .apply-status {
            display: block;
            margin: 10px auto;
            width: 3rem;
            line-height: 3rem;
            font-size: 2rem;
            color: #fff;
            background: #ff0000;
            border-radius: 2rem;
            text-align: center;
        }
        .apply-status-content {
            text-align: center;
            line-height: 2rem;
        }
        .apply-status-gray {
            background-color: #ddd;
        }
        {/literal}
    </style>
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>商家进驻进度</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <h3 style="font-size: 0.8rem; font-weight: normal; text-align: center; line-height: 1.8rem;">您的审核进度</h3>

        <h4 class="apply-status">1</h4>
        <p class="apply-status-content">提交商家进驻申请</p>


        <h4 class="apply-status {if $status lt 1}apply-status-gray{/if}">2</h4>
        <p class="apply-status-content">平台验证审核</p>


        <h4 class="apply-status {if $status lt 2}apply-status-gray{/if}">3</h4>
        <p class="apply-status-content">申请成功，账号发放 {if $status gt 1}商机编号：{$smarty.session.business_account}{/if}</p>

    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>

</body>
</html>