<div class="aside">
    <div class="home-nav">
        <dl>
            <dt><i class="icon p">&#xe611;</i><i class="icon m">&#xe612;</i><a href="#" target="_parent" title="订单信息">订单信息</a></dt>
            <dd><a href="order.php" target="_parent" title="我的订单" {if $is_login && $aside_hover eq 'order.php'}class="hover"{/if}>我的订单</a></dd>
            <dd><a href="wishlist.php" target="_parent" title="我的收藏" {if $is_login && $aside_hover eq 'wishlist.php'}class="hover"{/if}>我的收藏</a></dd>
            <dd><a href="history.php" target="_parent" title="我的足迹" {if $is_login && $aside_hover eq 'history.php'}class="hover"{/if}>我的足迹</a></dd>
        </dl>
        <dl>
            <dt><i class="icon p">&#xe611;</i><i class="icon m">&#xe612;</i><a href="#" target="_parent" title="我的资产">我的资产</a></dt>
            <dd><a href="#" target="_parent" title="余额">余额</a></dd>
            <dd><a href="#" target="_parent" title="佣金">佣金</a></dd>
            <dd><a href="#" target="_parent" title="积分">积分</a></dd>
            <dd><a href="#" target="_parent" title="优惠券">优惠券</a></dd>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="#" target="_parent" title="我的资料">我的资料</a></dt>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="address.php" target="_parent" title="收货地址" {if $is_login && $aside_hover eq 'address.php'}class="hover"{/if}>收货地址</a></dt>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="#" target="_parent" title="我的推广">我的推广</a></dt>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="#" target="_parent" title="我的分销">我的分销</a></dt>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="#" target="_parent" title="我的团队">我的团队</a></dt>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="#" target="_parent" title="我要开店">我要开店</a></dt>
        </dl>
        <dl>
            <dt><i class="icon">&#xe613;</i><a href="#" target="_parent" title="投诉维权">投诉维权</a></dt>
        </dl>
    </div>
</div>
<div style="clear: both"></div>