<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我的银行卡</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        {if $act eq 'list'}
        <!--我的银行卡 开始-->
        <div class="address-list bank">
            {foreach from=$bank_card_list item=bank_card}
            <div class="address-item">
                <div class="addr-inner">
                    <div class="addr-hd">
                        <span class="name">{$bank_card.bank}</span>
                        <em>存储卡</em>
                    </div>
                    <div class="addr-con">
                        <ul>
                            <li>卡号：{$bank_card.bank_card}</li>
                            <li>持卡人姓名：{$bank_card.bank_account}</li>
                            <li>手机号码：{$bank_card.mobile}</li>
                            <li class="addr-btn">
                                <div class="fr">
                                    <a href="?act=edit&id={$bank_card.id};"><i class="icon" title="编辑">&#xe621;</i></a>
                                    <a href="javascript:delete_bank_confirm({$bank_card.id});"><i class="icon" title="删除">&#xe620;</i></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            {/foreach}

            <div style="clear: both;"></div>
            <div class="address-item-add">
                <a href="?act=add" title="添加银行卡">
                    <div class="add-inner">
                        <span class="icon">&#xe61f;</span>
                        <p>添加银行卡</p>
                    </div>
                </a>
            </div>
        </div>
        <div style="clear: both;"></div>
        <!--我的银行卡 结束-->
        {/if}

        {if $act eq 'add'}
        <!--我的银行卡 开始-->
        <div class="add-bank">
            <dl class="form-item">
                <dt><em>*</em>持卡人：</dt>
                <dd>
                    <input type="text" name="bank_account" id="bank_account" placeholder="开户人姓名" class="fl" maxlength="12">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>银行卡号：</dt>
                <dd>
                    <input type="text" name="bank_card" id="bank_card" placeholder="请输入银行卡号" class="fl" maxlength="">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>开户银行：</dt>
                <dd>
                    <input type="text" name="bank" id="bank" placeholder="请输入开户银行" class="fl" maxlength="">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>手机号码：</dt>
                <dd>
                    <input type="text" name="mobile" id="mobile" placeholder="银行卡的预留号码" class="fl" maxlength="11">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>账户密码：</dt>
                <dd>
                    <input type="password" name="password" id="password" placeholder="请输入账户密码" class="fl" maxlength="">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <div class="operation">
                <a href="javascript:save_bank();" class="sure">保存</a>
                <div style="clear: both;"></div>
            </div>
        </div>
        <!--我的银行卡 结束-->
        {/if}

        {if $act eq 'edit'}
        <!--我的银行卡 开始-->
        <div class="add-bank">
            <dl class="form-item">
                <dt><em>*</em>持卡人：</dt>
                <dd>
                    <input value="{$bank_card.bank_account}" type="text" name="bank_account" id="bank_account" placeholder="开户人姓名" class="fl" maxlength="12">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>银行卡号：</dt>
                <dd>
                    <input value="{$bank_card.bank_card}" type="text" name="bank_card" id="bank_card" placeholder="请输入银行卡号" class="fl" maxlength="">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>开户银行：</dt>
                <dd>
                    <input value="{$bank_card.bank}" type="text" name="bank" id="bank" placeholder="请输入开户银行" class="fl" maxlength="">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>手机号码：</dt>
                <dd>
                    <input value="{$bank_card.mobile}" type="text" name="mobile" id="mobile" placeholder="银行卡的预留号码" class="fl" maxlength="11">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>账户密码：</dt>
                <dd>
                    <input type="password" name="password" id="password" placeholder="请输入账户密码" class="fl" maxlength="">
                    <p></p>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <div class="operation">
                <input type="hidden" name="eid" id="eid" value="{$bank_card.id}"/>
                <a href="javascript:save_bank();" class="sure">保存</a>
                <div style="clear: both;"></div>
            </div>
        </div>
        <!--我的银行卡 结束-->
        {/if}

    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
{if $act eq 'list'}
<script type="text/javascript">
    var loading;
    var id;
    function delete_bank_confirm(eid) {
        id = eid;
        layer.confirm('确定删除银行卡?', {
            btn: ['确定','取消'] //按钮
        }, function() {
            delete_bank(id);
        });
    }

    function delete_bank(id) {
        id = parseInt(id);
        var msg = "";

        if(isNaN(id) || id <= 0) {
            msg += "-参数错误<br/>";
        }

        if(msg == "") {
            var url = "bank.php";
            var data = { "opera":"delete", "eid":id };

            show_mask();
            $.post(url, data, delete_bank_handler, "json");
        } else {
            layer.msg(msg);
        }
    }

    function delete_bank_handler(response) {
        hide_mask();

        if(response.error == 0) {
            layer.msg(response.msg, function() {
                window.location.reload();
            });
        } else {
            layer.msg(response.msg);
        }
    }

    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });
    }

    function hide_mask() {
        layer.close(loading);
    }
</script>
{/if}
{if $act eq 'add' || $act eq 'edit'}
<script type="text/javascript">
    var loading;
    function save_bank() {
        var bank_account = $("#bank_account").val();
        var bank_card = $("#bank_card").val();
        var bank = $("#bank").val();
        var password = $("#password").val();
        var mobile = $("#mobile").val();
        var msg = "";
        {if $act eq 'edit'}
        var id = $("#eid").val();
        id = parseInt(id);
        var msg = "";

        if(isNaN(id) || id <= 0) {
            msg += "-参数错误";
        }
        {/if}


        if(bank == "") {
            msg += "-请填写开户银行<br/>";
        }

        if(bank_account == "") {
            msg += "-请填写开户人姓名<br/>";
        }

        if(bank_card == "") {
            msg += "-请填写银行卡号<br/>";
        }

        if(mobile == "") {
            msg += "-请输入该卡在银行预留的号码<br/>";
        }

        if(password == "") {
            msg += "-请输入账户密码<br/>";
        }

        if(msg == "") {
            var url = "bank.php";
            {if $act eq 'add'}
            var data = { "opera":"{$act}", "bank":bank, "bank_account":bank_account, "bank_card":bank_card, "mobile":mobile, "password":password };
            {else}
            var data = { "opera":"{$act}", "eid":id, "bank":bank, "bank_account":bank_account, "bank_card":bank_card, "mobile":mobile, "password":password };
            {/if}

            show_mask();
            $.post(url, data, save_bank_handler, "json");
        } else {
            layer.msg(msg);
        }
    }

    function save_bank_handler(response) {
        hide_mask();
        if(response.error == 0) {
            window.localStorage.setItem("need_refresh", 1);
            layer.msg(response.msg, function() {
                history.back();
            });
        } else {
            layer.msg(response.msg);
        }
    }

    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });
    }

    function hide_mask() {
        layer.close(loading);
    }
</script>
{/if}
</body>
</html>