<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>确认订单</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 确认订单 开始 -->
<div class="confirm-order container">
    <!--选择收货地址 开始-->
    <div class="confirm-addr">
        <div class="confirm-addr-t">
            <h3>收货人信息</h3>
            <input type="hidden" name="address_id" value="{$address_list[0].id}" id="address_id"/>
        </div>
        <div class="address-list">
            {foreach from=$address_list item=address}
            <div class="address-item {if $address.is_default eq 1}addr-active{/if}" data-id="{$address.id}">
                <div class="addr-inner">
                    <ins class="icon">&#xe624;</ins>
                    <div class="addr-hd">
                        <span class="name">{$address.consignee}</span>
                        {if $address.is_default}
                        <em>默认地址</em>
                        {/if}
                    </div>
                    <div class="addr-con">
                        <ul>
                            <li>{$address.province_name}{$address.city_name}{$address.district_name}{$address.group_name}</li>
                            <li class="addr-detail">{$address.address}</li>
                            <li>{$address.mobile}</li>
                        </ul>
                    </div>
                </div>
            </div>
            {/foreach}
        </div>
        <div style="clear: both;"></div>
        <div class="addr-confirm-btn">
            <!-- 大于三个显示更多地址 开始 -->
            <div class="addr-switch switch-on" style="display: none;">
                <span>更多地址</span><b class="icon">&#xe607;</b>
            </div>
            <div class="addr-switch switch-off" style="display: none;">
                <span>收起地址</span><b class="icon">&#xe608;</b>
            </div>
            <!-- 大于三个显示更多地址 结束 -->
            <div class="select-new-addr">
                <a href="address.php" target="_blank" title="管理收货地址">管理收货地址</a>
            </div>
            <div style="clear: both;"></div>
        </div>
    </div>
    <!--选择收货地址 结束-->

    <!--选择支付方式 开始-->
    <div class="select-pay-type">
        <div class="pay-type-t">
            <h3>支付方式</h3>
                <input type="hidden" name="payment_id" value="" id="payment_id"/>
        </div>
        <ul>
            {foreach from=$payment_list item=payment}
            <li class="payment-item" data-id="{$payment.id}">
                <ins class="icon">&#xe624;</ins>
                {$payment.name}
            </li>
            {/foreach}
        </ul>
        <div style="clear: both;"></div>
    </div>
    <!--选择支付方式 结束-->

    <!-- 确认订单信息 开始 -->
    <div class="cart-inner">
        <div class="cart-title">
            <h3>送货清单</h3>
        </div>
        <div class="cart-con">
            <!--购物清单 表头 开始-->
            <ul class="cart-box-title">
                <li class="cart-cell a-c-1">
                    &nbsp;
                </li>
                <li class="cart-cell a-c-2">商品信息</li>
                <li class="cart-cell a-c-3">单价</li>
                <li class="cart-cell a-c-4">数量</li>
                <li class="cart-cell a-c-5">小计(元)</li>
<!--                <li class="cart-cell a-c-6">配送方式</li>-->
                <div style="clear: both;"></div>
            </ul>
            <!--购物清单 表头 结束-->
            <div class="cart-list">
                <div class="cart-list-item">
                    {foreach from=$cart_list item=cart}
                    <!-- 店铺 开始 -->
                    <div class="seller">
                        <a target="_blank" href="shop.php?id={$cart.b_id}">{$cart.shop_name}</a>
                        <div style="clear: both;"></div>
                    </div>
                    <div class="attice">
                        {foreach from=$cart.products item=product}
                        <!-- 同店产品 开始 -->
                        <div class="cart-list-cell">
                            <div class="cart-list-choice">
                                &nbsp;
                            </div>
                            <div class="cart-list-goods">
                                <a class="pro-img" target="_blank" href="product.php?id={$product.p_id}" title="{$product.name} {$product.attributes}">
                                    <img src="{$product.img|build_url}" alt="{$product.name} {$product.attributes}">
                                </a>
                            <span class="cart-list-goods-txt">
                                <a target="_blank" href="product.php?id={$product.p_id}" title="{$product.name} {$product.attributes}">{$product.name} {$product.attributes}</a><br>
                            </span>
                            </div>
                            <div class="cart-list-snprice">
                                {if $product.integral gt 0}
                                <q class="snPrice c3"><i></i><em>{sprintf("%.2f", $product.integral)}积分</em></q>
                                {else}
                                <q class="snPrice c3"><i>¥</i><em>{sprintf("%.2f", $product.price)}</em></q>
                                {/if}
                            </div>
                            <div class="cart-list-amount">
                                <div class="cart-goods-cout">
                                    x{$product.number}
                                </div>
                            </div>
                            <div class="cart-list-price">
                                {if $product.integral gt 0}
                                <span class="snPrice" id="product-price-{$product.p_id}"><em>{sprintf("%.2f", ($product.integral * $product.number))}积分</em></span>
                                {else}
                                <span class="snPrice" id="product-price-{$product.p_id}"><i>¥</i><em>{sprintf("%.2f", ($product.price * $product.number))}</em></span>
                                {/if}
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        <!-- 同店产品 结束 -->
                        {/foreach}
                    </div>
                    <!--商家留言 开始-->
                    <div class="fl" style="width: 100%; padding-bottom: 20px">
                        <b>给商家留言</b>
                        <span><input name="comment[{$cart.b_id}]" id="comment_{$cart.b_id}" placeholder="要对商家说...（限70字）" value="" data-original-length="0" type="text" maxlength="70" style="border: 1px solid #BBB;line-height: 2;width: 100%;"></span>
                    </div>
                    <div style="clear: both;"></div>
                    <!--商家留言 结束-->
                    <!--运费 开始-->
                    <div class="ship-price-box fr">
                        <span class="ship-price">
                            <b>配送方式：</b>
                            <span class="snPrice"><em>{$cart.delivery_list.0.delivery_name}</em></span>
                        </span>
                        <span class="ship-price">
                            <b>运费：</b>
                            <span class="snPrice"><i>¥</i><em>{sprintf("%.2f", $cart.delivery_list.0.delivery_fee)}</em></span>
                        </span>
                    </div>
                    <!--运费 结束-->
                    <div style="clear: both;"></div>

                    <!-- 店铺 结束 -->
                    {/foreach}

                    <!--商品总金额结算 开始-->
                    <div style="height: 102px; display: none;"></div>
                    <div class="shoppayarea" style="left: 194px;">
                        <div class="row row-1">
                            <span class="settle-item">
                                {if $user_info.reward gt 0 and $user_info.level_id gt 0}
                                <input name="use_reward" id="use_reward" type="checkbox" class="" value="use_reward"/>
                                <label>
                                    可用佣金：
                                    <span><i>¥</i><em>{if $user_info.reward/$config.reward_rate>$total_amount}
                                    {$total_amount*$config.reward_rate}
                                    {assign var=reward value=$total_amount}
                                    {else}
                                    {$user_info.reward}
                                    {assign var=reward value=$user_info.reward/$config.reward_rate}
                                    {/if}
                                        </em></span>
                                </label>
                                {/if}
                            </span><br />
                            <span class="settle-item">
                                {if $user_info.balance gt 0}
                                <input name="use_balance" id="use_balance" type="checkbox" class="" value="use_balance"/>
                                <label>
                                    可用余额：
                                    <span><i>¥</i><em>{if $user_info.balance>$total_amount}{$total_amount}{else}{$user_info.balance}{/if}</em></span>

                                </label>
                                {/if}
                            </span>
                            <div class="price-items">
                                <div class="price-items">
                                    <p class="pro-amount price"><label>商品总金额：</label><span><i>¥</i><em>{sprintf("%.2f", $total_product_amount)}</em></span></p>
                                    <p class="favour-amount price">
                                    <p class="trans-amount price"><label>运费：</label><span><i>¥</i><em>{sprintf('%.2f', $total_delivery_fee)}</em></span></p>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        <div class="row row-2">
                            <div class="shopSubmit submit00">
                                <a class="btn-orange fr" title="提交订单" href="javascript:submit_order();" ><em>提交订单</em></a>
                            </div>
                            <div class="pro-desc">
                                <p>
                                    <span class="price"><b>商品应付金额：</b><i>¥</i><em id="total_amount">{sprintf("%.2f", $total_amount)}</em></span>
                                </p>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                    <!--商品总金额结算 结束-->
                </div>
            </div>
        </div>
    </div>

    <div style="clear: both"></div>
    <!-- 确认订单信息 结束 -->
</div>
<!-- 确认订单 结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var delivery_list = {$delivery_list_json};
    var total_amount = {$total_amount};
    var total_product_amount = {$total_product_amount};
    var total_number = {$total_number};

    var loading;

    $(function(){

        $('.address-item').on('click', function() {
            $('#address_id').val($(this).attr('data-id'));
        });

        $('.payment-item').on('click', function() {
            $('#payment_id').val($(this).attr('data-id'));
        });

        if($("#use_integral") != undefined) {
            $("#use_integral").bind("click", function() { use_mode(); });
        }

        if($("#use_reward") != undefined) {
            $("#use_reward").bind("click", function() { use_mode(); });
        }

        if($("#use_balance") != undefined) {
            $("#use_balance").bind("click", function() { use_mode(); });
        }

        {if !$delivery_support}
            //如果部分商品不支持配送，则提示用户
            layer.msg("部分商品不支持您所在地区的配送或服务，系统已自动为您剔除");
            {if $target neq ""}
//        $("#dialog_close_btn").click(function(){
//            window.location.href = "{$target}";
//        });
//
//        $("#dialog_close").click(function(){
//            window.location.href = "{$target}";
//        });
            {/if}
        {/if}
    });

    function submit_order() {
        var address_id = $("#address_id").val();
        var payment_id = $("#payment_id").val();
        var comments = {};
        var comment_ele = $("input[type='text']");
        var msg = "";

        if(total_number <= 0) {
            layer.msg("请选择要购买的产品");
            return false;
        }

        var data = { "opera":"submit_order", "use_integral": false, "use_reward": false, "use_balance": false, "address_id": address_id, "payment_id": payment_id, "comments": comments, "delivery_list": delivery_list };
        if($("#use_integral") != undefined && $("#use_integral").is(":checked")) {
            data.use_integral = true;
            if(total_amount < 0) {
                $("#use_integral").attr("checked", false);
                return false;
            }
        }

        if($("#use_reward") != undefined && $("#use_reward").is(":checked")) {
            data.use_reward = true;
            if(total_amount < 0) {
                $("#use_reward").attr("checked", false);
                return false;
            }
        }

        if($("#use_balance") != undefined && $("#use_balance").is(":checked")) {
            data.use_balance = true;
            if(total_amount < 0) {
                $("#use_balance").attr("checked", false);
                return false;
            }
        }

        for(var i = 0; i < comment_ele.length; i++) {
            comments[comment_ele[i].id.replace("comment_", "")] = comment_ele[i].value;
        }
        data.comments = comments;
        console.info(JSON.stringify(data));

        address_id = parseInt(address_id);
        payment_id = parseInt(payment_id);

        if(isNaN(address_id) || address_id <= 0) {
            msg += "-请填写收货地址\n";
        }

        if(isNaN(payment_id) || payment_id <= 0) {
            msg += "-请选择支付方式\n";
        }

        if(msg != "") {
            layer.msg(msg);
            return false;
        }

        var url = "checkout.php";

        show_mask();
        $.post(url, data, submit_order_handler, "json");
    }

    function submit_order_handler(response) {
        hide_mask();
        if(response.error == 0) {
            if(response.count == 1) {
                if(response.order_status == 1) {
                    if( response.order_sn ) {
                        layer.confirm('马上支付?', {
                            btn: ['确定', '取消'] //按钮
                        }, function () {
                            simulation_pay(response.order_sn);
                        });
                    } else {
                        window.location.href = "order.php";
                    }
//                    window.location.href = "topay.php";
                } else {
                    window.location.href = "order.php";
                }
            } else {
                window.location.href = "order.php";
            }
        } else {
            layer.msg(response.msg);
        }
    }

    function simulation_pay(order_sn) {
        var url = 'checkout.php';
        var param = { "opera": "simulation_pay", "order_sn" : order_sn  };
        show_mask();
        $.post(url , param, simulation_pay_handler, 'json');
    }

    function simulation_pay_handler(response) {
        hide_mask();
        if( response.error == 0 ) {
            /*
            layer.msg(response.msg, function() {
                window.location.href = "order.php";
            });
            */
            $("body").append(response.content);
        } else {
            layer.msg(response.msg);
        }
    }

    function use_mode() {
        var data = { "opera":"calculate_fee", "use_integral": false, "use_reward": false, "use_balance": false };
        if($("#use_integral") != undefined && $("#use_integral").is(":checked")) {
            data.use_integral = true;
            if(total_amount < 0) {
                $("#use_integral").attr("checked", false);
                return false;
            }
        }

        if($("#use_reward") != undefined && $("#use_reward").is(":checked")) {
            data.use_reward = true;
            if(total_amount < 0) {
                $("#use_reward").attr("checked", false);
                return false;
            }
        }

        if($("#use_balance") != undefined && $("#use_balance").is(":checked")) {
            data.use_balance = true;
            if(total_amount < 0) {
                $("#use_balance").attr("checked", false);
                return false;
            }
        }

        var url = "checkout.php";

        show_mask();
        $.post(url, data, use_mode_handler, "json");
    }

    function use_mode_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#total_amount").text(response.total_amount.toFixed(2));
            total_amount = response.total_amount;
        } else {
            layer.msg(response.msg);
        }
    }

    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });

    }

    function hide_mask() {
        layer.close(loading);
    }
</script>
</body>
</html>