<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <a href="order.php" target="_blank">我的订单</a><span class="gt">&gt;</span>
    <span>订单评价</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--订单评价 开始-->
        <div class="comment">
            <div class="comment-title">
                <h3><i class="icon">&#xe614;</i>订单评价</h3>
            </div>
            <div class="comment-tb">
                <dl class="form-item">
                    <dt><em>*</em>店铺评分：</dt>
                    {if $order.is_comment eq 0}
                    <dt class="i-star">
                        <i class="icon" onclick="star(1, 'server_star');">&#xe60b;</i><i class="icon onclick="star(2, 'server_star');">&#xe60b;</i><i class="icon" onclick="star(3, 'server_star');">&#xe60b;</i><i class="icon" onclick="star(4, 'server_star');">&#xe60b;</i><i class="icon" onclick="star(5, 'server_star');">&#xe60b;</i>
                    </dt>
                    <dt class="operation fr">
                        <a href="javascript:shop_comment('{$order.order_sn}');" class="sure">评分</a>
                        <input type="hidden" value="5" id="server_star" name="server_star"/>
                    </dt>
                    {else}
                    <dt class="i-star">
                    已评价
                    </dt>
                    {/if}
                    <div style="clear: both;"></div>
                </dl>
                {foreach from=$order_detail item=p}
                <div class="order-list">
                    <table cellpadding="0" cellspacing="0" class="order-tb">
                        <tbody>
                        <tr class="sep-row"><td colspan="5"></td></tr>

                        <tr class="tr-th">
                            <td colspan="5">
                                <span class="gap"></span>
                                <span class="dealtime" title="{date('Y-m-d H:i:s', $order.add_time)}">{date('Y-m-d H:i:s', $order.add_time)}</span>
                                <input type="hidden" value="{date('Y-m-d H:i:s', $order.add_time)}">
                                     <span class="number">订单号：
                                         <a target="_blank" href="#">{$order.order_sn}</a>
                                     </span>
                                <div class="tr-operate">
                                    <span class="order-shop">
                                        <span class="shop-txt">{$order.shop_name}</span>
                                        <a class="icon" href="shop.php?sn={$order.order_sn}" title="进入店铺">&#xe61b;</a>
                                    </span>
                                </div>
                                <div style="clear: both;"></div>
                            </td>
                        </tr>

                        <tr class="tr-bd">
                            <td>
                                <div class="goods-item p-1073757">
                                    <div class="p-img">
                                        <a href="#" target="_blank">
                                            <img class="" src="{$p.img}" title="{$p.product_name} {$p.product_attributes}" width="60" height="60">
                                        </a>
                                    </div>
                                    <div class="p-msg">
                                        <div class="p-name"><a href="product.php?id={$p.id}" class="a-link" target="_blank" title="{$p.product_name} {$p.product_attributes}">{$p.product_name} {$p.product_attributes}</a></div>
                                    </div>
                                    <div style="clear: both;"></div>
                                </div>
                                <div class="goods-number">
                                    x{$p.count}
                                </div>
                                <div style="clear: both;"></div>
                            </td>
                            <td rowspan="2">
                                <div class="amount">
                                    <strong>{if $p.integral gt 0}{$p.integral*$p.count}积分{else}¥{sprintf('%.2f', $p.product_price*$p.count)}{/if}</strong> <br>
                                    {if $p.has_comment}
                                    <span class="ftx-13">已评价</span><br>
                                    {/if}
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div style="clear: both;"></div>
                {if empty($p.has_comment)}
                <dl class="form-item">
                    <dt><em>*</em>产品评分：</dt>
                    <dd class="i-star">
                        <i class="icon" onclick="star(1, 'product-star-{$p.id}');">&#xe60b;</i>
                        <i class="icon" onclick="star(2, 'product-star-{$p.id}');">&#xe60b;</i>
                        <i class="icon" onclick="star(3, 'product-star-{$p.id}');">&#xe60b;</i>
                        <i class="icon" onclick="star(4, 'product-star-{$p.id}');">&#xe60b;</i>
                        <i class="icon" onclick="star(5, 'product-star-{$p.id}');">&#xe60b;</i>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <dl class="form-item">
                    <dt><em>*</em>心得：</dt>
                    <dd class="i-star">
                        <textarea name="" id="comment-{$p.id}" class="area" cols="30" rows="10" placeholder="分享心得，告诉小伙伴们这款产品赞不赞"></textarea>
                        <input type="hidden" id="product-star-{$p.id}" value="5"/>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <div class="operation">
                    <a href="javascript:product_comment({$p.id}, '{$p.product_sn}');" class="sure">发表评论</a>
                    <div style="clear: both;"></div>
                </div>
                {/if}
                {/foreach}
            </div>
        </div>
        <!--订单评价 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>

<script type="text/javascript">
    $(function(){
        $(".i-star i").click(function(){
            $(this).siblings().css("color","#ffce28");
            $(this).css("color","#ffce28");
            $(this).nextAll().css("color","#ccc");
        })
    })
</script>
<script type="text/javascript">
    var loading;

    function shop_comment(order_sn) {
        var star = $("#server_star]").val();
        star = parseInt(star);

        if(isNaN(star) || star <= 0) {
            layer.msg("请选择评价星级");
            return false;
        }

        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"comment", "order_sn":order_sn, "star":star };

            show_mask();
            $.post(url, data, shop_comment_handler, "json");
        }
    }

    function shop_comment_handler(response) {
        if(response.error == 0) {
            window.location.reload();
        } else {
            hide_mask();
            layer.msg(response.msg);
        }
    }

    function product_comment(id, product_sn) {
        var star = $("#product-star-"+id).val();
        star = parseInt(star);

        if(isNaN(star) || star <= 0) {
            layer.msg("请选择评价星级");
            return false;
        }

        if( product_sn == '') {
            layer.msg("请选择要评价的产品");
            return false;
        }

        var comment = $("#comment-"+id).val();
        if( comment == '') {
            layer.msg("请填写评语");
            return false;
        }
        var url = "order.php";
        var data = { "opera":"product_comment", "product_sn":product_sn, "star":star, "comment":comment };

        show_mask();
        $.post(url, data, product_comment_handler, "json");

    }

    function product_comment_handler(response) {
        hide_mask();
        layer.msg(response.msg, function() {
            if(response.error == 0) {
                window.location.reload();
            }
        });

    }

    function star(num, id) {
        $("#"+id).val(parseInt(num));
    }

    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });
    }

    function hide_mask() {
        layer.close(loading);
    }
</script>
</body>
</html>