<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我的分销</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        {if $product_list}
        <!--右侧我的分销 开始-->
        <div class="distribution">
            <div class="distribution-list">
                <div class="distribution-h">
                    <div class="distribution-h-inner">
                        <label><input type="checkbox" class="check" id="check-all" onclick="check_all();">全选</label>
                        <a href="javascript:multi_delete_distribution();" class="del-btn">删除</a>
                    </div>
                </div>
                <div class="distribution-c">
                    <ul>
                        {foreach from=$product_list item=p}
                        <li>
                            <div class="distribution-item">
                                <input type="checkbox" class="check check-product" data-cid="{$p.id}" id="check-product-{$p.id}" onclick="check_product({$p.id})">
                                <div class="p-img">
                                    <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">
                                        <img alt="{$p.name}" src="{$p.img}">
                                    </a>
                                </div>
                                <div class="p-name">
                                    <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">{$p.name}</a>
                                </div>
                                <div class="price">￥{sprintf('%.2f', $p.price)}</div>
                            </div>
                            <div style="clear: both;"></div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
            </div>
        </div>
        <!--右侧我的分销 结束-->
        {else}
        <!--右侧我的分销 开始-->
        <div class="distribution">
            <div class="distribution-list">
                <div class="tips-empty">
                    <div class="tips-icon">
                        <span class="icon">&#xe61a;</span>
                    </div>
                    <div class="tips-detail">
                        对不起，你当前没有分销过任何产品！
                    </div>
                </div>
            </div>
        </div>
        <!--右侧我的分销 结束-->
        {/if}
        <div class="might-like">
            <div class="might-like-inner">
                <div class="inner-head">
                    <h3 class="fl">根据浏览，猜你喜欢</h3>
                    <span class="fr"><i class="icon">&#xe618;</i>换一组</span>
                    <div style="clear: both;"></div>
                </div>
                <div class="inner-con">
                    <ul class="p-list">
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">
                                    <img width="90" height="90" alt="圣宝先自营复合酵素" src="images/sbx-product.png">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">圣宝先自营复合酵素</a>
                            </div>
                            <div class="p-price"><span>￥</span>5099.<span>00</span></div>
                        </li>
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">
                                    <img width="90" height="90" alt="圣宝先自营复合酵素" src="images/sbx-product.png">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">圣宝先自营复合酵素</a>
                            </div>
                            <div class="p-price"><span>￥</span>5099.<span>00</span></div>
                        </li>
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">
                                    <img width="90" height="90" alt="圣宝先自营复合酵素" src="images/sbx-product.png">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">圣宝先自营复合酵素</a>
                            </div>
                            <div class="p-price"><span>￥</span>5099.<span>00</span></div>
                        </li>
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">
                                    <img width="90" height="90" alt="圣宝先自营复合酵素" src="images/sbx-product.png">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">圣宝先自营复合酵素</a>
                            </div>
                            <div class="p-price"><span>￥</span>5099.<span>00</span></div>
                        </li>
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">
                                    <img width="90" height="90" alt="圣宝先自营复合酵素" src="images/sbx-product.png">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">圣宝先自营复合酵素</a>
                            </div>
                            <div class="p-price"><span>￥</span>5099.<span>00</span></div>
                        </li>
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">
                                    <img width="90" height="90" alt="圣宝先自营复合酵素" src="images/sbx-product.png">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="#" title="圣宝先自营复合酵素">圣宝先自营复合酵素</a>
                            </div>
                            <div class="p-price"><span>￥</span>5099.<span>00</span></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var loading;

    function multi_delete_distribution() {
        layer.confirm('确定删除选中的商品?', {
            btn: ['确定','取消'] //按钮
        }, function(){
            var cid_list = new Array();
            $('.check-product').each(function () {
                if ($(this).is(':checked')) {
                    var cid = $(this).attr('data-cid');
                    cid = parseInt(cid);
                    cid_list.push(cid);
                }
            });
            if (cid_list.length == 0) {
                layer.msg('请选择要删除的商品');
            } else {
                multi_remove_from_distribution(cid_list);
            }
        });
    }

    function multi_remove_from_distribution(cid_list) {
        var url = "distribution.php";
        console.log(cid_list);
        var list = '[';
        for( var id in cid_list ) {
            if( id == 0 ) {
                list += cid_list[id];
            } else {
                list += ',' + cid_list[id];
            }

        }
        list += ']';

        var data = { "opera":"multi_delete", "cid_list":list };
        console.log(data);
        loading = layer.load(0, { shade: 0.3 });

        $.post(url, data, remove_from_distribution_handler, "json");
    }

    function remove_from_distribution_handler(response) {
        layer.close(loading);
        if( response.error == 0 ) {
            window.location.reload();
        } else {
            layer.msg(response.msg);
        }
    }

    //更改复选框状态
    function check_all() {
        var flag = false;
        if( $('#check-all').is(':checked') ) {
            flag = true;
        }
        $("input[type='checkbox']").prop('checked', flag);
        return true;
    }

    function check_product(pid) {
        if( !$('#check-product-'+pid).is(':checked') ) {
            $('#check-all').prop('checked', false);
        } else {
            var flag = true;
            $('.check-product').each(function() {
                if( !$(this).is(':checked') ) {
                    flag = false;
                }
            });
            $('#check-all').prop('checked', flag);
        }

    }

</script>
</body>
</html>