<!-- 底部开始 -->
<div class="footer container">
    <div class="footer-inner">
        <div class="fl">
            <h3>联系我们</h3>
            <span> CONTACT US</span>
            <span>&nbsp;</span>
            <span class="copy">copyright&copy;圣宝先国际商务服务有限公司</span>
        </div>
        <div class="fr">
            <span>圣宝先国际商务服务有限公司</span>
            <span>电话：440-123-4567</span>
            <span>邮箱：sbx@qq.com</span>
            <span>地址：成都市青羊区堂东路66号锦绣工场古玩城55314</span>
        </div>
    </div>
</div>
<!-- 底部结束 -->