<!-- 底部开始 -->
<div class="footer container">
    <div class="footer-inner">
        <div class="fl">
            <h3>联系我们</h3>
            <span> CONTACT US</span>
            <span>&nbsp;</span>
            <span class="copy">copyright&copy;{$config.copyright}</span>
        </div>
        <div class="fr">
            <span>{$config.site_owner}</span>
            <span>电话：{$config.service_phone}</span>
            <span>邮箱：{$config.site_email}</span>
            <span>地址：{$config.address}</span>
        </div>
    </div>
</div>
<!-- 底部结束 -->