{include file="topbar.phtml"}
<div class="header">
    <div class="container">
        <div class="header-logo">
            <a class="logo ir" href="index.php" title="圣宝先官网">圣宝先</a>
        </div>
        <div class="header-search">
            <form action="search.php" method="get">
            <div class="search-form">
                <span class="search-select"><span id="search-mode">{if isset($mode_name)}{$mode_name}{else}宝贝{/if}</span><em class="icon">&#xe603;</em></span>
                <input type="hidden" value="{if isset($mode)}{$mode}{else}product{/if}" name="mode" id="search-mode-val"/>
                <div class="search-select-item">
                    <a id="search-product" href="javascript:select_search_mode('product');">宝贝</a>
                    <a id="search-shop"  href="javascript:select_search_mode('shop');">店铺</a>
                </div>
                <input name="keyword" type="text" class="text" autocomplete="off" placeholder="大家都在搜：圣宝先自营" {if isset($keyword)}value="{$keyword}"{/if}>
                <button class="search-button"><i class="icon">&#xe602;</i></button>
            </div>
            </form>
            <script type="text/javascript">
                function select_search_mode(mode) {
                    if( mode == '' || mode == 'product') {
                        $('#search-mode').text('宝贝');
                    } else {
                        $('#search-mode').text('店铺');
                    }
                    $('#search-mode-val').val(mode);
                }
            </script>
        </div>
        <div class="hotwords">
            <a href="#" name="hotword" target="_blank">圣宝先</a>
            <a href="#" name="hotword" target="_blank">钢笔</a>
            <a href="#" name="hotword" target="_blank">惠氏</a>
            <a href="#" name="hotword" target="_blank">智能爆炸</a>
            <a href="#" name="hotword" target="_blank">冯友兰</a>
        </div>
        <div class="header-qr">
            <span class="h">手机逛微商城</span>
            <img src="{$template_dir}images/qrcode.jpg">
        </div>
    </div>
</div>
{if $aside_hover neq 'shop.php'}
{include file="nav.phtml"}
{/if}