<div class="topbar">
    <div class="container">
        <div class="fl">
            <span><i class="icon">&#xe600;</i>财富热线：<em>440-123-4567</em></span>
        </div>
        <div class="fr">
            <div class="topbar-cart">
                <a href="cart.php" class="cart-mini"><i class="icon">&#xe601;</i>购物车<span class="cart-num">（0）</span></a>
                <div class="cart-menu">
                    <div class="cart-menu-inner">
                        购物车中还没有商品，赶紧选购吧！
                    </div>
                </div>
            </div>
            <div class="topbar-info">
                <a href="#">登陆</a>
                <span class="sep">|</span>
                <a href="#">注册</a>
            </div>
        </div>
    </div>
</div>
<div style="clear: both;"></div>
<div class="header">
    <div class="container">
        <div class="header-logo">
            <a class="logo ir" href="index.php" title="圣宝先官网">圣宝先</a>
        </div>
        <div class="header-search">
            <form action="search.php" method="get">
            <div class="search-form">
                <span class="search-select"><span>宝贝</span><em class="icon">&#xe603;</em></span>
                <div class="search-select-item">
                    <a id="search-product">宝贝</a>
                    <a id="search-shop">店铺</a>
                </div>
                <input name="keyword" type="text" class="text" autocomplete="off" placeholder="大家都在搜：圣宝先自营">
                <button class="search-button"><i class="icon">&#xe602;</i></button>
            </div>
            </form>
        </div>
        <div class="hotwords">
            <a href="#" name="hotword" target="_blank">圣宝先</a>
            <a href="#" name="hotword" target="_blank">钢笔</a>
            <a href="#" name="hotword" target="_blank">惠氏</a>
            <a href="#" name="hotword" target="_blank">智能爆炸</a>
            <a href="#" name="hotword" target="_blank">冯友兰</a>
        </div>
        <div class="header-qr">
            <span class="h">手机逛微商城</span>
            <img src="{$template_dir}images/qrcode.jpg">
        </div>
    </div>
</div>
<div class="nav">
    <div class="container">
        <!-- 侧栏开始 -->
        <div class="categorys">
            <div class="dt">
                <a href="#" target="_blank">全部商品分类<i class="icon">&#xe606;</i></a>
            </div>
            <div class="dd inner">
                <div class="dd-inner">
                    {foreach from=$category_list item=cat name=category_list}
                    <div class="item">
                        <h3>
                            <a class="item-title" target="" href="product_list.php?id={$cat.id}">{$cat.name}</a>
                        </h3>
                        <i class="icon">&#xe604;</i>
                        {if $cat.children}
                        <div class="sub-item clearfix">
                            {foreach from=$cat.children item=c}
                            <a href="product_list.php?id={$c.id}" target="">{$c.name}</a>
                            {/foreach}
                        </div>
                        {/if}
                    </div>
                    {/foreach}
                </div>
            </div>
        </div>
        <!-- 侧栏结束 -->
        <!-- 导航条开始 -->
        <div class="navitems">
            <ul class="navitems-grounp">
                {foreach from=$top_nav item=nav}
                <li>
                    <a href="{$nav.url}" target="_self">{$nav.name}</a>
                </li>
                {/foreach}
            </ul>
        </div>
        <!-- 导航条结束 -->
    </div>
</div>