{include file="topbar.phtml"}
<div class="header">
    <div class="container">
        <div class="header-logo">
            <a class="logo ir" href="index.php" title="圣宝先官网">圣宝先</a>
        </div>
        <div class="header-search">
            <form action="search.php" method="get">
            <div class="search-form">
                <span class="search-select"><span>宝贝</span><em class="icon">&#xe603;</em></span>
                <div class="search-select-item">
                    <a id="search-product">宝贝</a>
                    <a id="search-shop">店铺</a>
                </div>
                <input name="keyword" type="text" class="text" autocomplete="off" placeholder="大家都在搜：圣宝先自营">
                <button class="search-button"><i class="icon">&#xe602;</i></button>
            </div>
            </form>
        </div>
        <div class="hotwords">
            <a href="#" name="hotword" target="_blank">圣宝先</a>
            <a href="#" name="hotword" target="_blank">钢笔</a>
            <a href="#" name="hotword" target="_blank">惠氏</a>
            <a href="#" name="hotword" target="_blank">智能爆炸</a>
            <a href="#" name="hotword" target="_blank">冯友兰</a>
        </div>
        <div class="header-qr">
            <span class="h">手机逛微商城</span>
            <img src="{$template_dir}images/qrcode.jpg">
        </div>
    </div>
</div>
{if $aside_hover neq 'shop.php'}
{include file="nav.phtml"}
{/if}