<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <span>健康管理</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="health container">
    <!--健康管理 开始-->
    <!-- 文章列表开始 -->
    <div class="article-list">
        <div class="tab-area">
            <div class="tab">
                <a href="article_list.php?id=5" {if $sub_section_id_on eq 5}{$index = $temp}class="on"{/if} id="tab{$temp}">全部</a>
                {foreach from=$section_list item=s}
                {$temp = $temp + 1}
                <a href="article_list.php?id={$s.id}" {if $s.id eq $sub_section_id_on}{$index = $temp}class="on"{/if} id="tab{$temp}">{$s.section_name}</a>
                {/foreach}
            </div>
            <div style="clear: both;"></div>
        </div>
        {if $article_list}
        <div class="article-list-inner" id="con1" style="display: block;">
            <ul>
                {foreach from=$article_list item=a}
                <li>
                    <div class="article-list-pic">
                        <a href="article.php?id={$a.id}" title="{$a.title}">
                            <img src="{$a.original|build_url}" alt="{$a.title}"/>
                        </a>
                    </div>
                    <div>
                        <a href="article.php?id={$a.id}" title="{$a.title}">{$a.title}</a>
                    </div>
                    <span>{$a.last_modify}</span>
                    <div class="line"></div>
                </li>
                {/foreach}
            </ul>
        </div>
        <div class="pages fr">
            {if $has_prev eq false}
            <a rel="nofollow" class="prev disabled fl" id="prePage" href="javascript:void();"><i class="sign left">&lt;</i>上一页</a>
            {else}
            <a rel="nofollow" class="prev fl" id="prePage" href="?id={$id}&page={$page-1}"><i class="sign left">&lt;</i>上一页</a>
            {/if}
            <a rel="nofollow" class="fl" id="pageFirst" href="?id={$id}&page=1">首页</a>
            {if $has_many_prev}
            <span class="icon ellipsis fl">&#xe61e;</span>
            {/if}
            {foreach from=$show_page item=pageNum}
            {if $pageNum eq $page}
            <a rel="nofollow" class="fl cur" href="?id={$id}&page={$pageNum}">{$pageNum}</a>
            {else}
            <a rel="nofollow" class="fl" href="?id={$id}&page={$pageNum}">{$pageNum}</a>
            {/if}
            {/foreach}
            {if $has_many_next}
            <span class="icon ellipsis fl">&#xe61e;</span>
            {/if}
            <a rel="nofollow" class="fl" href="?id={$id}&page={$totalPage}" id="pageLast">末页</a>
            {if $has_next eq false}
            <a rel="nofollow" id="nextPage" class="next disabled fl" title="下一页" href="javascript:void();">下一页<i class="sign right">&gt;</i></a>
            {else}
            <a rel="nofollow" id="nextPage" class="next fl" title="下一页" href="?id={$id}&page={$page+1}">下一页<i class="sign right">&gt;</i></a>
            {/if}
            <div class="fl">
                <span class="fl">向第</span>
                <input class="fl" type="text" id="bottomPage">
                <span class="fl">页</span>
                <a rel="nofollow" class="pageGo fl" href="javascript:page_go()" id="pagesubmit">跳转</a>
            </div>
            <script type="text/javascript">
                function page_go() {
                    var page = $('#bottomPage').val();
                    window.location.href="?id={$id}&page=" + page;
                }
            </script>
        </div>
        {else}
        <div class="article-list-inner" id="con1" style="display: block;">
        <ul>
            <li>暂无资讯</li>
        </ul>
        </div>
        {/if}
        <div style="clear: both;"></div>
    </div>
    <!-- 文章列表结束 -->
    <!--健康管理 结束-->
    <div style="clear: both"></div>
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript">
    /* 健康管理tabs切换 */
    $(function(){
        $("#tab1").click(function(){
            $(this).addClass("on");
            $(this).siblings().removeClass("on");
            $(".article-list-inner").hide();
            $("#con1").show();
        });
        $("#tab2").click(function(){
            $(this).addClass("on");
            $(this).siblings().removeClass("on");
            $(".article-list-inner").hide();
            $("#con2").show();
        });
        $("#tab3").click(function(){
            $(this).addClass("on");
            $(this).siblings().removeClass("on");
            $(".article-list-inner").hide();
            $("#con3").show();
        });
        $("#tab4").click(function(){
            $(this).addClass("on");
            $(this).siblings().removeClass("on");
            $(".article-list-inner").hide();
            $("#con4").show();
        });
    })
</script>
</body>
</html>