<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我的足迹</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        {if $product_list}
        <!--右侧我的足迹 开始-->
        <div class="history">
            {foreach from=$product_list item=sub_list key=date}
            <div class="might-like history-inner" id="history-{$date}">
                <div class="inner-head">
                    <h3 class="fl">{$date}</h3>
                    <span class="fr"><a href="javascript:confirm_delete_history('{$date}')"><i class="icon">&#xe61c;</i></a></span>
                    <div style="clear: both;"></div>
                </div>
                <div class="inner-con">
                    <ul class="p-list">
                        {foreach from=$sub_list item=p}
                        <li>
                            <div class="p-img">
                                <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">
                                    <img width="90" height="90" alt="{$p.name}" src="{$p.img|build_url}">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">{$p.name}</a>
                            </div>
                            <div class="p-price"><span>￥</span>{sprintf('%.2f', $p.price)}</div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
            </div>
            {/foreach}
        </div>
        <!--右侧我的足迹 结束-->
        {else}
        <!--右侧我的足迹 开始-->
        <div class="history">
            <div class="tips-empty">
                <div class="tips-icon">
                    <span class="icon">&#xe619;</span>
                </div>
                <div class="tips-detail">
                    对不起，你当前并没有浏览过任何产品！
                </div>
            </div>
        </div>
        <!--右侧我的足迹 结束-->
        {/if}
        {include file="might-like.phtml"}

    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var loading;

    function confirm_delete_history(date) {
        layer.confirm('确定删除当天的浏览记录？', {
            btn: ['确定','取消'] //按钮
        }, function(){
            delete_history(date);
        });
    }

    function delete_history(date) {
        var url = 'history.php';
        var param = { "opera": "delete", "date": date };
        loading = layer.load(0, { shade: 0.3 });
        $.post(url, param, delete_history_handler, 'json');
    }

    function delete_history_handler(response) {
        layer.close(loading);
        if( response.error == 0 ) {
            layer.msg('已删除'+response.date+'的浏览记录');
            $('#history-'+response.date).remove();
            if( $('.history-inner').length == 0 ) {
                var temp = '<div class="tips-empty"> <div class="tips-icon"> <span class="icon">&#xe619;</span> </div> <div class="tips-detail">对不起，你当前并没有浏览过任何产品！ </div> </div>';
                $('.history').append(temp);
            }
        } else {
            layer.msg(response.msg, function() {
                if( response.error == 2 ) {
                    window.location.href = 'login.php';
                }
            });
        }
    }
</script>
</body>
</html>