<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <span>用户中心</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <div class="home-head">
            <div class="user-photo">
                <div class="user-photo-inner">
                    <a href="profile.php?act=avatar">
                        <img src="{if $user_info.headimg neq ""}{$user_info.headimg|build_url}{else}{$template_dir}images/avatar_60x60.jpg{/if}" alt="头像"/>
                        <div class="edit-box">
                            <span class="edit">&nbsp;</span>
                            <span class="edita">编辑头像</span>
                        </div>
                    </a>
                </div>
            </div>
            <div class="user-info">
                <div class="welcome-tips">
                    你好，<span class="username">{if empty($user_info.nickname)}{$user_info.account}{else}{$user_info.nickname}{/if}</span>
                </div>
                <div class="last-login">
                    注册时间：<span class="time">{date('Y/m/d H:i:s', $user_info.add_time)}</span>
                </div>
            </div>
            <div class="account-message">
                <ul>
                    <li>
                        <div class="count-item">
                            <a href="order.php?status=1" target="_parent" title="待付款">
                                <i class="icon">&#xe617;</i>
                                待付款
                                <em>{$order_await_pay}</em>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="count-item">
                            <a href="order.php?status=6" target="_parent" title="待收货">
                                <i class="icon">&#xe615;</i>
                                待收货
                                <em>{$order_await_receive}</em>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="count-item">
                            <a href="order.php?status=7" target="_parent" title="待评价">
                                <i class="icon">&#xe614;</i>
                                待评价
                                <em>{$order_await_comment}</em>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="count-item">
                            <a href="order.php?status=8" target="_parent" title="退换货">
                                <i class="icon">&#xe616;</i>
                                退换货
                                <em>{$order_await_refund}</em>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="account-info">
                <div class="account-info-inner">
                    <div class="inner-item">
                        <label>余额：</label>
                        <a href="#">{sprintf("%.2f", $user_info.balance)}</a>
                    </div>
                    <div class="inner-item">
                        <label>佣金：</label>
                        <a href="#">{sprintf("%.2f", $user_info.reward)}</a>
                    </div>
                    <div class="inner-item">
                        <label>积分：</label>
                        <a href="#">{sprintf("%.2f", $user_info.integral)}</a>
                    </div>
<!--                    <div class="inner-item">-->
<!--                        <label>优惠券：</label>-->
<!--                        <a href="#">0</a>-->
<!--                    </div>-->
                </div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <div class="might-like">
            <div class="might-like-inner">
                <div class="inner-head">
                    <h3 class="fl">根据浏览，猜你喜欢</h3>
                    <span class="fr" id="change-fav"><i class="icon">&#xe618;</i>换一组</span>
                    <div style="clear: both;"></div>
                </div>
                <div class="inner-con">
                    <ul class="p-list" id="fav-list">
                        {foreach from=$fav_products item=product}
                        <li>
                            <div class="p-img">
                                <a href="product.php?id={$product.id}" title="{$product.name}">
                                    <img width="90" height="90" alt="{$product.name}" src="{$product.img|build_url}">
                                </a>
                            </div>
                            <div class="p-name">
                                <a href="product.php?id={$product.id}" title="{$product.name}">{$product.name}</a>
                            </div>
                            <div class="p-price"><span>￥</span><span>{sprintf('%.2f', $product.price)}</span></div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript">
    {literal}
    $(function() {
        $('#change-fav').click(function() {
            var url = 'data_center.php';
            var param = {'opera': 'get_fav'};
            $.post(url, param, do_change_fav_handler, 'json');
        });
    });

    function do_change_fav_handler(response) {
        if( response.error == 0 ) {
            $('#fav-list').empty();
            $('#fav-list').append(response.content);
        }
    }
    {/literal}
</script>
</body>
</html>