<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 轮播开始 -->
<div class="slide container">
    <div class="banner" id="b04">
        <ul>
            {foreach from=$cycle_ad item=ad}
            <li><img src="{$ad.img|build_url}" alt="" width="788" height="328" ></li>
            {/foreach}
        </ul>
        <a href="javascript:void(0);" class="unslider-arrow04 prev"><img class="arrow" id="al" src="{$template_dir}images/arrowl.png" alt="prev" width="20" height="35"></a>
        <a href="javascript:void(0);" class="unslider-arrow04 next"><img class="arrow" id="ar" src="{$template_dir}images/arrowr.png" alt="next" width="20" height="37"></a>
    </div>
</div>
<!-- 轮播结束 -->
<div class="video-con container">
    <div class="fl">
        <!-- 商城公告开始 -->
        <div class="notice">
            <h3 class="ir">商城公告</h3>
            <ul>
                {foreach from=$notice item=n}
                <li>
                    <i class="icon">&#xe605;</i>
                    <!--<em><a href="#" target="_blank">[公告]</a></em>-->
                    <a href="article.php?id={$n.id}" title="{$n.title}">{$n.title}</a>
                    <span class="date">{date('m/d', $n.add_time)}</span>
                </li>
                {/foreach}
            </ul>
        </div>
        <!-- 商城公告结束 -->
        <!-- 品牌logo广告开始 -->
        <div class="AD-brands" style="display: none">
            <ul>
                <li>
                    <a href="#" title="IPhone" target="_blank">
                        <img src="{$template_dir}images/iPhone.png" alt="iphone"/>
                    </a>
                </li>
                <li>
                    <a href="#" title="三星" target="_blank">
                        <img src="{$template_dir}images/sanxing.jpg" alt="三星"/>
                    </a>
                </li>
                <li>
                    <a href="#" title="ThinkPad" target="_blank">
                        <img src="{$template_dir}images/thinkpad.jpg" alt="ThinkPad"/>
                    </a>
                </li>
                <li>
                    <a href="#" title="TP-Link" target="_blank">
                        <img src="{$template_dir}images/tp-link.png" alt="TP-Link"/>
                    </a>
                </li>
            </ul>
        </div>
        <!-- 品牌logo广告结束 -->
    </div>
    <div class="fr">
        <div id="myplayer">
            <!--酷播迷你 CuPlayerMiniV4.0 代码开始-->
            <script type="text/javascript" src="{$template_dir}js/swfobject.js"></script>
            <div id="CuPlayer"><embed type="application/x-shockwave-flash" src="CuPlayer/CuPlayerMiniV4.swf" width="480" height="340" id="ply" name="ply" bgcolor="#000000" quality="high" allowfullscreen="true" allowscriptaccess="always" wmode="opaque" salign="lt" flashvars="CuPlayerFile={$template_dir}images/Video.flv&amp;CuPlayerSetFile=CuPlayer/CuPlayerSetFile.xml&amp;CuPlayerImage=CuPlayer/{$template_dir}images/start.jpg&amp;CuPlayerWidth=480&amp;CuPlayerHeight=340&amp;CuPlayerAutoPlay=yes&amp;CuPlayerPosition=bottom-right"></div>
            <script type="text/javascript">
                <!--
                //酷播迷你：官方连播代码示例//
                var CuPlayerList ="http://www.dehua.net/weizhan/{$template_dir}images/Video.flv"  //视频地址
                var sp =CuPlayerList.split("|")
                var num = sp.length;
                var video_index = 0;
                function getNext(pars)
                {
                    if(video_index < num-1)
                    {
                        video_index++;
                        so.addVariable("CuPlayerFile",sp[video_index]);
                        so.write("CuPlayer");
//alert(video_index);
                    }
                    else
                    {
                        video_index = 0;
                        so.addVariable("CuPlayerFile",sp[video_index]);
                        so.write("CuPlayer");
//alert(video_index);
                    }
                }
                function changeStream(CuPlayerFile){
                    so.addVariable("CuPlayerFile",sp[CuPlayerFile]);
                    so.write("CuPlayer");
                }
                CuPlayerFile =sp[video_index];
                var so = new SWFObject("{$template_dir}CuPlayer/CuPlayerMiniV4.swf","ply","480","340","9","#000000");
                so.addParam("allowfullscreen","true");
                so.addParam("allowscriptaccess","always");
                so.addParam("wmode","opaque");
                so.addParam("quality","high");
                so.addParam("salign","lt");
                so.addVariable("CuPlayerFile",CuPlayerFile);
                so.addVariable("CuPlayerSetFile","{$template_dir}CuPlayer/CuPlayerSetFile.xml"); //播放器配置文件地址
                so.addVariable("CuPlayerImage","{$template_dir}CuPlayer/images/start.jpg");//视频略缩图,本图片文件必须正确
                so.addVariable("CuPlayerWidth","480"); //视频宽度
                so.addVariable("CuPlayerHeight","340"); //视频高度
                so.addVariable("CuPlayerAutoPlay","no"); //是否自动播放
                so.addVariable("CuPlayerPosition","bottom-right"); //Logo显示的位置
                so.write("CuPlayer");
                //-->
            </script>
            <!--酷播迷你 CuPlayerMiniV4.0 代码结束-->
        </div>
        <div><img src="{$template_dir}CuPlayer/images/bottom-bg.jpg" alt="视频底部背景"></div>
    </div>
</div>
<div class="floor container">
    <div class="side">
        <div class="side-inner">
            <a href="{$perform_ad[0].url}" target="_blank" title="{$perform_ad[0].alt}">
                <img src="{$perform_ad[0].img|build_url}" alt="{$perform_ad[0].alt}" />
            </a>
        </div>
    </div>
    <div class="main">
        <div class="main-inner">
            <ul class="p-list">
                {foreach from=$youxuan item=p}
                <li>
                    <div class="p-img">
                        <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">
                            <img width="90" height="90" alt="{$p.name}" src="{$p.img|build_url}">
                        </a>
                    </div>
                    <div class="p-name">
                        <a target="" href="product.php?id={$p.id}" title="{$p.name}">{$p.name|truncate:10:".."}</a>
                    </div>
                    <div class="p-price"><span>￥</span><span>{$p.price}</span></div>
                </li>
                {/foreach}
            </ul>
        </div>
    </div>
</div>
<div class="floor container" style="border-color:#ebebeb;">
    <div class="side">
        <div class="side-inner">
            <a href="{$perform_ad[1].url}" target="_blank" title="{$perform_ad[1].alt}">
                <img src="{$perform_ad[1].img|build_url}" alt="{$perform_ad[1].alt}" />
            </a>
        </div>
    </div>
    <div class="main">
        <div class="main-inner">
            <ul class="p-list">
                {foreach from=$jifen item=p}
                <li>
                    <div class="p-img">
                        <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">
                            <img width="90" height="90" alt="{$p.name}" src="{$p.img|build_url}">
                        </a>
                    </div>
                    <div class="p-name">
                        <a target="" href="product.php?id={$p.id}" title="{$p.name}">{$p.name|truncate:10:".."}</a>
                    </div>
                    <div class="p-price"><span>￥</span><span>{$p.price}</span></div>
                </li>
                {/foreach}
            </ul>
        </div>
    </div>
</div>
<div class="floor container" style="border-color: #d3e5b3;">
    <div class="side">
        <div class="side-inner">
            <a href="{$perform_ad[2].url}" target="_blank" title="{$perform_ad[2].alt}">
                <img src="{$perform_ad[2].img|build_url}" alt="{$perform_ad[2].alt}" />
            </a>
        </div>
    </div>
    <div class="main">
        <div class="main-inner">
            <ul class="p-list">
                {foreach from=$cuxiao item=p}
                <li>
                    <div class="p-img">
                        <a target="_blank" href="product.php?id={$p.id}" title="{$p.name}">
                            <img width="90" height="90" alt="{$p.name}" src="{$p.img|build_url}">
                        </a>
                    </div>
                    <div class="p-name">
                        <a target="" href="product.php?id={$p.id}" title="{$p.name}">{$p.name|truncate:10:".."}</a>
                    </div>
                    <div class="p-price"><span>￥</span><span>{$p.price}</span></div>
                </li>
                {/foreach}
            </ul>
        </div>
    </div>
</div>
{include file="footer.phtml"}

<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/unslider.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(e) {
        var unslider04 = $('#b04').unslider({
                dots: true
            }),
            data04 = unslider04.data('unslider');

        $('.unslider-arrow04').click(function() {
            var fn = this.className.split(' ')[1];
            data04[fn]();
        });
        $(".inner").show();
    });
</script>

</body>
</html>