<div class="might-like">
    <div class="might-like-inner">
        <div class="inner-head">
            <h3 class="fl">根据浏览，猜你喜欢</h3>
            <span class="fr"><i class="icon">&#xe618;</i>换一组</span>
            <div style="clear: both;"></div>
        </div>
        <div class="inner-con">
            <ul class="p-list">
                {foreach from=$fav_products item=p}
                <li>
                    <div class="p-img">
                        <a href="product.php?id={$p.id}" title="{$p.name}">
                            <img width="90" height="90" alt="{$p.name}" src="{$p.img|build_url}">
                        </a>
                    </div>
                    <div class="p-name">
                        <a href="product.php?id={$p.id}" title="{$p.name}">{if mb_strlen($p.name) > 10}{mb_substr($p.name, 0, 10)}...{else}{$p.name}{/if}</a>
                    </div>
                    <div class="p-price"><span>￥</span>{sprintf('%.2f', $p.price)}</div>
                </li>
                {/foreach}
            </ul>
        </div>
    </div>
</div>