<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="topbar.phtml"}
<!-- 注册页面开始 -->
<div class="login container register">
    <div class="aside">
        <div class="pic">
            <a href="#" target="_blank">
                <img src="{$template_dir}images/login-bg.jpg" alt="登陆页面背景图" />
            </a>
        </div>
    </div>
    <form action="" method="POST" id="step-1">
        <div class="main">
            <!--注册头部-->
            <div class="login-head">
                <h3></h3>
            </div>
            <div style="clear: both;"></div>
            <!--用户名-->
            <div class="username">
                <span class="icon">&#xe626;</span>
                <input class="user" readonly="readonly" name="phone" value="{substr($mobile, 0, 3)}***{substr($mobile, -4)}" type="text" autocomplete="off" maxlength="11" title="请输入手机号码" placeholder="手机号码">
            </div>
            <!--密码-->
            <div class="password" id="password_div" style="margin-top: 32px;">
                <span class="icon">&#xe625;</span>
                <input class="pass" name="password" id="password" type="password" title="请输入登陆密码" placeholder="请输入登陆密码" maxlength="20" autocomplete="off">
            </div>
            <p class="tips"></p>
            <!--验证码-->
            <div class="code_wrap" style="display: block;">
                <div class="code">
                    <span class="icon">&#xe627;</span>
                    <input class="codes" id="pic_code" name="verifyCode" type="text" title="请输入验证码" placeholder="验证码" maxlength="4" autocomplete="off">
                </div>
                <a class="code_pic" href="javascript:refresh_code();">
                    <img src="code.php">
                </a>
                <a href="javascript:refresh_code();">换张图</a>
            </div>
            <p class="tips"></p>
            <div style="clear: both;"></div>
            <!--登陆-->
            <p class="btn">
                <input type="button" value="下一步" id="verify_pic_code" data-step="2">
            </p>
        </div>
    </form>
    <form action="" method="POST" id="step-2" style="display: none">
        <div class="main">
            <!--注册头部-->
            <div class="login-head">
                <h3>更改手机号码</h3>
            </div>
            <div style="clear: both;"></div>
            <!--用户名-->
            <div class="username">
                <span class="icon">&#xe626;</span>
                <input class="user" name="mobile" id="mobile" value="" onblur="verify_mobile();" type="text" autocomplete="off" maxlength="11" title="请输入手机号码" placeholder="手机号码">
            </div>
            <p class="tips"></p>
            <!--验证码-->
            <div class="code_wrap" style="display: block;">
                <div class="code">
                    <span class="icon">&#xe628;</span>
                    <input class="codes" id="verify" name="verifyCode" type="text" title="请输入验证码" placeholder="验证码" maxlength="6" autocomplete="off">
                </div>
                <a href="javascript:get_message_code()" class="get-code" id="get-message-code">获取验证码</a>
                <!--<a href="javascript:void(0);" class="get-code" style="background-color: #ddd;">重新获取（60）</a>-->
            </div>
            <p class="tips"></p>
            <div style="clear: both;"></div>
            <!--登陆-->
            <p class="btn">
                <input type="button" value="提&nbsp;交" id="set_mobile">&nbsp;
            </p>
        </div>
    </form>
    <div style="clear: both;"></div>
</div>
<!-- 注册页面结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var loading;

    var interval = null;
    var timer = 0;
    var mobile = '';

    $(function(){

        $('#verify_pic_code').click(function() {
            verify_pic_code();
        });

        $("#set_mobile").click(function(){
            set_mobile();
        });
    });

    function refresh_code() {
        $(".code_pic img").attr("src", "code.php");
    }

    function verify_pic_code() {
        var code = $("#pic_code").val();
        var password = $("#password").val();
        if(code == "") {
            layer.msg("请输入图形验证码");
            return false;
        }

        var url = "mobile.php";
        var data = { "opera":"verify", 'password':password, "code":code };

        show_mask();
        $.post(url, data, verify_pic_code_handler, "json");
    }

    function verify_pic_code_handler(response) {
        hide_mask();
        if(response.error == 0) {
            step(2);
//            get_message_code();
        } else {
            layer.msg(response.msg);
        }
    }

    function set_mobile() {

        if(mobile == "") {
            layer.msg("请输入新手机号码");
            return false;
        } else {
            var code = $("#verify").val();

            if(code == "") {
                layer.msg("请输入验证码");
                return false;
            }
            var ref = document.referrer;
            var url = "mobile.php";
            var data = { "opera":"edit", "mobile":mobile,"code":code,'ref':ref };
            show_mask();
            $.post(url, data, set_mobile_handler, "json");
        }
    }

    function set_mobile_handler(response) {
        hide_mask();
        if(response.error == 0) {
            layer.msg(response.msg, function() {
                if( response.referer ) {
                    window.location.href = response.referer;
                } else {
                    window.location.href = "index.php";
                }
            });
        } else {
            layer.msg(response.msg);

        }
    }

    function get_message_code() {
        if( mobile == '' ) {
            layer.msg('请输入新手机号码');
            return false;
        }
        if(timer == 0) {
            var url = "data_center.php";
            var data = { "opera":"get_message_code", "mobile": mobile };

            show_mask();
            $.post(url, data, get_message_code_handler, "json");
        }
    }

    function get_message_code_handler(response) {
        hide_mask();
        if(response.error == 0) {
            timer = response.timer;
            $("#get-message-code").css('background-color', '#ddd');
            $('#get-message-code').attr('href', 'javascript:void(0)');
            $("#get-message-code").html("<em>重新获取</em><i id='timer'>"+timer+"</i>");
            interval = setInterval(trick, 1000);
            layer.msg("当前没有短信接口,请输入验证码："+response.code);
        } else {
            layer.msg(response.msg);
            if(response.timer != undefined) {
                timer = response.timer;
                $("#get-message-code").css('background-color', '#ddd');
                $('#get-message-code').attr('href', 'javascript:void(0)');
                $("#get-message-code").html("<em>重新获取</em><i id='timer'>"+timer+"</i>");
                interval = setInterval(trick, 1000);
            }
        }
    }

    function verify_mobile() {
        var mobile = $("#mobile").val();

        if(mobile == "") {
            layer.msg("请输入手机号码");
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"verify_mobile", "mobile":mobile };

        show_mask();
        $.post(url, data, verify_mobile_handler, "json");
    }

    function verify_mobile_handler(response) {
        hide_mask();
        if(response.error == 0) {
            mobile = response.mobile;
        } else {
            layer.msg(response.msg);
            mobile = "";
        }
    }

    function trick() {
        if(timer) {
            timer--;
            $("#timer").text(timer);
        } else {
            clearInterval(interval);
            $("#get-message-code").removeAttr('style');
            $('#get-message-code').attr('href', 'javascript:get_message_code();');
            $("#get-message-code").html("获取验证码");
        }
    }

    function step(num) {
        $("#step-"+(num-1)).hide();
        $("#step-"+num).show();
        if(num > 1) {
            num--;
            $(".back").click(function(){
                step(num);
                return false;
            });
        } else {
            $(".back").click(function(){
                return true;
            });
        }
    }


    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });
    }

    function hide_mask() {
        layer.close(loading);
    }
</script>
</body>
</html>