<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <span>{$title}</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 文章列表开始 -->
<div class="article-list container">
    <div class="article-list-inner">
        <h5>{$title}</h5>
        <ul>
            {foreach from=$article_list item=article}
            <li>
                <div>
                    <a href="article.php?id={$article.id}" title="{$article.title}">{$article.title}</a>
                </div>
                <span>{date("Y-m-d H:i:s", $article.add_time)}</span>
                <div class="line"></div>
            </li>
            {/foreach}
        </ul>
        {if count($article_list) gt 20}
        <div class="pages fr">
            <a rel="nofollow" class="prev disabled fl" id="prePage" href="javascript:void(0);"><i class="sign left">&lt;</i>上一页</a>
            <a rel="nofollow" class="cur fl" id="pageFirst" href="#">1</a>
            <a rel="nofollow" class="fl" href="#">2</a>
            <a rel="nofollow" class="fl" href="#">3</a>
            <a rel="nofollow" class="fl" href="#">4</a>
            <span class="searchBg ellipsis fl"></span>
            <a rel="nofollow" class="fl" href="#" id="pageLast">100</a>
            <a rel="nofollow" id="nextPage" class="next fl" title="下一页" href="#">下一页<i class="sign right">&gt;</i></a>
            <div class="fl">
                <span class="fl">向第</span>
                <input class="fl" type="text" id="bottomPage">
                <span class="fl">页</span>
                <a rel="nofollow" class="pageGo fl" href="#" id="pagesubmit">跳转</a>
            </div>
        </div>
        {/if}
        <div style="clear: both;"></div>
    </div>
</div>
<!-- 文章列表结束 -->
{include file="footer.phtml"}

<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>

</body>
</html>