<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="">首页</a><span class="gt">&gt;</span>
    <a href="article_list.php?id={$section.id}" target="">{$section.section_name}</a><span class="gt">&gt;</span>
    <span>{$article.title}</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 文章内容开始 -->
<div class="article container">
    <div class="article-inner">
        <div class="mt">
            <h3>{$article.title}</h3>
            <div class="summary">{date('Y-m-d H:i:s', $article.add_time)}</div>
        </div>
        <div class="mc">
            {$article.content}
        </div>
    </div>
</div>
<!-- 文章内容结束 -->
{include file="footer.phtml"}

<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>

</body>
</html>