<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <span>合伙人入口</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 合伙人入口开始 -->
<div class="partner container">
    <div class="tips-empty">
        <div class="tips-icon">
            <span class="icon">&#xe630;</span>
        </div>
        <div class="operation" style="margin:0;">
            <a href="activity.php?id=4" class="sure" style="margin:20px auto;float: none;">精品专区</a>
            <div style="clear: both;"></div>
        </div>
        <div class="tips-detail">
            点击"<a href="activity.php?id=4" title="前往精品专区">精品专区</a>"，任选专区中一款产品并支付成功，即可成为平台合伙人！
        </div>
    </div>
    <div style="clear: both"></div>
</div>
<!-- 合伙人入口结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
</body>
</html>