<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php">首页</a><span class="gt">&gt;</span>
    <a href="home.php">用户中心</a><span class="gt">&gt;</span>
    <span>支付结果</span>
</div>
<div class="home container">
    <div class="order-detail">
        <div class="order-info">
            <div class="order-title">
                <h3><i class="icon">&#xe61a;</i>{$pay_title}</h3>
            </div>
            <!--产品详情 开始-->
            <div class="order-order">
                <span>订单编号：{$order.order_sn}</span>
                <span>买家留言：{$order.remark}</span>
                <span>支付时间：{$notify_time}</span>
            </div>
            {if $order_detail}
            <div class="order-list">
                <table cellpadding="0" cellspacing="0" class="order-tb">
                    <thead>
                    <tr>
                        <th><div class="ordertime-cont">

                            </div>
                            <div class="order-detail-txt">订单详情</div>
                        </th>
                        <th>总计</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="sep-row"><td colspan="5"></td></tr>
                    <tr class="tr-th">
                        <td colspan="5">
                            <span class="gap"></span>
                            <span class="dealtime" title="{date('Y-m-d H:i:s', $order.add_time)}">{date('Y-m-d H:i:s', $order.add_time)}</span>
                            <input type="hidden" value="{date('Y-m-d H:i:s', $order.add_time)}">
                                     <span class="number">订单号：
                                         <a href="javascript:void(0)">{$order.order_sn}</a>
                                     </span>
                            <div class="tr-operate">

                            </div>
                            <div style="clear: both;"></div>
                        </td>
                    </tr>
                    {foreach from=$order_detail item=product key=i}
                    <tr class="tr-bd">
                        <td>
                            <div class="goods-item p-1073757">
                                <div class="p-img">
                                    <a href="product.php?id={$product.id}">
                                        <img class="" src="{$product.img|build_url}" title="{$product.product_name} {$product.product_attributes}" width="60" height="60">
                                    </a>
                                </div>
                                <div class="p-msg">
                                    <div class="p-name"><a href="product.php?id={$product.id}" class="a-link" title="{$product.product_name} {$product.product_attributes}">{$product.product_name} {$product.product_attributes}</a></div>
                                </div>
                                <div style="clear: both;"></div>
                            </div>
                            <div class="goods-number">
                                x{$product.count}
                            </div>
                            <div style="clear: both;"></div>
                        </td>
                        {if $i eq 0}
                        <td rowspan="{count($order.order_detail)}">
                            <div class="amount">
                                <strong>¥{sprintf("%.2f", $order.amount)}</strong> <br>
                                <!--                                <span class="ftx-13"></span><br>-->
                            </div>
                        </td>
                        {/if}
                    </tr>
                    {/foreach}
                    </tbody>
                </table>
            </div>
            {/if}
            <!-- 产品详情 结束 -->
        </div>
    </div>
</div>
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>

<script type="text/javascript">

</script>
</body>
</html>