<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
{foreach from=$product_list item=product}
<li>
    <div class="p-img">
        <a href="product.php?id={$product.id}" title="{$product.name}">
            <img width="90" height="90" alt="{$product.name}" src="{$product.img}">
        </a>
    </div>
    <div class="p-name">
        <a href="product.php?id={$product.id}" title="{$product.name}">{$product.name}</a>
    </div>
    <div class="p-price"><span>￥</span><span>{sprintf('%.2f', $product.price)}</span></div>
</li>
{/foreach}