<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <!--<a href="product-all.html" target="_blank">常备药物</a><span class="gt">&gt;</span>-->
    <span>{$product.name}</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 产品详情开始 -->
<div class="product-detail container">
    <!-- 产品展示 开始 -->
    <div class="show">
        <div class="pic-info">
            <!-- 商品图片展示 开始 -->
            <div class="pic-show">
                <div id="preview" class="spec-preview"> <span class="jqzoom"><img jqimg="../{$product.img}" src="../{$product.img}" /></span> </div>
                <!--缩图开始-->
                <div class="spec-scroll"> <a class="prev">&lt;</a> <a class="next">&gt;</a>
                    <div class="items">
                        <ul>
                            {foreach from=$product.gallery item=gallery}
                            <li><img alt="{$product.name}" bimg="../{$gallery}" src="../{$gallery}" onmousemove="preview(this);"></li>
                            {/foreach}
                        </ul>
                    </div>
                </div>
                <div style="clear: both;"></div>
                <!--缩图结束-->
            </div>
            <!-- 商品图片展示 结束 -->
            <!-- 商品信息 开始 -->
            <div class="show-info">
                <div class="show-info-inner">
                    <div class="head">
                        <h1>{$product.name}</h1>
                        <!--
                        <span class="subtitle">
                            <span>送厨具五件套 百洁布！</span>
                        </span>
                        -->
                    </div>
                    <div class="sale">
                        <div class="sale-box">
                            <div class="show-info-left">价格</div>
                            <div class="show-info-right">
                                <b class="d_price">
                                    <span>¥<span id="salePriceTag">{$product.price}</span></span>
                                </b>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--商品信息 结束-->
        </div>
    </div>
    <div style="clear: both"></div>
    <!-- 产品展示 结束 -->
</div>
<!-- 产品详情结束 -->
<!-- 底部开始 -->
<div class="footer container">
    <div class="footer-inner">
        <div class="fl">
            <h3>联系我们</h3>
            <span> CONTACT US</span>
            <span>&nbsp;</span>
            <span class="copy">copyright&copy;圣宝先国际商务服务有限公司</span>
        </div>
        <div class="fr">
            <span>圣宝先国际商务服务有限公司</span>
            <span>电话：440-123-4567</span>
            <span>邮箱：sbx@qq.com</span>
            <span>地址：成都市青羊区堂东路66号锦绣工场古玩城55314</span>
        </div>
    </div>
</div>
<!-- 底部结束 -->
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
</body>
</html>