<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="">首页</a><span class="gt">&gt;</span>
    <span>{$category_name}</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 全部产品开始 -->
<div class="product-all container">
    <div class="con">
        <ul class="p-list">
            {foreach from=$product_list item=p}
            <li>
                <div class="p-img">
                    <a href="product.php?id={$p.id}">
                        <img width="160" height="160" alt="{$p.name}" src="../{$p.img}">
                    </a>
                </div>
                <div class="p-name">
                    <a href="product.php?id={$p.id}" title="{$p.name}" target="">
                        {$p.name}
                    </a>
                </div>
                <div class="p-price"><strong>￥{$p.price}</strong></div>
                <div class="extra">
                    <span class="evaluate">
							<a href="product.php?id={$p.id}">已有<span>{$p.comment_count}</span>人评论</a>
                    </span>
                </div>
                <div class="btns">
                    <a class="btn-buy" href="javascript:get_attributes({$p.id});">加入购物车</a>
                    {if empty($p.collection)}
                    <a class="btn-coll" id="btn-coll-{$p.product_sn}" href="javascript:collection('{$p.product_sn}')">收藏</a>
                    {else}
                    <a style="margin-left: 20px" class="btn-coll" id="btn-coll-{$p.product_sn}" href="javascript:collection('{$p.product_sn}')">取消收藏</a>
                    {/if}
                </div>
            </li>
            {/foreach}
        </ul>
        <div style="clear: both;"></div>
        {if $total gt $count}
        <div class="pages fr">
            {if $has_prev eq false}
            <a rel="nofollow" class="prev disabled fl" id="prePage" href="javascript:void();"><i class="sign left">&lt;</i>上一页</a>
            {else}
            <a rel="nofollow" class="prev fl" id="prePage" href="?id={$id}&page={$page-1}"><i class="sign left">&lt;</i>上一页</a>
            {/if}
            <a rel="nofollow" class="fl" id="pageFirst" href="?id={$id}&page=1">首页</a>
            {if $has_many_prev}
            <span class="icon ellipsis fl">&#xe61e;</span>
            {/if}
            {foreach from=$show_page item=pageNum}
            {if $pageNum eq $page}
            <a rel="nofollow" class="fl cur" href="?id={$id}&page={$pageNum}">{$pageNum}</a>
            {else}
            <a rel="nofollow" class="fl" href="?id={$id}&page={$pageNum}">{$pageNum}</a>
            {/if}
            {/foreach}
            <!--            <a rel="nofollow" class="fl" href="#">2</a>-->
            <!--            <a rel="nofollow" class="fl" href="#">3</a>-->
            <!--            <a rel="nofollow" class="fl" href="#">4</a>-->
            {if $has_many_next}
            <span class="icon ellipsis fl">&#xe61e;</span>
            {/if}
            <a rel="nofollow" class="fl" href="?id={$id}&page={$totalPage}" id="pageLast">末页</a>
            {if $has_next eq false}
            <a rel="nofollow" id="nextPage" class="next disabled fl" title="下一页" href="javascript:void();">下一页<i class="sign right">&gt;</i></a>
            {else}
            <a rel="nofollow" id="nextPage" class="next fl" title="下一页" href="?id={$id}&page={$page+1}">下一页<i class="sign right">&gt;</i></a>
            {/if}
            <div class="fl">
                <span class="fl">向第</span>
                <input class="fl" type="text" id="bottomPage">
                <span class="fl">页</span>
                <a rel="nofollow" class="pageGo fl" href="javascript:page_go()" id="pagesubmit">跳转</a>
            </div>
            <script type="text/javascript">
                function page_go() {
                    var page = $('#bottomPage').val();
                    window.location.href="?id={$id}&page=" + page;
                }
            </script>
        </div>
        {/if}
        <div style="clear: both;"></div>
    </div>
</div>
<!-- 全部产品结束 -->
{include file="footer.phtml"}
<style>
    {literal}
    .yourclass {
        width:840px; height:240px; box-shadow: none;
    }
    {/literal}
</style>
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var index;
    var loading;
    function get_attributes(id) {
//        var index = layer.load(0, { shade: false });
        var url = 'product.php';
        var param = { 'opera': 'add_to_cart', 'id': id };
        $.post(url, param, get_attributes_handler, 'json');
    }

    function get_attributes_handler(result) {
        if( result.error == 0 ) {

            if( result.content != '' ) {
                index = layer.open({
                    type: 1,
                    title: false,
                    closeBtn: true,
                    shadeClose: true,
                    area: '500px',
                    skin: 'yourclass',
                    content: result.content
                });
            } else {
                add_to_cart_directly(result.product_sn, result.attributes);
            }
        } else {
            layer.msg(result.msg);
        }
    }

    function add_to_cart_directly(product_sn, attributes) {
        var url = "cart.php";
        var buy_num = 1;
        var data = { "opera":"add_to_cart", "product_sn": product_sn, "number": buy_num, "attributes": attributes };

        loading = layer.load(0, { shade: 0.3 });
        $.post(url, data, add_to_cart_directly_handler, "json");
    }

    function add_to_cart_directly_handler(response) {
        layer.close(loading);
        if(response.error == 0) {
            layer.msg('已加入购物车');
        } else {
            layer.msg(response.msg, function(){
                if(response.error == 2) {
                    window.location.href='login.php';
                }
            });
        }
    }
    //加入购物车 end===============================================

    //收藏 start==============================================================
    function collection(product_sn) {
        var url = "product.php";
        var data = { "opera":"collection", "product_sn":product_sn };

        loading = layer.load(0, { shade: 0.3 });
        $.post(url, data, collection_handler, "json");
    }

    function collection_handler(response) {
        layer.close(loading);
        if(response.error == 0) {
            layer.msg(response.msg);
            if(response.status) {
                $("#btn-coll-"+response.product_sn).text("取消收藏");
                $("#btn-coll-"+response.product_sn).css('margin-left', '20px');
            } else {
                $("#btn-coll-"+response.product_sn).text("收藏");
                $("#btn-coll-"+response.product_sn).removeAttr('style');
            }
        } else {
            layer.msg(response.msg, function(){
                if(response.error == 2) {
                    window.location.href='login.php';
                }
            });
        }
    }
    //收藏 end ========================================================================

    //其他参照文档http://layer.layui.com/?form=local
</script>
</body>
</html>