<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <a href="profile.php" target="_blank">我的资料</a><span class="gt">&gt;</span>
    <span>修改资料</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--新增收货地址 开始-->
        <div class="profile">
            <div class="fl">
                <dl class="form-item">
                    <dt>会员卡号：</dt>
                    <dd>
                        <span class="no-input">{$user_info.account}</span>
                    </dd>
                    <div style="clear: both;"></div>
                <dl class="form-item">
                    <dt>会员等级：</dt>
                    <dd>
                        <span class="no-input">{$level[{$user_info.level_id}]}</span>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                    <dl class="form-item">
                        <dt>昵称：</dt>
                        <dd>
                            <span class="no-input">{$user_info.nickname}</span>
                        </dd>
                        <div style="clear: both;"></div>
                    </dl>
                <dl class="form-item">
                    <dt>登陆密码：</dt>
                    <dd>
                        <span class="no-input"><a href="password.php">更改密码</a></span>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <dl class="form-item">
                    <dt>手机号码：</dt>
                    <dd>
                        <input type="text" name="mobile" id="mobile" placeholder="手机号码" class="fl" maxlength="11" value="{$user_info.mobile}" onblur="verify_mobile();"/>
                        <p></p>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <dl class="form-item">
                    <dt>性别：</dt>
                    <dd>
                        <div class="gender">
                            <label class="sex-label">
                                <input type="radio" name="sex" value="M" {if $user_info.sex eq 'M'}checked="checked"{/if}>
                                <span>男</span>
                            </label>
                            <label class="sex-label">
                                <input type="radio" name="sex" value="F" {if $user_info.sex eq 'F'}checked="checked"{/if}>
                                <span>女</span>
                            </label>
                            <label class="sex-label">
                                <input type="radio" name="sex" value="N" {if $user_info.sex eq 'N'}checked="checked"{/if}>
                                <span>保密</span>
                            </label>
                        </div>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <dl class="form-item">
                    <dt>邮箱：</dt>
                    <dd>
                        <input type="text" name="email" id="email" placeholder="请输入邮箱" class="fl" value="{$user_info.email}"/>
                        <p></p>
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <div class="operation">
                    <a href="javascript:edit_profile();" class="sure">保存</a>
<!--                    <a href="javascript:void(0);" class="cancel">取消</a>-->
                    <div style="clear: both;"></div>
                </div>
            </div>
            <div class="fl">
                <div class="profile-avatar">
                    <img src="{$template_dir}images/avatar_60x60.jpg" height="120" width="120">
                    <a href="javascript:;" name="person_index_info_head01">编辑头像</a>
                    <div class="edit_bg"></div>
                </div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <!--新增收货地址 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>

<script type="text/javascript">
    var mobile = "{$user_info.mobile}";
    var loading;

    function verify_mobile() {
        var mobile = $("#mobile").val();

        if(mobile == "") {
            layer.msg("请输入手机号码");
            return false;
        }

        var url = "data_center.php";
        var data = { "opera":"verify_mobile", "mobile":mobile, "mode":"unique" };

        show_mask();
        $.post(url, data, verify_mobile_handler, "json");
    }

    function verify_mobile_handler(response) {
        hide_mask();
        if(response.error == 0) {
//            $("#mobile-show").text(response.mobile_mask);
            mobile = response.mobile;
        } else {
            layer.msg(response.msg);
            mobile = "";
        }
    }

    function edit_profile() {
        var sex = '';
        $("input[name=sex]").each(function() {
            if( $(this).is(':checked') ) {
                sex = $(this).val();
            }
        });
        var email = $("#email").val();

        var msg = "";

        if(mobile == "") {
            msg += "-请填写有效的手机号码<br/>";
        }

        if(sex == "") {
            msg += "-请选择性别<br/>";
        }

        if(email == "") {
            msg += "-请填写邮箱<br/>";
        }

        if(msg != "") {
            layer.msg(msg);
        } else {
            var url = "profile.php";
            var data = { "opera":"edit", "email":email, "sex":sex, "mobile":mobile };
            console.log(data);
            show_mask();
            $.post(url, data, edit_profile_handler, "json");
        }
    }

    function edit_profile_handler(response) {
        hide_mask();
        layer.msg(response.msg);
        if(response.error == 0) {

        }
    }

    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });
    }

    function hide_mask() {
        layer.close(loading);
    }

</script>

</body>
</html>