<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我的推广</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--我的推广 开始-->
        <!-- 文章列表开始 -->
        <div class="article-list">
            {if $article_list}
            <div class="article-list-inner article-all">
                <h5>{$section.section_name}</h5>
                <ul>
                    {foreach from=$article_list item=article key=id}
                    {if $id eq $page_count}
                    {break}
                    {/if}
                    <li>
                        <div class="article-list-pic">
                            <a href="article.php?id={$article.id}" title="{$article.title}">
                                <img src="{$article.original|build_url}" alt="{$article.title}"/>
                            </a>
                        </div>
                        <div>
                            <em class="istop">{if $article.order_view eq 0}[置顶]{/if}</em>
                            <a href="article.php?id={$article.id}" title="{$article.title}">{$article.title}</a>
                        </div>
                        <span>{$article.last_modify}</span>
                        <div class="line"></div>
                    </li>
                    {/foreach}
                </ul>
            </div>
            <div class="pages fr">
                <a rel="nofollow" class="prev disabled fl" id="prePage" href="javascript:void(0);"><i class="sign left">&lt;</i>上一页</a>
                {for $index=1 to $total_page-1}
                <a rel="nofollow" class="{if $index eq 1}cur{/if} fl" href="javascript:get_promotion({$index});">{$index}</a>
                {if $index eq 5}
                {break}
                {/if}
                {/for}
                {if $total_page gt 6}
                <span class="icon ellipsis fl">&#xe61e;</span>
                {/if}
                <a rel="nofollow" class="fl {if $total_page eq 1}cur{/if}" href="javascript:{if $total_page eq 1}void(0);{else}get_promotion({$total_page}){/if}" id="pageLast">{$total_page}</a>
                <a rel="nofollow" class="prev {if $total_page eq 1}disabled{/if} fl" id="nextPage" href="javascript:{if $total_page eq 1}void(0);{else}get_promotion(2){/if}">下一页<i class="sign right">&gt;</i></a>
                <div class="fl">
                    <span class="fl">向第</span>
                    <input class="fl" type="text" id="bottomPage">
                    <span class="fl">页</span>
                    <a rel="nofollow" class="pageGo fl" href="javascript:get_promotion_by_input()" id="bad-pagesubmit">跳转</a>
                </div>
            </div>
            {else}
            <div class="article-list-inner article-all">
                <h5>{$section.section_name}</h5>
            </div>
            {/if}
            <div style="clear: both;"></div>
        </div>
        <!-- 文章列表结束 -->
        <!--我的推广 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var loading;
    function get_promotion(page) {
        var url = 'promotion.php';
        var param = { "opera":'paging', 'page':page };
        loading = layer.load(0, { shade: 0.3 });

        $.post(url, param, get_promotion_handler, 'json');
    }

    function get_promotion_handler(response) {
        layer.close(loading);
        if( response.error == 0 ) {
            $('div.article-all').remove();
            $('div.pages').remove();
            $('div.article-list').append(response.content);
        }
    }
</script>
</body>
</html>