<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>收益排行榜</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--排行榜 开始-->
        <div class="ranking">
            <div class="myteam-header">
                <div class="myteam-header-info">
                    <img src="{if $member.headimg neq ""}{$member.headimg|build_url}{else}{$template_dir}images/wang.jpg{/if}"  alt="{$user.account}" />
                    <span>{$user.account}</span>
                    <em>{$level[$user.level_id]}</em>
                </div>
            </div>
            <div class="ranking-con">
                <ul>
                    {foreach from=$member_list item=member key=id}
                    <li>
                        <div class="ranking-list">
                            <img src="{if $member.headimg neq ""}{$member.headimg|build_url}{else}{$template_dir}images/wang.jpg{/if}" alt="{$member.account}" />
                            <div class="ranking-detail">
                                <span>{$member.account}</span>
                                <span>收益<em>￥{sprintf('%.2f', $member.reward + $member.reward_await)}</em></span>
                            </div>
                            <i class="ranking-num {if $id lt 3}r123{/if}">{$id+1}</i>
                        </div>
                        <div style="clear: both;"></div>
                    </li>
                    {/foreach}
                    <!-- 收益排行列出前10即可 -->
                </ul>
            </div>
        </div>
        <!--排行榜 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
</body>
</html>