<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我要充值</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <div class="recharge">
            <div class="recharge-con">
                <div class="recharge-tips">
                    <i class="icon"></i>充值金额将充入到余额款项中，余额可用于购物，加盟等费用抵用，充值的款项将无法退回。
                </div>
                <div class="recharge-info">
                    <h3><i class="icon" style="margin-right: 4px;"></i>充值到平台</h3>
                    <label><span>所属银行：</span>中国工商银行</label>
                    <label><span>平台账号：</span>44444*******5555</label>
                    <label><span>账户名称：</span>圣宝先</label>
                </div>
                <dl class="form-item recharge-value">
                    <dt><em>*</em>充值金额：</dt>
                    <dd>
                        <input type="text" placeholder="请填写金额（元）" class="fl" maxlength="11">
                    </dd>
                    <div style="clear: both;"></div>
                </dl>
                <div class="operation">
                    <a href="javascript:;" class="sure">确认</a>
                    <div style="clear: both;"></div>
                </div>
            </div>
        </div>
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>

<script type="text/javascript">

</script>

</body>
</html>