<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="?keyword={$keyword}&filter={$filter}&mode={$mode}" >全部结果</a><span class="gt">&gt;</span>
    <span>{$keyword}</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 产品搜索结果开始 -->
<div class="search-product product-all container">
    <div class="con">
        <div class="filter">
            <div class="f-line top">
                <div class="f-sort"><a href="?keyword={$keyword}&filter=star&mode={$mode}" class="curr">店铺评价</a><!--a href="javascript:;">离我最近</a--></div>
                <div class="f-pager">
                    <span class="fp-text"><b>{$page}</b><em>/</em><i>{if $totalPage eq 0}1{else}{$totalPage}{/if}</i></span>
                    <a class="fp-prev {if $has_prev eq false}disabled{/if}" href="{if $has_prev eq false}javascript:;{else}?keyword={$keyword}&mode={$mode}&page={$page-1}&filter={$filter}{/if}">&lt;</a>
                    <a class="fp-next {if $has_next eq false}disabled{/if}" href="{if $has_next eq false}javascript:;{else}?keyword={$keyword}&mode={$mode}&page={$page+1}&filter={$filter}{/if}">&gt;</a>
                </div>
                <div class="f-result-sum">共<span class="num">{$total}</span>家店铺</div>
                <span class="clr"></span>
            </div>
        </div>
        {if $total}
        <!-- search result -->
        <div class="search-shop">
            <ul>
                {foreach from=$shop_list item=shop}
                <li class="search-shop-li">
                    <div class="search-shop-info">
                        <img src="{$shop.logo|build_url}" alt="{$shop.shop_name}"/>
                        <span class="search-shop-detail">
                            <span class="search-shop-name">{$shop.shop_name}</span>
                            <span class="search-shop-comment">店铺评价<em>{sprintf("%.1f", $shop.comment)}分</em></span>
                        </span>
                        <a href="shop.php?id={$shop.id}" class="search-to-shop">进店逛逛</a>
                        <div style="clear: both;"></div>
                        <ul class="search-shop-product">
                            {foreach from=$shop.product_list item=product}
                            <li>
                                <a href="product.php?id={$product.id}" title="{$product.name}">
                                    <img src="{$product.img|build_url}" alt="{$product.name}"/>
                                    <span class="shop-product-price">￥{$product.price}</span>
                                </a>
                            </li>
                            {/foreach}
                            <div style="clear: both;"></div>
                        </ul>
                    </div>
                    <div style="clear: both;"></div>
                </li>
                {/foreach}
            </ul>
        </div>
        <div style="clear: both;"></div>
        <div class="pages fr">
            {if $has_prev eq false}
            <a rel="nofollow" class="prev disabled fl" id="prePage" href="javascript:void();"><i class="sign left">&lt;</i>上一页</a>
            {else}
            <a rel="nofollow" class="prev fl" id="prePage" href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page={$page-1}"><i class="sign left">&lt;</i>上一页</a>
            {/if}
            <a rel="nofollow" class="fl" id="pageFirst" href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page=1">首页</a>
            {if $has_many_prev}
            <span class="icon ellipsis fl">&#xe61e;</span>
            {/if}
            {foreach from=$show_page item=pageNum}
            {if $pageNum eq $page}
            <a rel="nofollow" class="fl cur" href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page={$pageNum}">{$pageNum}</a>
            {else}
            <a rel="nofollow" class="fl" href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page={$pageNum}">{$pageNum}</a>
            {/if}
            {/foreach}
            <!--            <a rel="nofollow" class="fl" href="#">2</a>-->
            <!--            <a rel="nofollow" class="fl" href="#">3</a>-->
            <!--            <a rel="nofollow" class="fl" href="#">4</a>-->
            {if $has_many_next}
            <span class="icon ellipsis fl">&#xe61e;</span>
            {/if}
            <a rel="nofollow" class="fl" href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page={$totalPage}" id="pageLast">末页</a>
            {if $has_next eq false}
            <a rel="nofollow" id="nextPage" class="next disabled fl" title="下一页" href="javascript:void();">下一页<i class="sign right">&gt;</i></a>
            {else}
            <a rel="nofollow" id="nextPage" class="next fl" title="下一页" href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page={$page+1}">下一页<i class="sign right">&gt;</i></a>
            {/if}
            <div class="fl">
                <span class="fl">向第</span>
                <input class="fl" type="text" id="bottomPage">
                <span class="fl">页</span>
                <a rel="nofollow" class="pageGo fl" href="javascript:page_go()" id="pagesubmit">跳转</a>
            </div>
            <script type="text/javascript">
                function page_go() {
                    var page = $('#bottomPage').val();
                    window.location.href="?keyword={$keyword}&filter={$filter}&mode={$mode}&page=" + page;
                }
            </script>
        </div>
        {else}
        <div class="tips-empty">
            <div class="tips-icon">
                <span class="icon">&#xe61d;</span>
            </div>
            <div class="tips-detail">
                对不起，找不到相应的店铺！
            </div>
        </div>
        {/if}
        <div style="clear: both;"></div>
    </div>
</div>
<!-- 产品搜索结果结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>

</body>
</html>