<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我的团队</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--右侧我的团队 开始-->
        <div class="myteam">
            <div class="myteam-header">
                <div class="myteam-header-info">
                    <img src="{$user.headimg}"  alt="{$user.account}" />
                    <span>{$user.account}</span>
                    <em>{$level[$user.level_id]}</em>
                    <ul class="team-overview">
                        <li>一级分销团队（<i>{count($first_member_list)}</i>）</li>
                        <li>二级分销团队（<i>{count($second_member_list)}</i>）</li>
                    </ul>
                </div>
            </div>
            <div class="myteam-list">
                <a class="arrow_con title">
                    <div class="arrow_d">一级分销团队<i class="icon icon-d">&#xe607;</i><i class="icon icon-u">&#xe608;</i><b>{count($first_member_list)}</b></div>
                </a>
                <ul style="display: none;">
                    {foreach from=$first_member_list item=member}
                    <li>
                    <span class="head-pic">
                        <img src="{$member.headimg}" alt="{$member.account}">
                    </span>
                        <span class="user-name">{$member.account}</span>
                        <span class="follow-time">注册时间：{date('Y-m-d H:i:s', $member.add_time)}</span>
                    </li>
                    {/foreach}
                </ul>
            </div>
            <div class="myteam-list">
                <a class="arrow_con title">
                    <div class="arrow_d">二级分销团队<i class="icon icon-d">&#xe607;</i><i class="icon icon-u">&#xe608;</i><b>{count($second_member_list)}</b></div>
                </a>
                <ul style="display: none;">
                    {foreach from=$second_member_list item=member}
                    <li>
                    <span class="head-pic">
                        <img src="{$member.headimg}" alt="{$member.account}">
                    </span>
                        <span class="user-name">{$member.account}</span>
                        <span class="follow-time">注册时间：{date('Y-m-d H:i:s', $member.add_time)}</span>
                    </li>
                    {/foreach}
                </ul>
            </div>
        </div>
        <!--右侧我的团队 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript">
    $(function() {
        $(".myteam-list .arrow_con").click(function(){
            if($(this).find(".arrow_d").hasClass("up")){
                $(this).siblings().slideUp();
                $(this).find(".arrow_d").removeClass("up");
                $(this).find(".icon-d").show();
                $(this).find(".icon-u").hide();
            }else{
                $(this).siblings().slideDown();
                $(this).find(".arrow_d").addClass("up");
                $(this).find(".icon-d").hide();
                $(this).find(".icon-u").show();
            }
        })
    });
</script>
</body>
</html>