<div class="topbar">
    <div class="container">
        <div class="fl">
            <span><i class="icon">&#xe600;</i>财富热线：<em>440-123-4567</em></span>
        </div>
        <div class="fr">
            <div class="topbar-cart">
                <a href="cart.php" class="cart-mini"><i class="icon">&#xe601;</i>购物车<span class="cart-num">（{if $is_login}{$cart_count}{else}0{/if}）</span></a>
                <div class="cart-menu">
                    {if $is_login && $cart_count gt 0}
                    <ul class="cart-list" {if count($mini_cart_list) gt 5}style="height: 450px;overflow: scroll;position:relative;"{/if}>
                    {foreach from=$mini_cart_list item=cart}
                    <li>
                        <div class="cart-item first">
                            <a class="thumb" href="product.php?id={$cart.id}">
                                <img alt="" src="{$cart.img}">
                            </a>
                            <a class="name" href="product.php?id={$cart.id}">{$cart.name} {foreach from=$cart.attributes_str item=attr}{$attr}&nbsp;{/foreach}</a>
                            <span class="price">{sprintf('%.2f', $cart.price)}元 × {$cart.number}</span>
                            <a class="btn-del" href="javascript: void(0);"><i class="icon">&#xe61c;</i></a>
                            <div style="clear: both;"></div>
                        </div>
                    </li>
                    {/foreach}
                    </ul>
                    <div style="clear: both;"></div>
                    <div class="cart-total">
                        <span class="total">共 <em>{$cart_count}</em> 件商品<span class="price"><em>{sprintf('%.2f', $cart_price_amount)}</em>元</span></span>
                        <a href="cart.php" class="btn-cart">去购物车结算</a>
                        <div style="clear: both;"></div>
                    </div>
                    {else}
                    <div class="cart-menu-inner">
                        购物车中还没有商品，赶紧选购吧！
                    </div>
                    {/if}
                </div>
            </div>
            <div class="topbar-info">
                {if $is_login}
                <a href="home.php">用户中心({$account})</a>
                <span class="sep">|</span>
                <a href="logout.php">注销</a>
                {else}
                <a href="login.php">登陆</a>
                <span class="sep">|</span>
                <a href="register.php">注册</a>
                {/if}
            </div>
        </div>
    </div>
</div>
<div style="clear: both;"></div>