<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <a href="order.php" target="_blank">我的订单</a><span class="gt">&gt;</span>
    <span>物流详情</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--物流详情 开始-->
        <div class="track">
            <div class="order-track border_bottom">
                <div class="order-track-l">
                    <img src="{$product_img|build_url}" alt="产品图"/>
                </div>
                <div class="order-track-r">
                    <span class="track-status">物流状态：<em>{if $express_flow.status eq 200}{$express_state[{$express_flow.state}]}{else}暂无信息{/if}</em></span>
                    <span>承运公司：{$express_info.name}</span>
                    <span>运单编号：{$order.express_sn}</span>
                </div>
                <div style="clear: both"></div>
            </div>
            <div class="track-detail">
                {if $express_flow.status eq 200}
                <div class="track-detail-con">
                    <i class="icon">&#xe62c;</i>
                    <ul>
                        {foreach from=$express_flow.data item=data name=express_flow}
                        <li {if $smarty.foreach.express_flow.first}class="selected"{/if}>
                            <span class="icon">&#xe62b;</span>
                            <span>{$data.context}</span>
                            <p>{$data.time}</p>
                        </li>
                        {/foreach}
                    </ul>
                </div>
                {else}
                <div class="track-detail-con">
                    <i class="icon">&#xe62c;</i>
                    <ul>
                        <li class="selected">
                            <span class="icon">&#xe62b;</span>
                            <span>物流单暂无结果</span>
                            <p>{date('Y-m-d H:i:s')}</p>
                        </li>
                    </ul>
                </div>
                {/if}
            </div>
        </div>
        <!--物流详情 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="{$template_dir}js/jquery.jqzoom.js" type="text/javascript"></script>
<script src="{$template_dir}js/jqzoom-base.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
</body>
</html>