<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>圣宝先官方商城</title>
    <meta name="keywords" content=" " />
    <meta name="description" content=" " />
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="shortcut icon" href="{$template_dir}images/favicon.ico" type="image/x-icon">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css" />
    <link href="{$template_dir}css/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
{include file="header.phtml"}
<!-- 顶部面包屑导航开始 -->
<div class="breadcrumb container">
    <span>当前位置：</span>
    <a href="index.php" target="_blank">首页</a><span class="gt">&gt;</span>
    <a href="home.php" target="_blank">用户中心</a><span class="gt">&gt;</span>
    <span>我要提现</span>
</div>
<!-- 顶部面包屑导航结束 -->
<!-- 个人中心开始 -->
<div class="home container">
    <div class="main">
        <!--我要提现 开始-->
        <div class="withdrawals">
            <dl class="form-item">
                <dt>可以提现金额：</dt>
                <dd>
                    <span class="no-input price">￥{sprintf("%.2f", $withdraw_await)}</span>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>提现金额：</dt>
                <dd>
                    <input type="text" id="amount" name="amount" placeholder="请输入金额" class="fl" maxlength="11" value=""/>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>手续费：</dt>
                <dd>
                    <span class="no-input price" id="fee">￥0.00</span>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>选择银行卡：</dt>
                <dd>
                    <div class="select-bank">
                        <input type="hidden" name="bank_id" value="{$bank_list.0.id}" id="bank_id"/>
                        <ul>
                            {foreach from=$bank_list item=bank name=bank_list}
                            <li data-id="{$bank.id}" class="bank-card {if $smarty.foreach.bank_list.first}hover{/if}">
                                <ins class="icon">&#xe624;</ins>
                                {$bank.bank}（{$bank.show_name}）借记卡
                            </li>
                            {/foreach}
                            <div style="clear: both;"></div>
                        </ul>
                        <div class="new-bank">
                            <a href="bank.php?act=add" title="添加银行卡">
                                <i class="icon">&#xe60d;</i>添加银行卡
                            </a>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <dl class="form-item">
                <dt><em>*</em>账户密码：</dt>
                <dd>
                    <input type="password" name="password" id="password" placeholder="请输入账户密码" class="fl" maxlength="">
                </dd>
                <div style="clear: both;"></div>
            </dl>
            <div class="operation">
                <a href="javascript:void(0);" id="submit_withdraw_btn" class="sure">提交</a>
                <div style="clear: both;"></div>
            </div>
        </div>
        <!--我要提现 结束-->
    </div>
    {include file="aside.phtml"}
</div>
<!-- 个人中心结束 -->
{include file="footer.phtml"}
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{$template_dir}js/sbx-pc.js"></script>
<script type="text/javascript" src="{$template_dir}js/layer/layer.js"></script>
<script type="text/javascript">
    var withdraw_await = {$withdraw_await};
    var fee_rate = {$config.fee_rate};
    var withdraw_min = {$config.withdraw_min};
    var loading;

    function select_bank_card(id) {
        $("").removeClass("current");

        $("#bank_"+id).addClass("current");
    }

    function submit_withdraw() {
//        console.log(check_amount());
        if(check_amount()) {
            var amount = $("#amount").val();
            var bank_id = $("#bank_id").val();
            var password = $("#password").val();
            var msg = "";

            amount = parseFloat(amount);
            bank_id = parseInt(bank_id);

            if(isNaN(amount) || amount <= 0) {
                amount = 0;
                $("#amount").val(amount.toFixed(2));
                $("#fee").text("￥0.00");
                msg += "-请填写要提现的金额<br/>";
            }

            if(isNaN(bank_id) || bank_id <= 0) {
                msg += "-请选择银行卡<br/>";
            }

            if(password == "") {
                msg += "-请填写账户密码<br/>";
            }

            if(msg == "") {
                var url = "withdraw.php";
                var data = { "opera":"add", "bank_id":bank_id, "password":password, "amount":amount };

                show_mask();
                $.post(url, data, submit_withdraw_handler, "json");
            } else {
                layer.msg(msg);
            }
        }
    }

    function submit_withdraw_handler(response) {
        hide_mask();
        if(response.error == 0) {
            layer.msg(response.msg, function() {
                window.location.reload();
            });
        } else {
            layer.msg(response.msg);
        }
    }

    function check_amount() {
        var amount = $("#amount").val();
        amount = parseFloat(amount);
        if(isNaN(amount) || amount < 0) {
            amount = 0;
            $("#amount").val(amount.toFixed(2));
            $("#fee").text("￥0.00");
            layer.msg("最小提现金额为:"+withdraw_min);
            return false;
        }

        if(amount < withdraw_min) {
            layer.msg("最小提现金额为:"+withdraw_min);
            return false;
        }

        var fee = fee_rate * amount;

        var total_amount = fee + amount;

        if(total_amount > withdraw_await) {
            layer.msg("可提现额不足");
            disable_btn("submit_withdraw_btn");
            $("#fee").text("￥" + fee.toFixed(2));
            return false;
        } else {
            enable_btn("submit_withdraw_btn");
        }

        $("#fee").text("￥" + fee.toFixed(2));
        return true;
    }

    function show_mask() {
        loading = layer.load(0, { shade: 0.3 });
    }

    function hide_mask() {
        layer.close(loading);
    }

    function enable_btn(id) {
        $("#"+id).removeClass("btn-disabled");
    }

    function disable_btn(id) {
        $("#"+id).addClass("btn-disabled");
    }


    $(function(){
        $("#amount").blur(function() { check_amount(); });

        $("#submit_withdraw_btn").click(function() { submit_withdraw(); });

        $('.bank-card').on('click', function() {
            $('#bank_id').val(($(this).attr('data-id')));
        });


        {if !$bank_list}
            layer.msg("请先添加银行卡", function() {
                window.location.href = "bank.php?act=add";

            });
        {/if}

        {if $no_privicy}
            layer.msg("请先升级为合伙人", function() {
                window.location.href = "javascript:void(0)";

            });
        {/if}
    });
</script>
</body>
</html>