{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">添加产品分类</h5>
        <!--        <div class="pull-right"><a class="btn btn-primary" href="?act=passwd">修改密码</a></div>-->
        <div class="clear"></div>
    </div>
    <div class="basicInfo-main">
        <form id="categoryAddForm" method="post" action="">
            <fieldset>
                <p>
                    <label class="l-title">分类名：</label>
                    <input class="text-input w300" type="text" maxlength="64" id="category_name" name="category_name" value="" placeholder="请输入分类名"/>
                </p>
                <p>
                    <label class="l-title">父级分类：</label>
                    <select name="parent_id" class="w150">
                        <option value="0">顶级分类</option>
                        {foreach from=$category_list item=category}
                        <option value="{$category.id}">{$category.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">价格区间：</label>
                    <input class="text-input w300" type="text" maxlength="64" id="price_filter" name="price_filter" value="3" placeholder=""/>
                </p>
                <p>
                    <label class="l-title">图标：</label>
                    <input type="radio" name="icon" value="e607" checked="checked"/><em class="icon">&#xe607;</em>&nbsp;
                    <input type="radio" name="icon" value="e601" /><em class="icon">&#xe601;</em>&nbsp;
                    <input type="radio" name="icon" value="e602" /><em class="icon">&#xe602;</em>&nbsp;
                    <input type="radio" name="icon" value="e603" /><em class="icon">&#xe603;</em>&nbsp;
                </p>
                <p>
                    <label class="l-title">按品牌检索：</label>
                    <input class="" type="radio" name="search_brand" value="1" checked="checked"/><em>是</em>&nbsp;
                    <input class="" type="radio" name="search_brand" value="0"/><em>否</em>&nbsp;
                </p>
                <p>
                    <label class="l-title"></label>
                    <button class="btn btn-primary" type="submit">保存</button>
                    <input type="hidden" name="opera" value="add" />
                </p>

            </fieldset>
        </form>
    </div>
</div>
<!-- END content -->
<script type="text/javascript">
    $(function () {
        menu1("#ud2", "#ud2 a", ".coin_3 a.nav-top-item");
    })
</script>
{include file="library/footer.lbi"}
</body>
</html>