<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>收货地址列表</em></h1>
</header>
<!-- 收货地址列表 -->
<section id="address-list">
    <div class="address-list">
        <div class="address_item">
            <div class="detail">
                <p class="a-name">收货人：隔壁老王<span class="a-phone">13662366666</span></p>
                <p class="a-address">收货地址：广州市海珠区仑头路21号</p>
                <div class="clear tags">
                    <span>默认地址</span>
                    <a class="garbage"></a>
                </div>
            </div>
            <div class="bottom_line"></div>
        </div>
        <div class="address_item">
            <div class="detail">
                <p class="a-name">收货人：隔壁老王<span class="a-phone">13662366666</span></p>
                <p class="a-address">收货地址：广州市海珠区仑头路21号这个地址要长点试试效果</p>
                <div class="clear tags">
                    <a class="garbage"></a>
                </div>
            </div>
            <div class="bottom_line"></div>
        </div>
        <div class="address_item">
            <div class="detail">
                <p class="a-name">收货人：隔壁老王<span class="a-phone">13662366666</span></p>
                <p class="a-address">收货地址：广州市海珠区仑头路21号</p>
                <div class="clear tags">
                    <a class="garbage"></a>
                </div>
            </div>
            <div class="bottom_line"></div>
        </div>
    </div>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
