<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>绑定手机号码</em></h1>
</header>
<!-- 绑定手机 -->
<section class="binding-con">
    <div class="binding-phone">
        <span class="ico"></span>
        <span class="input"><input type="tel" id="mobile" placeholder="请输入你的手机号"></span>
    </div>
    <div class="verify-phone">
        <span class="input"><input type="text" id="verify" placeholder="请输入验证码"></span>
    </div>
    <button id="reget" class="new" type="button" on="获取验证码" off="重新获取" time="60"><em>获取验证码</em><i style="display: none;">60</i></button>
    <div class="binding-tips">
        <i class="icon" style="color: #FF8948">&#xe60c;</i>&nbsp;绑定手机号码需短信确认，验证号码已发送成功！
    </div>
    <a class="btn" href="#" onclick="return false;">完成</a>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    $("#reget").click(function(){
        $(this).removeClass("new");
        $(this).find("em").html("重新获取");
        $(this).find("i").show();
    })
</script>
</body>
</html>
