<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>发表评价</em></h1>
</header>
<!-- 发表评价页面 -->
<section class="product-comment">
    <section class="comment-con">
        <div class="comment-header">
            <img src="{$template_dir}images/sbx-product.png" alt="产品图" />
            <dl class="comment-star">
                <dt>评分</dt>
                <dd class="i-star">
                    <i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i>
                </dd>
            </dl>
        </div>
        <div class="comment-detail">
            <textarea maxlength="500" cols="30" rows="5"  autocomplete="off"  placeholder="写下购买体会或者使用中带来的帮助等，可以为其他小伙伴提供参考~" class="comment-text"></textarea>
        </div>
            <a class="btn" href="#">提交评价</a>
    </section>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    $(function(){
        $(".i-star i").click(function(){
            $(".i-star i").css("color","#ffce28");
            $(this).css("color","#ffce28");
            $(this).nextAll().css("color","#ccc");
        })
    })
</script>
</body>
</html>
