<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>合伙人申请</em></h1>
</header>
<section class="address">
    {if $act eq 'apply'}
    <div class="add-address">
        {if $level gt 0}
        {$account}已成为合伙人
        {else}
        <form method="post" enctype="multipart/form-data">
            <label for="partner_fee"><span style="width: 30.5%;">合伙人费用:</span>
                <input type="text" disabled="disabled" id="partner_fee" name="partner_fee" placeholder="{$config.partner_fee}">
            </label>
            <label for="payment"><span style="width: 30.5%;">支付方式:</span>
                <select name="payment" id="payment">
                    <option value="">请选择</option>
                    {foreach from=$payment_list item=payment}
                    <option value="{$payment.plugins}">{$payment.name}</option>
                    {/foreach}
                    <option value="wechat_pay">微信代付</option>
                </select>
            </label>
            <label for="agree"><span style="width: 30.5%;"><a href="article.php?id=3">《用户协议》:</a></span>
                <input style="margin-left: 18px" type="checkbox" class="fl c_checkbox" id="agree" name="agree" checked="checked">
            </label>
            <div class="address-btn">
                <input type="hidden" name="opera" value="apply"/>
                <a href="javascript:topay();" class="btn" id="pay_btn">确认支付</a>
            </div>
        </form>
        {/if}
    </div>
    {/if}
</section>
<section class="article" id="qrcode-area" style="display:none;position: fixed;top: 2.2rem;text-align: center;width: 100%;background: rgba(0,0,0,0.5);">
    <section class="article-con" id="qrcode" style="margin-top: 1rem;">
    </section>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
{if is_weixin()}
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.1.0.js"></script>
{/if}
<script type="text/javascript">
    var global_result = null;

    $(function() {
        $(".paydetail ul li span").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
        })

        $('#payment').change(function() {
            var value = $(this).val();
            if( value == '' ) {
                return;
            }
            get_pay_link(value);
        });
    });

    {if $act eq 'pay'}
    wx.ready(function(){
        wx.chooseWXPay({
            timestamp: {$payment.timestamp},
            nonceStr: "{$payment.nonce_str}",
            package: 'prepay_id={$payment.prepay_id}',
            signType: 'MD5',
            paySign: "{$payment.sign}",
            success: function (res) {
                // 支付成功后的回调函数
                if(res.errMsg == "chooseWXPay:ok") {
                    window.location.href = "copartner_result.php?account={$payment.account}";
                } else {
                    show_message_dialog(res.errMsg+":支付失败");
                }
            }
        });
    });
    {/if}

    function topay() {
//        show_message_dialog("等待支付接口申请下来");
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").html(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function get_pay_link(plugins) {
        switch(plugins)
        {
            case "wechat":
                get_prepay_id();
                break;
            case "wechat_pay":
                get_pay_code();
                break;
            default:
                show_message_dialog("该支付方式暂无接口支持");
                break;
        }
    }

    function get_pay_code() {
        var url = 'data_center.php';
        var data = { "opera":"get_qrcode", "url":"copartner.php?act=pay&account={$smarty.session.account}" };

        show_mask();
        $.post(url, data, get_pay_code_handler, "json");
    }

    function get_pay_code_handler(result) {
        hide_mask();
        if(result.error == 0) {
            $("#qrcode").html('<img src="'+result.url+'"/>');
            $("#qrcode").append('<p style="font-size: 1rem;color: #f1f1f1;margin-top: .5rem;">请用微信扫描二维码支付！</p>');
            $("#qrcode-area").show();
        } else {
            show_message_dialog(result.msg);
        }
    }

    function get_prepay_id() {
        var data = { "opera":"wechat" };
        var url = "copartner.php";

        show_mask();
        $.post(url, data, get_prepay_id_handler, "json");
    }

    function get_prepay_id_handler(result) {
        hide_mask();
        if(result.error == 0) {
            global_result = result;
            $("#pay_btn").bind("click", function() {
                wx.chooseWXPay({
                    timestamp: global_result.timestamp,
                    nonceStr: global_result.nonce_str,
                    package: 'prepay_id='+global_result.prepay_id,
                    signType: 'MD5',
                    paySign: global_result.sign,
                    success: function (res) {
                        // 支付成功后的回调函数
                        if(res.errMsg == "chooseWXPay:ok") {
                            window.location.href = "copartner_result.php";
                        } else {
                            show_message_dialog(res.errMsg+":支付失败");
                        }
                    }
                });
            });
        } else {
            show_message_dialog(result.msg);
        }
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }

    {if is_weixin()}
        wx.config({
                appId: '{$signPackage.appId}',
                timestamp: {$signPackage.timestamp},
            nonceStr: '{$signPackage.nonceStr}',
        signature: '{$signPackage.signature}',
        jsApiList: [
        'chooseWXPay',
        'closeWindow'
    ]
    });
    {/if}
</script>
</body>
</html>