<style>
    <!--
    .float-icon {
        position: fixed;
        right: .5rem;
        top: 60%;
        border: 2px solid rgba(255,206,40,1);
        border-radius: 40px;
        background: #fff;
        font-size: .6rem;
        padding: 7px .3rem;
        opacity: .5;
        text-align: center;
        line-height: 1.1rem;
    }
    -->
</style>
<div class="float-icon" id="float-icon">
    <span class="icon" style="font-size: 1rem;margin-bottom: 0.3rem;">&#xe600;</span><br/>
    在线客服
</div>