<!DOCTYPE html>
<html>
<head>
<title>互动专区</title>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
<meta name="format-detection" content="telephone=no"/>
<meta name="apple-mobile-web-app-capable" content="yes" />
<link rel="stylesheet" type="text/css" href="{$template_dir}css/common.css"/>
<link rel="stylesheet" type="text/css" href="{$template_dir}css/app.css"/>
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
</head>
<body style="padding-bottom: 0;background: #ddd; font-size: 16px;">
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$page_title}</em></h1>
</header>
<section style="padding: 10px 5px 50px; background: #ddd;">
    {foreach from=$forums item=forum}
    <div class="forum-item" id="forum-{$forum.id}">
        <div class="forum-header">
            <img src="{if $forum.photo}{$forum.photo}{else}{$template_dir}images/wang.jpg{/if}" class="forum-photo"/>
            <div class="forum-info">
                <p class="forum-id">{$forum.name}</p>
                <p class="forum-date">{$forum.date}</p>
            </div>
        </div>
        <div class="forum-content">
            {$forum.content|escape}
            {if $forum.img}
            <div class="forum-img">
                {foreach from=$forum.img item=img}
                <img src="{$img}" class="forum-img-item"/>
                {/foreach}
            </div>
            {/if}
        </div>
        <div class="forum-toolbar">
            <span style="float: right; margin-right: 40px;">
            <a href="javascript:up({$forum.id});" id="forum-up-{$forum.id}" class="forum-up" {if $forum.up}style="background-position:-290px -33px;"{/if}>
                    <span id="forum-up-count-{$forum.id}">{if $forum.up_count}{$forum.up_count}{else}赞{/if}</span>
            </a>
            <a href="forum.php?act=detail&id={$forum.id}" class="forum-share"></a>
            <a href="javascript:comment({$forum.id});" id="forum-comment-{$forum.id}" class="forum-comment">
                <span id="forum-comment-count-{$forum.id}">{$forum.comment_count}</span>
            </a>
            </span>
        </div>
        <div class="forum-comment-list">
            <ul id="comment-list-{$forum.id}">
                {if $forum.comment}
                {foreach from=$forum.comment item=comment}
                <li id="forum-comment-{$comment.id}" class="forum-comment-item">
                    <img src="{if $comment.photo}{$comment.photo}{else}{$template_dir}images/wang.jpg{/if}" class="forum-comment-photo"/>
                    <p class="forum-comment-id">{$comment.name}:</p>
                    <span class="forum-comment-content">{$comment.comment|escape}</span>
                </li>
                {/foreach}
                {/if}
            </ul>
        </div>
    </div>
    {/foreach}
</section>
<div id="comment">
    <div class="post-forum-content-wr">
        <textarea class="post-forum-content" id="post-comment" placeholder="回点啥呗..."></textarea>
    </div>
    <div class="post-forum-bottom-nav">
        <input type="button" class="input-btn post-forum-btn" name="post" value="发送" id="post"/>
        <input type="button" class="input-btn post-forum-cancel-btn" name="cancel" value="取消" id="cancel"/>
    </div>
</div>
<div id="mask"></div>
{include file="comment_footer.lbi"}
<script type="text/javascript">
var comment_id = 0;
window.onload = function() {
    $("#cancel").bind("click", cancel);
    $("#post").bind("click", post);
}
function topic() {
    window.location.href = 'forum.php?act=post&id={$id}';
}
{literal}
function showMask() {
    var mask = document.getElementById("mask");
    var screenWidth = document.body.scrollWidth;
    var screenHeight = window.screen.height < document.body.scrollHeight ? window.screen.height : document.body.scrollHeight;
    var scrollHeight = document.body.scrollHeight > window.screen.height ? document.body.scrollHeight : window.screen.height;
    mask.style.height = scrollHeight+"px";
    mask.style.width = screenWidth+"px";
    mask.style.display = "block";
}
function hideMask() {
    $("#mask").hide();
}
function cancel() {
    hideMask();
    $("#post-comment").val("");
    $("#comment").hide();
}
function comment(id) {
    comment_id = id;
    showMask();
    $("#comment").show();
}
function up(id) {
    if(id <= 0) {
        info('参数错误');
    }

    $.post('forum.php', {'opera':'up', 'topic_id':id}, upHandler, 'json');
}
function upHandler(result) {
    if(result.error) {
        info(result.msg);
    } else {
        if(result.opera == 'add') {
            $("#forum-up-count-"+result.id).text(result.count);
            $("#forum-up-"+result.id).css({"background-position":"-290px -33px"});
        } else {
            if(result.count == 0)
            {
                result.count = '赞';
            }
            $("#forum-up-count-"+result.id).text(result.count);
            $("#forum-up-"+result.id).css({"background-position":"-307px 0px"});
        }
    }
}
function post() {
    if(comment_id <= 0) {
        cancel();
        info('参数错误');
        return false;
    }

    var comment = $("#post-comment").val();
    if(comment == '') {
        info('评论内容不能为空');
        return false;
    }

    $.post('forum.php', {'opera':'do_post', 'comment':comment, 'id':comment_id}, commentHandler, 'json');
}
function commentHandler(result) {
    if(result.error) {
        info(result.msg);
    } else {
        $(result.comment).insertBefore("#comment-list-"+result.comment_id);
        var count = $("#forum-comment-count-"+result.comment_id).text();
        count++;
        $("#forum-comment-count-"+result.comment_id).text(count);
    }
    cancel();
}
var o = null;
var sid = 0;
function info(msg) {
    var screenWidth = document.body.scrollWidth;
    var screenHeight = window.screen.height < document.body.scrollHeight ? window.screen.height : document.body.scrollHeight;
    var e = $("<div class='tips'>"+msg+"</div>");
    $("body").append(e);
    var top = (screenHeight-e.height())/2;
    var left = (screenWidth)/3-20;
    console.info(top+"px,"+left+"px,"+screenWidth+"px,"+e.width()+"px");
    e.css({"position":"fixed","top": top+"px","left": left+"px", "z-index": 999999});
    e.fadeOut(3000);
    o = e;
    sid = setInterval(function() {o.remove(); clearInterval(sid); }, 3000);
}
</script>
{/literal}
</body>
</html>
