<!DOCTYPE html>
<html>
<head>
<title>互动专区</title>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
<meta name="format-detection" content="telephone=no"/>
<meta name="apple-mobile-web-app-capable" content="yes" />
<link rel="stylesheet" type="text/css" href="{$template_dir}css/common.css"/>
<link rel="stylesheet" type="text/css" href="{$template_dir}css/app.css"/>
<script src="{$template_dir}js/jquery-1.11.0.min.js" type="text/javascript"></script>
</head>
<body style="padding-bottom: 0; font-size: 16px;">
<section style="padding-bottom: 0">
    <div class="post-forum-toolbar">
        <input type="text" maxlength="16" class="post-forum-content" onkeyup="check_title_length();" placeholder="请填写标题" name="title" style="width: 70%;line-height: 20px;padding: 2px 5px;"/>
        <input type="button" class="input-btn post-forum-btn" name="post" value="发送"/>
    </div>
    <div class="post-forum-content-wr">
        <textarea class="post-forum-content" placeholder="说两句呗..." name="content"></textarea>
    </div>
    <div class="post-forum-bottom-nav" style="display: none">
        选择发布板块：
        <input type="hidden" name="type" value="{$topic_id}"/>
        {foreach from=$topic name=topic item=t}
        <div class="input-radio {if $smarty.foreach.topic.first}input-radio-checked{/if}" id="{$t.id}">{$t.name}</div>
        {/foreach}
    </div>
</section>
{literal}
<script type="text/javascript">
window.onload = function() {
    document.getElementsByName('post')[0].onclick = postTopic;
    $(".post-forum-bottom-nav div").each(function(){
            $(this).bind('click', selectType);        
    });
}

function selectType(type) {
    type = type.toElement;
    id = type.id;
    $(".post-forum-bottom-nav div").each(function() {
            $(this).attr("class", "input-radio"); 
    });
    $("#"+id).attr("class", "input-radio input-radio-checked");
    document.getElementsByName('type')[0].value = id;
}

function postTopic() {
    var topic = document.getElementsByName("content")[0].value;
    var type = document.getElementsByName("type")[0].value;
    var title = document.getElementsByName("title")[0].value;
    $.post('forum.php', {'opera':'topic','content':topic, 'type':type, 'title':title}, postTopicHandler, 'json');
}

function postTopicHandler(result) {
    if(result.error) {
        info(result.msg);
    } else {
        info('新话题发布成功，请等待审核<br/>稍后将跳转到板块页面');
        setInterval(function() {window.history.back();}, 3000);
    }
}

var o = null;
var sid = 0;
function info(msg) {
    var screenWidth = document.body.scrollWidth;
    var screenHeight = window.screen.height < document.body.scrollHeight ? window.screen.height : document.body.scrollHeight;
    var e = $("<div class='tips'>"+msg+"</div>");
    $("body").append(e);
    var top = (screenHeight-e.height())/3;
    var left = (screenWidth-e.width())/2;
    console.info(top+"px,"+left+"px,"+screenWidth+"px,"+e.width()+"px");
    e.css({"position":"fixed","top": top+"px","left": left+"px", "z-index": 999999});
    e.fadeOut(3000);
    o = e;
    sid = setInterval(function() {o.remove(); clearInterval(sid); }, 3000);
}

function check_title_length() {
    var title = document.getElementsByName("title")[0].value;

    if(countLength(title) > 16) {
        info('标题不要超过16个汉字,否则将无法正常显示');
    }
}

function countLength(str) {
    var length = 0;
    for(var i = 0; i < str.length; i++) {
        var c = str.charCodeAt(i);
        if((c >= 0x0001 && c <= 0x007e) || (0xff60<=c && c<=0xff9f)) {
            length += 0.5;
        } else {
            length += 1;
        }
    }
    return length;
}
</script>
{/literal}
</body>
</html>
