<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>用户中心</em></h1>
</header>
<!-- 用户基本信息 -->
<section class="home">
    <header class="user-info">
        <section class="user-basic">
            <img class="user-avatar" src="{$template_dir}images/wang.jpg" alt="用户">
            <div class="user-name">隔壁老王</div>
            <p class="user-number">合伙人89757</p>
            <section class="remaining">
                <a href="#"><em>余额&nbsp;0.00</em></a>
                <a href="#"><em>佣金&nbsp;0.00</em></a>
                <a href="#"><em>积分&nbsp;0.00</em></a>
            </section>
        </section>
        <section class="user-stat">
            <a id="change_count" href="#"><em>0</em>消费总额</a>
            <a id="product_collect_number" href="#"><em>0</em>商品收藏</a>
            <a id="read_history_count" href="#"><em>5</em>我的足迹</a>
        </section>
    </header>
    <!-- 我的订单 -->
    <section class="f-section order-section">
        <a class="slide-link" href="#">
            <span class="icon">&#xe622;</span>
            我的订单            <em>查看全部购买商品</em>
        </a>
        <nav class="order-nav">
            <ul>
                <li>
                    <a id="onlinepay_orders_count" href="#">
                        <p class="icon">&#xe627;</p>
                        待付款
                        <sup class="badge">2</sup>
                    </a>
                </li>
                <li>
                    <a id="confirm_orders_count" href="#">
                        <p class="icon">&#xe623;</p>
                        待收货
                    </a>
                </li>
                <li>
                    <a id="pd-comment" href="#">
                        <p class="icon">&#xe624;</p>
                        待评价
                    </a>
                </li>
                <li>
                    <a id="refund" href="#">
                        <p class="icon">&#xe61f;</p>
                        退换货
                    </a>
                </li>
            </ul>
        </nav>
    </section>
    <!-- 我的资产 -->
    <section class="f-section wealth-section">
        <a class="slide-link" href="wallet.html">
            <span class="icon" style="background-color: #7dc4fb;">&#xe619;</span>
            我的资产            <em>查看我的全部资产</em>
        </a>
        <nav class="order-nav">
            <ul>
                <li>
                    <a href="#" >
                        <p class="icon">&#xe61d;</p>
                        余额
                    </a>
                </li>
                <li>
                    <a href="#" >
                        <p class="icon">&#xe62a;</p>
                        佣金
                    </a>
                </li>
                <li>
                    <a href="#">
                        <p class="icon">&#xe620;</p>
                        积分
                    </a>
                </li>
                <li>
                    <a href="#">
                        <p class="icon">&#xe616;</p>
                        优惠券
                    </a>
                </li>
            </ul>
        </nav>
    </section>
    <!-- 个人中心功能菜单 -->
    <section class="f-section">
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #f29ec2;">&#xe625;</span>我的资料
        </a>
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #d0c0a6;">&#xe61a;</span>收货地址
        </a>
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #fb9065;">&#xe621;</span>我要提现
        </a>
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #80c269;">&#xe626;</span>我的推广
        </a>
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #f29902;">&#xe61e;</span>我的分销
        </a>
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #c2cb5a;">&#xe61c;</span>我要开店
        </a>
    </section>
    <section class="f-section">
        <a class="slide-link" href="#">
            <span class="icon" style="background-color: #acd697;">&#xe61b;</span>投诉维权
        </a>
    </section>
    <!-- 猜你喜欢 -->
    <section class="f-section might-like">
        <h3><i class="icon">&#xe617;</i>猜你喜欢<a href="#"><span class="icon">&#xe618;</span>&nbsp;换一批</a></h3>
        <ul>
            <li>
                <a href="#">
                    <img src="{$template_dir}images/product_1.jpg" alt="产品图">
                    <span>【圣宝先自营】松花粉</span>
                    <em>￥160.00</em>
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="{$template_dir}images/product_1.jpg" alt="产品图">
                    <span>【圣宝先自营】松花粉</span>
                    <em>￥160.00</em>
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="{$template_dir}images/product_1.jpg" alt="产品图">
                    <span>【圣宝先自营】松花粉</span>
                    <em>￥160.00</em>
                </a>
            </li>
        </ul>
    </section>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.html"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.html"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.html"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
