<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/app.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>修改密码</em></h1>
</header>
<!--修改密码页面 -->
<section class="register">
    <section class="register-con">
        <p class="title">请设置新密码：</p>
        <div class="pw_contain">
            <div class="inp pw bg nomar">
                <span class="icon"></span>
                <span class="input"><input id="password" type="text" placeholder="密码：6-20位字母或数字"></span>
                <span class="change show"></span>
                <span class="clear" style="display: none;"></span>
            </div>
        </div>
        <a class="btn" href="#">设置新密码</a>
    </section>
</section>

<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>

</body>
</html>
