<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>修改密码</em></h1>
</header>
<!-- 修改密码页面 -->
<section class="register">
    <section class="register-con">
        <div class="inp user bg">
            <span class="icon"></span>
            <span class="input"><input id="username" type="text" value="1366****635" placeholder="请输入你的手机号" disabled="disabled"></span>
            <span class="more"></span>
            <span class="clear" style="display: none;"></span>
        </div>
        <div class="pw_contain">
            <div class="inp graphics short small bg">
                <span class="input"><input class="identify_code" type="text" placeholder="请输入图形验证码"></span>
                <span class="clear" style="display: none;"></span>
            </div>
            <div class="identify">
                <a class="refresh" href="#" onclick="return false;">refresh</a>
                <img class="repic" src="{$template_dir}images/show_vcode.jpg" alt="验证码">
            </div>
        </div>
        <a class="btn" href="new_password2.html">获取短信校验码</a>
    </section>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
