<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>修改密码</em></h1>
</header>
<!-- 修改密码页面 -->
<section class="register">
    <section class="register-con">
        <p class="title">已发送验证码到 123****8910</p>
        <div>
            <div class="inp user short small bg">
                <span class="input"><input type="text" id="verify" placeholder="请输入验证码"></span>
                <span class="clear" style="display: none;"></span>
            </div>
            <button id="reget" class="" type="button" on="获取验证码" off="重新获取" time="60"><em>重新获取</em><i>39</i></button>
        </div>
        <a class="btn" href="forget_password3.html">下一步</a>
    </section>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
