<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header" style="position:fixed">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>消息中心</em></h1>
</header>

<!-- 内容开始 -->
<section class="newslist">
    <ul>
        <li>
            <a href="#">
                <dl class="arrow">
                    <dt>公告<span>2015/09/28</span></dt>
                    <dd>健康生活，辟谷之旅</dd>
                </dl>
            </a>
        </li>
        <li>
            <a href="#">
                <dl class="arrow">
                    <dt>隔壁老王<span>2015/09/20</span></dt>
                    <dd>你购买的【酵素粉】已发货...</dd>
                </dl>
            </a>
        </li>
    </ul>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
