<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商品详情</em></h1>
</header>
<!-- 产品图片轮播区 -->
<section id="focus" class="focus">
    <div class="hd">
        <ul></ul>
    </div>
    <div class="bd">
        <ul>
            <li><a href="#"><img _src="{$template_dir}images/product_1.jpg" src="{$template_dir}images/blank.png" /></a></li>
            <li><a href="#"><img _src="{$template_dir}images/product_1.jpg" src="{$template_dir}images/blank.png"/></a></li>
            <li><a href="#"><img _src="{$template_dir}images/product_1.jpg" src="{$template_dir}images/blank.png"/></a></li>
        </ul>
    </div>
</section>
<!-- 产品详情页 -->
<section class="product-detail">
    <article>八方好运 富硒复合酵素</article>
    <div class="left">
        <b>￥<span id="main_price">160.00</span></b>
        <aside>
            <span class="blue"><em class="icon">&#xe614;</em>返利7元</span>
        </aside>
    </div>
    <div class="right">
        <ul>
            <li class="share"><a href="javascript:;" onclick="document.getElementById('mcover').style.display='block';">分享</a></li>
        </ul>
    </div>
    <div id="mcover" onclick="document.getElementById('mcover').style.display='';" style="display: none;">
        <img src="{$template_dir}images/guide.png">
    </div>
</section>
<!-- 推广链接二维码 -->
<section class="qr-link">
    <div class="top">
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe60f;</em>&nbsp;获取推广二维码</a></span>
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe615;</em>&nbsp;获取推广链接</a></span>
    </div>
    <div class="bottom">
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe610;</em>&nbsp;进店逛逛</a></span>
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe613;</em>&nbsp;联系掌柜</a></span>
    </div>
</section>
<!-- 产品属性选择 -->
<section class="option">
    <a class="arrow_con title">
        <div class="arrow_d up">商品属性选择</div>
    </a>
    <div class="option_detail">
        <h3 id="size_name">规格</h3>
        <ul id="size_options">
            <li>12包/盒</li><li>24包/盒</li></ul>
        <h3 id="packing_name">包装</h3>
        <ul id="packing_options">
            <li>简装</li>
            <li>礼品盒</li>
        </ul>
    </div>
</section>
<!-- 数量开始 -->
<section class="quantity">
    <h4>数量：</h4>
    <div class="number_con">
        <span class="minus">-</span>
        <div class="input"><input id="buy_num" type="text" value="1"></div>
        <span class="plus on">+</span>
    </div>
</section>

<!-- 产品详情 -->
<section class="detail-con">
    <a class="arrow_con title">
        <div class="arrow_d">商品详情</div>
    </a>
    <section id="detail-con" style="display: none;">
        <div class="detail-con-style">
            <div class="clear"></div>
            <div class="detail-con-style-list">品牌：八方好运</div>
            <div class="detail-con-style-list">规格：12包/盒 </div>
            <div class="detail-con-style-list">适用人群：不限</div>
        </div>
        <div class="detail-content">
            <p>&nbsp;</p>
            <img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/detail1.png">
            <img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/detail2.png">
        </div>
    </section>
</section>
<!-- 产品评论 -->
<section class="comment">
   <div class="title">产品评论</div>
    <ul class="clearfix">
        <li>
            <div class="block">
                <div class="div1">
                    <span class="head_pic">
                        <img src="{$template_dir}images/default-user.png" alt="">
                    </span>
                    <span class="user_name">老王</span>
                    <span class="level-star">
                         <i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i>
                    </span>
                </div>
                <div class="message">经常睡不着，吃了一盒复合酵素明显有改善</div>
                <div class="pic_list clearfix"></div>
                <div class="time">
                    <span class="c_96 fr">2015-02-02</span>
                </div>
            </div>
        </li>
        <li>
            <div class="block">
                <div class="div1">
                    <span class="head_pic">
                        <img src="{$template_dir}images/default-user.png" alt="">
                    </span>
                    <span class="user_name">kkk</span>
                    <span class="level-star">
                         <i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe638;</i><i class="icon">&#xe639;</i><i class="icon">&#xe639;</i>
                    </span>
                </div>
                <div class="message">味道挺好的，应该是多谷物混合而成的，挺适合挑食的人</div>
                <div class="pic_list clearfix"></div>
                <div class="time">
                    <span class="c_96 fr">2015-02-02</span>
                </div>
            </div>
        </li>
        <div class="more">更多评论</div>
    </ul>
</section>
<div style="height: 2.49rem;">&nbsp;</div>
<!-- 产品页底部 -->
<section class="actionBar-container">
    <div class="action-bar mui-flex">
        <div class="addfav cell">
            <i class="icon">&#xe611;</i>
            收藏
        </div>
        <div class="distribution cell">
            <i class="icon">&#xe612;</i>
            分销
            <a href="#"></a>
        </div>
        <button class="cart cell">加入购物车</button>
        <button class="buy cell">立即购买</button>
    </div>
</section>
<!--<div class="cd-popup is-visible" role="alert">-->
    <!--<div class="cd-popup-container">-->
        <!--<p>宝贝已成功加入购物车！</p>-->
        <!--<ul class="cd-buttons">-->
            <!--<li><a href="#0">继续购物</a></li>-->
            <!--<li><a href="#0">前往结算</a></li>-->
        <!--</ul>-->
        <!--<a href="#0" class="cd-popup-close img-replace">Close</a>-->
    <!--</div>-->
<!--</div>-->
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
        $(".option .arrow_con").click(function(){
            if($(".option .arrow_d").hasClass("up")){
                $(".option_detail").slideUp();
                $(".option .arrow_d").removeClass("up");
            }else{
                $(".option_detail").slideDown();
                $(".option .arrow_d").addClass("up");
            }
        });
        $(".option_detail ul li").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
        });
        $(".detail-con .arrow_con").click(function(){
            if($(".detail-con .arrow_d").hasClass("up")){
                $("#detail-con").slideUp();
                $(".detail-con .arrow_d").removeClass("up");
            }else{
                $("#detail-con").slideDown();
                $(".detail-con .arrow_d").addClass("up");
            }
        })
    });
</script>
<script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
<script type="text/javascript">
    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:true,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });
</script>
</body>
</html>
