<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/app.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>收益排行榜</em></h1>
</header>
<!-- 收益排行榜页面 -->
<section class="ranking">
    <section class="ranking-con">
        <ul>
            <li>
                <div class="ranking-list">
                    <img src="images/wang.jpg" alt="隔壁老王" />
                    <div class="ranking-detail">
                        <span>隔壁老王</span>
                        <span>收益<em>￥111.11</em></span>
                    </div>
                    <i class="ranking-num r123">1</i>
                </div>
            </li>
            <li>
                <div class="ranking-list">
                    <img src="images/wang.jpg" alt="小明" />
                    <div class="ranking-detail">
                        <span>小明</span>
                        <span>收益<em>￥89.11</em></span>
                    </div>
                    <i class="ranking-num r123">2</i>
                </div>
            </li>
            <li>
                <div class="ranking-list">
                    <img src="images/wang.jpg" alt="思聪" />
                    <div class="ranking-detail">
                        <span>思聪</span>
                        <span>收益<em>￥71.11</em></span>
                    </div>
                    <i class="ranking-num r123">3</i>
                </div>
            </li>
            <li>
                <div class="ranking-list">
                    <img src="images/wang.jpg" alt="大胖" />
                    <div class="ranking-detail">
                        <span>大胖</span>
                        <span>收益<em>￥51.11</em></span>
                    </div>
                    <i class="ranking-num">4</i>
                </div>
            </li>
            <li>
                <div class="ranking-list">
                    <img src="images/wang.jpg" alt="叶良辰" />
                    <div class="ranking-detail">
                        <span>叶良辰</span>
                        <span>收益<em>￥31.11</em></span>
                    </div>
                    <i class="ranking-num">5</i>
                </div>
            </li>
            <!-- 收益排行列出前10即可 -->
        </ul>
    </section>
</section>

<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>

</body>
</html>
