<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我要充值</em></h1>
</header>
<!-- 我要充值 -->
<section class="recharge">
    <div class="recharge-con">
        <div class="recharge-tips">
            <i class="icon">&#xe60c;</i>充值金额将充入到余额款项中，余额可用于购物，加盟等费用抵用，充值的款项将无法退回。
        </div>
        <div class="recharge-info">
            <h3>充值到平台</h3>
            <label><span>所属银行：</span>中国工商银行</label>
            <label><span>平台账号：</span>44444*******5555</label>
            <label><span>账户名称：</span>圣宝先</label>
        </div>
        <div class="recharge-value">
            <label><span>充值金额：</span><input type="text" value="" placeholder="请填写金额（元）"></label>
        </div>
        <div class="recharge-btn">
            <a class="btn" href="#" onclick="return false;">确认充值</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
