<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/app.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>积分明细</em></h1>
</header>
<!-- 积分明细 -->
<section class="record">
    <div class="record-detail">
        <ul>
            <li>
                晒单（订单号：123456789）
                <em class="plus">+100</em>
                <p>2015-09-15 18:02:13</p>
            </li>
            <li>
                购物（订单号：123456789）
                <em class="plus">+100</em>
                <p>2015-09-15 18:27:13</p>
            </li>
            <li>
                兑换ipad（订单号：123456789）
                <em>-10000</em>
                <p>2015-09-15 18:02:13</p>
            </li>
        </ul>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.html"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.html"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.html"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>

</body>
</html>
