<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>确认支付</em></h1>
</header>
<!-- 支付详情 -->
<section class="paycon">
    <div class="paydetail">
        <ul>
            <li>订单编号：{$order.order_sn}</li>
            <li>订单详情：</li>
            {foreach from=$order_detail item=od}
            <li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {$od.product_name}x{$od.count}
            </li>
            {/foreach}
            <li>支付金额：<i class="red_money">{sprintf("%.2f", $order.amount)}元</i></li>
            <li>支付方式：
                {foreach from=$payment_list item=payment}
                <span onclick="get_pay_link('{$payment.plugins}');">{$payment.name}</span>
                {/foreach}
            </li>
        </ul>
        <div class="paybtn-con">
            <a href="javascript:topay();" class="paybtn">确认支付</a>
        </div>
    </div>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    $(function() {
        $(".paydetail ul li span").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
        })
    });

    function topay() {
        show_message_dialog("等待支付接口申请下来");
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").text(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function get_pay_link(plugins) {

    }
</script>
</body>
</html>
