<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>查看物流</em></h1>
</header>
<!-- 查看物流页面 -->
<section class="track">
    <section class="track-con">
        <div class="order-track border_bottom">
            <div class="order-track-l">
                <img src="{$template_dir}images/sbx-product.png" alt="产品图"/>
            </div>
            <div class="order-track-r">
                <span class="track-status">物流状态：<em>已签收</em></span>
                <span>承运公司：圆通快递</span>
                <span>运单编号：1344554233444</span>
            </div>
        </div>
        <div class="track-detail">
            <div class="track-detail-con">
                <i class="icon">&#xe61a;</i>
                <ul>
                    <li class="selected"><span class="icon">&#xe636;</span><span>【广州市】广东省广州市科学城公司 已签收 签收人：本人签收，感谢使用圆通速递，期待再次为您服务</span><p>2015-09-10 12:56:17</p></li>
                    <li><span class="icon">&#xe636;</span><span>【广州市】广东省广州市科学城派件员：廖宜军 13416178144正在为您派件</span><p>2015-09-10 09:12:41</p></li>
                    <li><span class="icon">&#xe636;</span><span>广东省广州市科学城 已收入</span><p>2015-09-10 09:12:41</p></li>
                    <li><span class="icon">&#xe636;</span><span>【广州市】广州转运中心 已发出</span><p>2015-09-09 18:07:34</p></li>
                    <li><span class="icon">&#xe636;</span><span>广州转运中心公司 已收入</span><p>2015-09-09 15:20:18</p></li>
                    <li><span class="icon">&#xe636;</span><span>浙江省金华市义乌市公司 已发出</span><p>2015-09-08 22:56:25</p></li>
                    <li><span class="icon">&#xe636;</span><span>浙江省金华市义乌市市场三部公司 已发出</span><p>2015-09-08 20:17:33</p></li>
                    <li><span class="icon">&#xe636;</span><span>【金华市】圆通速递 浙江省金华市义乌市市场三部收件员 已揽件</span><p>2015-09-08 19:26:23</p></li>
                    <li><span class="icon">&#xe636;</span><span>商家正通知快递公司揽件</span><p>2015-09-08 12:59:39</p></li>
                </ul>
            </div>
        </div>
    </section>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
