<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>圣宝先移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="圣宝先移动商城">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我要提现</em></h1>
</header>
<!-- 我要提现 -->
<section class="withdrawals">
    <div class="withdrawals-con">
        <label><span>账户余额:</span><i class="red_money">￥1000.00</i></label>
        <label><span>提现金额:</span><input type="text" name="提现金额" value="" placeholder="请输入提现金额"></label>
        <label><span>请选择银行卡:</span><a href="javascript:" class="s-bank"><i></i>中国工商银行（尾号1234）借记卡</a></label>
        <label><span>&nbsp;</span><a href="javascript:" class="s-bank current"><i></i>中国招商银行（尾号8888）借记卡</a></label>
        <label><span>&nbsp;</span><a href="#" class="a-bank"><i>+</i>添加银行卡</a></label>
        <label><span>提现密码:</span><input type="password" name="提现密码" value="" placeholder="请输入提现密码"></label>
        <div class="withdrawals-btn">
            <a class="btn" href="#" onclick="return false;">确认提交</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.html"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.html"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.html"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
