{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<style>
    {literal}
    .select-image {
        cursor: pointer;
    }
    {/literal}
</style>

<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />
<script type="text/javascript" >
    var data_product_attr = {$json_attr_list};
    var attributes = {$attributes};
</script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">审核虚拟产品</h5>
        <div class="clear"></div>
    </div>
    <div class="adminUser-main">
        <form id="productExamForm" name="productExamForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">产品编号：</label>
                    <input disabled="disabled" class="text-input w300" type="text" id="product_sn" name="product_sn" placeholder="请输入产品编号" value="{$product.product_sn}">
                </p>
                <p>
                    <label class="l-title">名称：</label>
                    <input disabled="disabled" class="text-input w300" type="text" id="name" name="name" placeholder="请输入产品名称" value="{$product.name}">
                </p>
                <p class="clear">
                    <label class="l-title">产品分类：</label>
                    <select disabled="disabled" name="category" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$category_list item=category}
                        <option value="{$category.id}" {if $category.id eq $product.category_id}selected="selected"{/if}>{$category.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p class="clear">
                    <label class="l-title">消费内容：</label>
                </p>
                <p class="clear" id="show-content">
<!--                    <div style="width: 400px; margin: 0 auto">-->
                        <table class="table"   style="width: 1000px; margin: 0 auto">
                            <thead>
                            <tr>
                                <th>消费内容</th>
                                <th>数量/规格</th>
                                <th>小计</th>
                            </tr>
                            </thead>
                            <tbody>
                            {foreach from=$content_list item=content}
                            <tr>
                                <td>
                                    {$content.content}
                                </td>
                                <td>
                                    <em>{$content.count}</em>
                                </td>
                                <td>{$content.total}</td>
                            </tr>
                            {/foreach}
                            </tbody>
                        <table>
<!--                    </div>-->
                </p>
                <p class="clear">
                    <label class="l-title">售价：</label>
                    <input disabled="disabled" class="text-input w150" type="text" id="price" name="price" placeholder="请输入售价" value="{$product.price}">
                </p>
                <p>
                    <label class="l-title">市场价：</label>
                    <input disabled="disabled" class="text-input w150" type="text" id="shop_price" name="shop_price" placeholder="请输入市场价" value="{$product.shop_price}">
                </p>
                <p>
                    <label class="l-title">最低售价：</label>
                    <input disabled="disabled" class="text-input w150" type="text" name="lowest_price" placeholder="请输入最低销售价" value="{$product.lowest_price}">
                </p>
                <p>
                    <label class="l-title">产品图片：</label>
                    <input type="hidden" name="img" id="img" placeholder="" value="{$product.img}">
                    {if $product.img}
                    <img class="select-image" alt="" height="150" src="../{$product.img_src}">&nbsp;
                    {else}
                    <img class="select-image" alt="" src="../upload/image/no-image.png">&nbsp;
                    {/if}
                    {if $gallery_list}
                    {foreach from=$gallery_list item=gallery}
                    <img class="select-image" alt="" src="../{$gallery.thumb_img}">&nbsp;
                    {/foreach}
                    {/if}
                </p>
                <p>
                    <label class="l-title">产品简介：</label>
                    <textarea disabled="disabled" name="desc" rows="5" cols="93">{$product.desc}</textarea>
                </p>
                <p>
                    <label class="l-title">产品详情：</label>
                    <textarea disabled="disabled" name="detail">{$product.detail}</textarea>
                </p>
                <p>
                    <label class="l-title">促销价：</label>
                    <input disabled="disabled" class="text-input w150" type="text" name="promote_price" placeholder="促销价" value="{$product.promote_price}">
                </p>
                <p>
                    <label class="l-title">促销开始时间：</label>
                    <input disabled="disabled" class="text-input w300" type="text" name="promote_begin" placeholder="促销开始时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal}  value="{$product.promote_begin}"/>
                </p>
                <p>
                    <label class="l-title">促销结束时间：</label>
                    <input disabled="disabled" class="text-input w300" type="text" name="promote_end" placeholder="促销结束时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal}  value="{$product.promote_end}">
                </p>
                <p>
                    <label class="l-title">产品排序：</label>
                    <input disabled="disabled" class="text-input w150" type="text" name="order_view" placeholder="" value="{$product.order_view}">
                </p>
                <p>
                    <label class="l-title">返利：</label>
                    <input class="text-input w150" type="text" name="reward" placeholder="返利" value="{$product.reward}">
                </p>
                <p>
                    <label class="l-title">购买积分：</label>
                    <input class="text-input w150" type="text" name="integral" placeholder="购买积分" value="{$product.integral}">
                </p>
                <p>
                    <label class="l-title">赠送积分：</label>
                    <input class="text-input w150" type="text" name="integral_given" placeholder="赠送积分" value="{$product.integral_given}">
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="exam" />
                    <input type="hidden" name="id" value="{$product.id}"/>
                    <button class="btn btn-primary" type="submit">通过</button> &nbsp;
                    <a class="btn btn-primary" href="virtual_product.php?act=reject&id={$product.id}">驳回</a> &nbsp;
                    <a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>

            </fieldset>
        </form>
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->
<!-- kindeditor编辑器 -->
<script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
    {literal}
    KindEditor.ready(function(K) {
        var editor1 = K.create("textarea[name='detail']", {
            height: '400px',
            width: '60%',
            cssPath: '../plugins/kindeditor/plugins/code/prettify.css',
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php',
            allowFileManager: true,
            afterCreate: function () {
                var self = this;
                K.ctrl(document, 13, function () {
                    self.sync();
                    K('form[name=productExamForm]')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function () {
                    self.sync();
                    K('form[name=productExamForm]')[0].submit();
                });
            }
        });
    });
    {/literal}
</script>
<script type="text/javascript" src="js/product/exam.js"></script>
{include file="library/footer.lbi"}
</body>
</html>