{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<style>
{literal}
    .select-image {
        cursor: pointer;
    }
{/literal}
</style>

<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />
<script type="text/javascript" >
    var data_product_attr = {$json_attr_list};
</script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">添加产品</h5>
        <div class="clear"></div>
    </div>
    <div class="adminUser-main">
        <form id="productAddForm" name="productAddForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">产品编号：</label>
                    <input class="text-input w300" type="text" id="product_sn" name="product_sn" placeholder="请输入产品编号" minlength="2" maxlength="32">
                    <input type="checkbox" id="status" name="status" value="1"><em>上架</em>
                </p>
                <p>
                    <label class="l-title">名称：</label>
                    <input class="text-input w300" type="text" id="name" name="name" placeholder="请输入产品名称" minlength="5">
                </p>
                <p class="clear">
                    <label class="l-title">产品分类：</label>
                    <select name="category" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$category_list item=category}
                        <option value="{$category.id}">{$category.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p class="clear">
                    <label class="l-title">产品类型：</label>
                    <select name="type" id="product_type" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$product_type_list item=product_type}
                        <option value="{$product_type.id}">{$product_type.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p style="display: none" id="product_attr" class="clear">
                </p>
                <p class="clear">
                    <label class="l-title">品牌：</label>
                    <select name="brand" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$brand_list item=brand}
                        <option value="{$brand.id}">{$brand.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">库存：</label>
                    <input class="text-input w150" type="text" id="inventory" name="inventory" placeholder="请输入库存">
                </p>
                <p>
                    <label class="l-title">售价：</label>
                    <input class="text-input w150" type="text" id="price" name="price" placeholder="请输入售价">
                </p>
                <p>
                    <label class="l-title">市场价：</label>
                    <input class="text-input w150" type="text" id="shop_price" name="shop_price" placeholder="请输入市场价">
                </p>
                <p>
                    <label class="l-title">最低售价：</label>
                    <input class="text-input w150" type="text" name="lowest_price" placeholder="请输入最低销售价">
                </p>
                <p>
                    <label class="l-title">返利：</label>
                    <input class="text-input w150" type="text" name="reward" placeholder="返利">
                </p>
                <p>
                    <label class="l-title">购买积分：</label>
                    <input class="text-input w150" type="text" name="integral" placeholder="购买积分">
                </p>
                <p>
                    <label class="l-title">赠送积分：</label>
                    <input class="text-input w150" type="text" name="integral_given" placeholder="赠送积分">
                </p>
                <p>
                    <label class="l-title">产品图片：</label>
                    <input type="hidden" name="img" id="img" placeholder="">
                    <img class="select-image" alt="" src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image">&nbsp;
                </p>
                <p>
                    <label class="l-title">产品简介：</label>
                    <textarea name="desc" rows="5" cols="93"></textarea>
                </p>
                <p>
                    <label class="l-title">产品详情：</label>
                    <textarea name="detail"></textarea>
                </p>
                <p>
                    <label class="l-title">促销价：</label>
                    <input class="text-input w150" type="text" name="promote_price" placeholder="促销价">
                </p>
                <p>
                    <label class="l-title">促销开始时间：</label>
                    <input class="text-input w300" type="text" name="promote_begin" placeholder="促销开始时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal} />
                </p>
                <p>
                    <label class="l-title">促销结束时间：</label>
                    <input class="text-input w300" type="text" name="promote_end" placeholder="促销结束时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal}>
                </p>
                <p>
                    <label class="l-title">重量：</label>
                    <input class="text-input w150" type="text" name="weight" placeholder="单位：千克">
                </p>
                <p>
                    <label class="l-title">产品排序：</label>
                    <input class="text-input w150" type="text" name="order_view" placeholder="" value="50">
                </p>
                <p class="clear">
                    <label class="l-title">包邮：</label>
                    <input type="radio" name="free_delivering" value="0" checked="checked"> <em>否</em>&nbsp;
                    <input type="radio" name="free_delivering" value="1"> <em>是</em>
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="add" />
                    <button class="btn btn-primary" type="submit">添加</button> &nbsp;<a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>

            </fieldset>
        </form>
    </div>
    <div id="modal-product-attr" class="modal modal-large">
        <div class="modal-dialog">
            <div class="modal-head">
                <h1 class="modal-title">产品属性</h1>
                <a href="javascript: void(0)" class="close-modal" rel="modal:close">&times;</a>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button class="btn btn-primary" type="button" id="confirm">确定</button>&nbsp;
                    <a class="btn btn-primary" rel="modal:close">取消</a>
                </div>
            </div>
        </div>
    </div>
    <div id="modal-edit-product-attr" class="modal modal-large">
        <div class="modal-dialog">
            <div class="modal-head">
                <h1 class="modal-title">产品属性</h1>
                <a href="javascript: void(0)" class="close-modal" rel="modal:close">&times;</a>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button class="btn btn-primary" type="button" id="edit-confirm">确定</button>&nbsp;
                    <a class="btn btn-primary" rel="modal:close">取消</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->
<!-- kindeditor编辑器 -->
<script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
    {literal}
    KindEditor.ready(function(K) {
        var editor1 = K.create("textarea[name='detail']", {
            height: '400px',
            width: '60%',
            cssPath: '../plugins/kindeditor/plugins/code/prettify.css',
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php',
            allowFileManager: true,
            afterCreate: function () {
                var self = this;
                K.ctrl(document, 13, function () {
                    self.sync();
                    K('form[name=productAddForm]')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function () {
                    self.sync();
                    K('form[name=productAddForm]')[0].submit();
                });
            }
        });
        var editor = K.editor({
            allowFileManager: true,
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php'
        });
        K('.select-image').click(function() {
            editor.loadPlugin('image', function() {
                editor.plugin.imageDialog({
                    imageUrl : '',
                    clickFn : function(url, title, width, height, border, align) {
                        if( !width ) {
                            width = 200 + 'px';
                        }
                        if( !height ) {
                            height = 150 + 'px';
                        }

                        K('#img').val(url);
                        K('.select-image').attr('src', url);
                        K('.select-image').css('display', 'block');
                        K('.select-image').attr('width', width);
                        K('.select-image').attr('height', height);
                        editor.hideDialog();
                    }
                });
            });
        });
    });
    {/literal}
</script>
<script type="text/javascript" src="js/product/add.js"></script>
{include file="library/footer.lbi"}
</body>
</html>