{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<style>
    {literal}
    .select-image {
        cursor: pointer;
    }
    {/literal}
</style>

<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />
<script type="text/javascript" >
//    var data_product_attr = {$json_attr_list};
    var attributes = {$attributes};
</script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">编辑产品</h5>
        <div class="clear"></div>
    </div>
    <div class="adminUser-main">
        <form id="productEditForm" name="productEditForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">产品编号：</label>
                    <input disabled="disabled" class="text-input w300" type="text" id="product_sn" name="product_sn" placeholder="请输入产品编号" value="{$product.product_sn}">
                </p>
                <p>
                    <label class="l-title">名称：</label>
                    <input class="text-input w300" type="text" id="name" name="name" placeholder="请输入产品名称" value="{$product.name}">
                </p>
                <p class="clear">
                    <label class="l-title">产品分类：</label>
                    <select name="category" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$category_list item=category}
                        <option value="{$category.id}" {if $category.id eq $product.category_id}selected="selected"{/if}>{$category.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p class="clear">
                    <label class="l-title">产品类型：</label>
                    <select name="type" id="product_type" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$product_type_list item=product_type}
                        <option value="{$product_type.id}" {if $product_type.id eq $product.product_type_id}selected="selected"{/if}>{$product_type.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p class="clear" id="paoduct_attr">
                <p class="clear" id="show-attr">
                    <div class="pull-left" style="width: 80%;" id="show-attr-0">
                        <p style="display: inline-block" class="clear">
                            <label class="l-title">颜色：</label>
                            <em>红色</em>
                            <select name="attr[0][1]" class="w100 product-attribute" label="颜色" style="display: none;">
                                <option value="红色">红色</option><option value="绿色">绿色</option>
                            </select>
                        </p>
                        <p style="display: inline-block" class="clear">
                            <label class="l-title">尺码：</label>
                            <em>SL</em>
                            <select name="attr[0][2]" class="w100 product-attribute" label="尺码" style="display: none;">
                                <option value="SL">SL</option>
                                <option value="L">L</option>
                                <option value="ML">ML</option>
                                <option value="XL">XL</option>
                                <option value="XXL">XXL</option>
                            </select>
                        </p>
                        <p style="display: inline-block" class="clear">
                            <label class="l-title">印花主题：</label>
                            <em>123</em>
                            <input type="text" class="text-input w50 product-attribute required" name="attr[0][3]" label="印花主题" style="border: 1px solid rgb(213, 213, 213); color: rgb(0, 0, 0); display: none;">
                        </p>
                        <p style="display: inline-block" class="clear">
                            <label class="l-title">上市时间：</label><em>123</em><input type="text" class="text-input w50 product-attribute required" name="attr[0][4]" label="上市时间" style="border: 1px solid rgb(213, 213, 213); color: rgb(0, 0, 0); display: none;"></p>
                        <p style="display: inline-block" class="clear">
                            <label class="l-title">面料：</label>
                            <em>123</em>
                            <input type="text" class="text-input w50 product-attribute required" name="attr[0][9]" label="面料" style="border: 1px solid rgb(213, 213, 213); color: rgb(0, 0, 0); display: none;">
                        </p>
                        <p style="display: inline-block" class="clear"><label class="l-title">季度：</label>
                            <em>123</em>
                            <input type="text" class="text-input w50 product-attribute required" name="attr[0][10]" label="季度" style="border: 1px solid rgb(213, 213, 213); color: rgb(0, 0, 0); display: none;">
                        </p>
                        <p style="display: inline-block" class="clear">
                            <label class="l-title">库存：</label>
                            <em>123</em>
                            <input class="text-input w50 product-attribute" type="text" name="inventory[0]" placeholder="请输入库存" label="库存" style="display: none;">
                        </p>
                    </div>
                    <div class="pull-right">
                        <button class="btn btn-primary edit-attr" type="button">编辑</button>&nbsp;<button class="btn btn-primary remove-attr" type="button">删除</button>&nbsp;
                    </div>
                </p>
                <p class="clear">
                    <label class="l-title">品牌：</label>
                    <select name="brand" class="w150">
                        <option value="0">|--请选择--|</option>
                        {foreach from=$brand_list item=brand}
                        <option value="{$brand.id}" {if $brand.id eq $product.brand_id}selected="selected"{/if}>{$brand.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">库存：</label>
                    <input class="text-input w150" type="text" disabled="disabled" id="inventory" name="single_inventory" placeholder="请输入产品库存" value="{$inventory}"/>
                </p>
                <p>
                    <label class="l-title">售价：</label>
                    <input class="text-input w150" type="text" id="price" name="price" placeholder="请输入售价" value="{$product.price}">
                </p>
                <p>
                    <label class="l-title">市场价：</label>
                    <input class="text-input w150" type="text" id="shop_price" name="shop_price" placeholder="请输入市场价" value="{$product.shop_price}">
                </p>
                <p>
                    <label class="l-title">最低售价：</label>
                    <input class="text-input w150" type="text" name="lowest_price" placeholder="请输入最低销售价" value="{$product.lowest_price}">
                </p>
                <p>
                    <label class="l-title">产品图片：</label>
                    <input type="hidden" name="img" id="img" placeholder="" value="{$product.img}">
                    {if $product.img}
                    <img class="select-image" alt="" width="200" height="200" src="../{$product.img_src}">&nbsp;
                    {else}
                    <img class="select-image" alt="" src="../upload/image/no-image.png" height="200px">&nbsp;
                    {/if}
                </p>
                <p>
                    <label class="l-title">产品简介：</label>
                    <textarea name="desc" rows="5" cols="93">{$product.desc}</textarea>
                </p>
                <p>
                    <label class="l-title">产品详情：</label>
                    <textarea name="detail">{$product.detail}</textarea>
                </p>
                <p>
                    <label class="l-title">促销价：</label>
                    <input class="text-input w150" type="text" name="promote_price" placeholder="促销价" value="{$product.promote_price}">
                </p>
                <p>
                    <label class="l-title">促销开始时间：</label>
                    <input class="text-input w300" type="text" name="promote_begin" placeholder="促销开始时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal}  value="{$product.promote_begin}"/>
                </p>
                <p>
                    <label class="l-title">促销结束时间：</label>
                    <input class="text-input w300" type="text" name="promote_end" placeholder="促销结束时间" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"{/literal}  value="{$product.promote_end}">
                </p>
                <p>
                    <label class="l-title">重量：</label>
                    <input class="text-input w150" type="text" name="weight" placeholder="产品重量" value="{$product.weight}">克
                </p>
                <p>
                    <label class="l-title">产品排序：</label>
                    <input class="text-input w150" type="text" name="order_view" placeholder="" value="{$product.order_view}">
                </p>
                <p class="clear">
                    <label class="l-title">包邮：</label>
                    <input type="radio" name="free_delivering" value="0" {if $product.free_delivery eq 0}checked="checked"{/if}> <em>否</em>&nbsp;
                    <input type="radio" name="free_delivering" value="1" {if $product.free_delivery eq 1}checked="checked"{/if}> <em>是</em>
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="edit" />
                    <input type="hidden" name="id" value="{$product.id}"/>
                    <button class="btn btn-primary" type="submit">提交</button> &nbsp;<a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>

            </fieldset>
        </form>
    </div>
    <div id="modal-product-attr" class="modal modal-large">
        <div class="modal-dialog">
            <div class="modal-head">
                <h1 class="modal-title">产品属性</h1>
                <a href="javascript: void(0)" class="close-modal" rel="modal:close">&times;</a>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button class="btn btn-primary" type="button" id="confirm">确定</button>&nbsp;
                    <a class="btn btn-primary" rel="modal:close">取消</a>
                </div>
            </div>
        </div>
    </div>
    <div id="modal-edit-product-attr" class="modal modal-large">
        <div class="modal-dialog">
            <div class="modal-head">
                <h1 class="modal-title">产品属性</h1>
                <a href="javascript: void(0)" class="close-modal" rel="modal:close">&times;</a>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button class="btn btn-primary" type="button" id="edit-confirm">确定</button>&nbsp;
                    <a class="btn btn-primary" rel="modal:close">取消</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->
<!-- kindeditor编辑器 -->
<script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
    KindEditor.ready(function(K) {
        var editor1 = K.create("textarea[name='detail']", {
            height: '400px',
            width: '60%',
            cssPath: '../plugins/kindeditor/plugins/code/prettify.css',
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php',
            allowFileManager: true,
            afterCreate: function () {
                var self = this;
                K.ctrl(document, 13, function () {
                    self.sync();
                    K('form[name=productEditForm]')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function () {
                    self.sync();
                    K('form[name=productEditForm]')[0].submit();
                });
            }
        });
        var editor = K.editor({
            allowFileManager: true,
            uploadJson: '../plugins/kindeditor/upload_json.php',
            fileManagerJson: '../plugins/kindeditor/file_manager_json.php'
        });
        K('.select-image').click(function() {
            editor.loadPlugin('image', function() {
                editor.plugin.imageDialog({
                    imageUrl : '',
                    clickFn : function(url, title, width, height, border, align) {
                        if( !width ) {
                            width = 200 + 'px';
                        }
                        if( !height ) {
                            height = 200 + 'px';
                        }

                        K('#img').val(url.replace("{$smarty.const.BASE_DIR}", ""));
                        K('.select-image').attr('src', "../"+url.replace("{$smarty.const.BASE_DIR}", ""));
                        K('.select-image').css('display', 'block');
                        K('.select-image').attr('width', width);
                        K('.select-image').attr('height', height);
                        editor.hideDialog();
                    }
                });
            });
        });
    });
</script>
<script type="text/javascript" src="js/product/edit.js"></script>
{include file="library/footer.lbi"}
</body>
</html>