{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$product.name}-修改库存</h5>
        <div class="pull-right"><a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;</div>
        <div class="clear"></div>
    </div>
    <div class="inventory-main">
        <table class="table">
            <thead>
            <tr>
                <th>产品属性</th>
                <th>库存</th>
                <th>逻辑库存</th>
                <th>待发库存</th>
                <th>备注</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$inventory_list item=inventory}
            <form id="inventoryForm-{$inventory.id}" name="inventoryForm" method="post" onsubmit="return do_submit({$inventory.id});">
                <tr>
                    <td>{$inventory.attributes_str}</td>
                    <td>
                        <input class="text-input w300" type="text" name="inventory" value="{$inventory.inventory}" id="inventory-{$inventory.id}">
                        <span class="error-input" id="inventory-{$inventory.id}-error"></span>
                    </td>
                    <td>{$inventory.inventory_logic}</td>
                    <td>{$inventory.inventory_await}</td>
                    <td>待发库存不为0时<br />新库存不能小于待发库存</td>
                    <td>
                    <a type="submit" class="btn btn-primary submit-btn" id="submit-btn-{$inventory.id}" data-id="{$inventory.id}" href="javascript:;">
                        修改<img src="images/btn_loading.gif" class="btn-loading-img" id="btn-loading-img-{$inventory.id}"/>
                    </a>&nbsp;
                    <input type="hidden" name="opera" value="inventory" />
                    <input type="hidden" name="id" id="id-{$inventory.id}" value="{$inventory.id}" />
                    <input type="hidden" name="sn" id="sn-{$inventory.id}" value="{$inventory.product_sn}" />
                    </td>
                </tr>
            </form>
            {/foreach}
            </tbody>
        </table>
    </div>
</div>
<div id="mask"></div>
<script type="text/javascript">
    /**
     * 这个解决方案可以作为Ajax提交表单的模板
     * 1、form的提交操作托管给do_submit处理;
     * 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
     * 3、仅支持post方式提交表单;
     * 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码<div id="mask"></div>
     **/
$(function() {
    $('.submit-btn').click(function() {
        var id = $(this).attr('data-id');
        do_submit(id);
    });
});

    function do_submit(id) {
        //参数校验
        var flag = true;
        var inventory = $("#inventory-" + id).val();
        var id = $("#id-" + id).val().trim();
        var sn = $("#sn-" + id).val().trim();

        inventory = parseInt(inventory);
        if( inventory < 0 ) {
            $("#inventory-" + id + '-error').text("-库存不能小于0");
            flag = false;
        }
        if(flag) {
            flag = true;
            //启用过渡效果
            $("#btn-loading-img-"+id).show();
            $(".submit-btn").addClass("btn-disabled");
            $("#mask").show();

            var params = { "opera":"inventory", "inventory":inventory, 'id':id};
            var url = "product.php";
            $.post(url, params, do_response, "json");
        }

        return flag;
    }

    function do_response(result) {
        //关闭过渡效果
        var edit_id = result.edit_id;
        $(".btn-loading-img").hide();
        $(".submit-btn").removeClass("btn-disabled");
        $("#mask").hide();
        //处理返回结果
        if(result.error == 0) {
            alert(result.msg);
            $('#inventory-' + edit_id).val(result.new_inventory);
            $('#inventory-' + edit_id).parent().next().text(result.new_inventory_logic);
        } else {
            if(result.msg != "") {
                alert(result.msg);
            }

            if(result.errmsg.length) {
                for(var id in result.errmsg) {
                    $("#"+id+"-error").text(result.errmsg[id]);
                }
            }
        }
    }
</script>
{include file="library/footer.lbi"}
</body>
</html>