<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的账户</em></h1>
</header>
<!-- 内容开始 -->
<section class="points" style="margin-top:-.5rem;">
    <div class="points-detail">
        <a class="slide-link" href="#">
            余额：{$user_info.balance}&nbsp;&nbsp;圈币：{$user_info.reward}&nbsp;&nbsp;积分：{$user_info.integral}
        </a>
        <ul>
            {foreach from=$member_exchange item=exchange}
            <li>
                {$exchange.remark}
                <p>
                    余额：<span {if $exchange.balance gt 0}style="color:red"{/if}>{if $exchange.balance gt 0}+{/if}{$exchange.balance}</span>
                    圈币：<span {if $exchange.reward gt 0}style="color:red"{/if}>{if $exchange.reward gt 0}+{/if}{$exchange.reward}</span>
                    积分：<span {if $exchange.integral gt 0}style="color:red"{/if}>{if $exchange.integral gt 0}+{/if}{$exchange.integral}</span>
                </p>
                <p>{date("Y-m-d H:i:s", $exchange.add_time)}</p>
            </li>
            {/foreach}
        </ul>
    </div>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
</body>
</html>
