<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>收货地址列表</em></h1>
    <a href="address.php?act=add" class="edit">新增</a>
</header>
<section class="select-address">
    <div class="address-list">
        {if $address_list}
        {foreach from=$address_list item=address}
        <div class="address_item">
            <div class="detail" style="margin-left:20px;">
                <p class="a-name">{$address.consignee}<span class="a-phone">{$address.mobile}</span></p>
                <p class="a-address">{$address.detail_address}</p>
                <div class="clear tags">
                    {if $address.is_default}<span>默认地址</span>{/if}
                    <a class="garbage" href="address.php?act=edit&id={$address.id}"></a>
                </div>
            </div>
            <div class="bottom_line"></div>
        </div>
        {/foreach}
        {else}
        您尚未添加任何地址
        {/if}
    </div>
</section>
</body>
</html>
