<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商城公告</em></h1>
</header>
<section class="home">
    <section class="f-section">
        {foreach from=$article_list item=article}
        <a class="slide-link" href="article.php?id={$article.id}">
            <i class="link-tag"></i>{$article.title}
        </a>
        {/foreach}
    </section>
    <!-- 猜你喜欢 -->
    <!--
    <section class="f-section might-like">
        <h3><i class="icon">&#xe61b;</i>猜你喜欢<a href="#"><span class="icon">&#xe625;</span>&nbsp;换一批</a></h3>
        <ul>
            <li>
                <a href="#">
                    <img src="images/product_1.jpg" alt="产品图">
                    <span>【速来健自营】速来健玛卡片</span>
                    <em>￥160.00</em>
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="images/product_1.jpg" alt="产品图">
                    <span>【速来健自营】速来健玛卡片</span>
                    <em>￥160.00</em>
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="images/product_1.jpg" alt="产品图">
                    <span>【速来健自营】速来健玛卡片</span>
                    <em>￥160.00</em>
                </a>
            </li>
        </ul>
    </section>
    -->
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
