<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/mobile.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的银行卡</em></h1>
    <a href="#" class="edit">添加</a>
</header>
<!-- 银行卡列表 -->
<section class="bank">
    <div class="bank-list">
        <ul>
            <li class="bank-list-item">
                <div class="bank-title">
                    <div class="fl">中国建设银行</div>
                    <div class="fr">尾号0580<span>存储卡</span></div>
                </div>
                <div class="bank-con">
                    <div class="bank-item">
                        <span class="info">持卡人姓名：***王</span>
                        <a href="javascript:" class="font-blue fr">修改</a>
                    </div>
                    <div class="bank-item">
                        <span class="info">手机号：136****4635</span>
                        <a href="javascript:" class="font-blue fr">删除</a>
                    </div>
                </div>
            </li>
            <li class="bank-list-item">
                <div class="bank-title">
                    <div class="fl">中国建设银行</div>
                    <div class="fr">尾号0580<span>存储卡</span></div>
                </div>
                <div class="bank-con">
                    <div class="bank-item">
                        <span class="info">持卡人姓名：***王</span>
                        <a href="javascript:" class="font-blue fr">修改</a>
                    </div>
                    <div class="bank-item">
                        <span class="info">手机号：136****4635</span>
                        <a href="javascript:" class="font-blue fr">删除</a>
                    </div>
                </div>
            </li>
            <li class="quick-add">
                <a class="quick-add-item">
                    <span class="icon bg">&#xe628;</span>
                    添加银行卡
                </a>
            </li>
        </ul>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.html"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.html"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.html"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    $(function(){
        $(".bank-list-item").click(function(){
            $(this).addClass("hover").find(".font-blue").show();
            $(this).siblings().removeClass("hover").find(".font-blue").hide();
        })
    });
</script>

</body>
</html>
