<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>购物车</em></h1>
</header>
<!-- 购物车列表 -->
<div class="wrapper">
    <div class="viewport">
        <section class="content">
            <div class="block">
                <div class="cart_list">
                    <div class="shop_title" shop_id="7825">
                        <input type="checkbox" class="fl c_checkbox">
                        <div class="fl"><a class="shopLink eclipse" href="#">科皮妮旗舰店</a></div>
                        <a class="fl right_arrow" href="#"></a>
                        <a class="c_edit" id="e__7825"></a>
                    </div>
                    <div class="cart_item" id="1248291811" item_id="2072461422" stock="67">
                        <input type="checkbox" class="fl c_checkbox" checked="">
                        <img src="http://img31.ddimg.cn/19/19/1248291811-1_h.jpg" class="fl pro_pic">
                        <div class="detail">
                            <p class="fr prd_price">￥369.00</p>
                            <p class="fl prd_tit"><a href="#">Copione科皮妮2015新款女士包包女包大包单肩斜挎包休闲尼龙包欧美时尚手提包8325_藏蓝色,单肩斜挎手提配头层牛皮</a></p>
                        </div>
                        <div class="edit_area">
                            <a class="fr bottom_arrow arrow_num"></a>
                            <p class="fr num"><span class="fr quantity">1</span></p>

                            <p class="fl attrs">
                                <span>藏蓝色</span>
                                <span>单肩斜挎手提配头层牛皮</span>
                            </p>
                            <!--                        <a class="fl bottom_arrow edit_color_size"></a>-->
                            <p class="fr border_right"></p>

                        </div>

                        <div class="bottom_line"></div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="total_result">
            <div class="fl ">
                <input type="checkbox" class="c_checkbox" id="cart_check_all" style="">
                <span style="color:">全选</span>
            </div>

            <div class="fr">
                <a style="color:;background-color:;border:.1rem solid red;" class="c_btn payBtn" id="do_checkout" href="javascript:;">去结算(<span id="cart_quantity">1</span>)</a>
            </div>
            <div class="fr totalPrice">
                <span>商品金额总计</span>
                <p id="cart_price" style="color:">            <span style="color:">￥319.00</span>
                </p>
            </div>
        </footer>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
<script type="text/javascript">
    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:true,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });
</script>
</body>
</html>
