<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/mobile.css">
    <link rel="stylesheet" href="css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>编辑银行卡</em></h1>
</header>
<!-- 编辑银行卡 -->
<section class="bank">
    <div class="edit-bank">
        <label><span>开户人:</span><i class="red-font">隔壁老王</i></label>
        <label><span>银行卡号:</span><input type="text" name="银行卡号" value="6217********0580" placeholder="请输入银行卡号"></label>
        <label><span>银行名称:</span><input type="text" name="银行名称" value="建设银行" placeholder="请输入银行名称"></label>
        <label><span>开户行:</span><input type="text" name="开户行" value="天河支行" placeholder="请输入开户所在支行的名称"></label>
        <label><span>手机号码:</span><input type="text" name="手机号码" value="1366****11111" placeholder="请输入该卡在银行预留的号码 "></label>
        <label><span>提现密码:</span><input type="password" name="提现密码" value="111111" placeholder="请输入提现密码"></label>
        <div class="bank-btn">
            <a class="btn" href="#" onclick="return false;">确认修改</a>
        </div>
    </div>
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.html"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.html"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.html"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="#"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>

</body>
</html>
