<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/index.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<!-- 首页头部 -->
<header class="header">
    <div class="logo">
        <a href="product.php?id=1">生活圈</a>
    </div>
    <div class="search_box">
        <a href="#" >
            <div class="search">
                <form method="get" action="search.php">
                    <div class="text_box">
                        <input id="keyword" name="keyword" type="text" placeholder="搜索商品/店铺" class="keyword text" onkeydown="this.style.color='#404040'" autocomplete="off">
                    </div>
                    <input type="submit" value="" class="submit" dd_name="搜索">
                </form>
            </div>
        </a>
    </div>
    <div class="header_qb">
        <a href="account.php"><span><i>{$user_info.reward}</i>圈币</span></a>
    </div>
</header>
<!-- 广告轮播区 -->
<section id="focus" class="focus">
    <div class="hd">
        <ul></ul>
    </div>
    <div class="bd">
        <ul>
            <li><a href="product.php?id=1"><img _src="{$template_dir}images/m1.jpg" src="{$template_dir}images/blank.png" /></a></li>
            <li><a href="product.php?id=1"><img _src="{$template_dir}images/m2.jpg" src="{$template_dir}images/blank.png"/></a></li>
            <li><a href="product.php?id=1"><img _src="{$template_dir}images/m3.jpg" src="{$template_dir}images/blank.png"/></a></li>
        </ul>
    </div>
</section>
<!-- 首页功能区 -->
<ul class="index-nav">
    <li><a href="integral.php" title="我的积分"><img class="" src="{$template_dir}images/jifen.png"><span>我的积分</span></a></li>
    <li><a href="withdraw.php" title="账户提现"><img class="" src="{$template_dir}images/tixian.png"><span>账户提现</span></a></li>
    <li><a href="order.php" title="我的订单"><img class="" src="{$template_dir}images/dingdan.png"><span>我的订单</span></a></li>
    <li><a href="address.php" title="收货地址"><img class="" src="{$template_dir}images/dizhi.png"><span>收货地址</span></a></li>
</ul>
<!-- 首页公告区 -->
<section class="index-news clearfix">
    <div class="index-news-l fl"></div>
    <div id="myscroll" class="index-news-r fr">
        <ul id="notice" class="news-title">
            {foreach from=$notice item=n}
            <li><a href="article_list.php?id=1" target="_blank">{$n.title}</a></li>
            {/foreach}
        </ul>
    </div>
</section>
<!-- 首页商家推荐区 -->
<section class="floor">
    <h2>
        <a class="title"><i class="icon">&#xe610;</i>同圈优选</a>
        <a href="product_list.php?id=56" class="more" title="更多">更多</a>
    </h2>
    <dl>
        <dt><a href="product.php?id=1"><img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/H5.jpg" width="100%" height="auto"></a></dt>
        <dd><a href="distribution_shop.php"><img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/309x224-1.jpg" width="100%" height="auto"></a></dd>
        <dd><a href="apply.php"><img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/309x224-2.jpg" width="100%" height="auto"></a></dd>
    </dl>
</section>
<section class="floor">
    <h2>
        <a class="title"><i class="icon">&#xe611;</i>同城配送</a>
        <a href="product_list.php?id=56" class="more" title="更多">更多</a>
    </h2>
    <dl>
        <dt><a href="product.php?id=1"><img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/H5.jpg" width="100%" height="auto"></a></dt>
        <dd><a href="distribution_shop.php"><img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/309x224-1.jpg" width="100%" height="auto"></a></dd>
        <dd><a href="apply.php"><img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$template_dir}images/309x224-2.jpg" width="100%" height="auto"></a></dd>
    </dl>
</section>
<div style="height:1rem; "></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a class="active" href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
    });
</script>
<script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
<script type="text/javascript">
    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:true,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });
</script>
<script type="text/javascript" src="{$template_dir}js/scrolltext.js"></script>
<script type="text/javascript">
    var newsHeight = $(".index-news").height();
    if(document.getElementById("notice")){
        var scrollup = new ScrollText("notice");
        scrollup.LineHeight =  (newsHeight ==120)?40:20;//单排文字滚动的高度
        scrollup.Amount = 1;            //注意:子模块(LineHeight)一定要能整除Amount.
        scrollup.Delay = 35;           //延时
        scrollup.Start();             //文字自动滚动
        scrollup.Direction = "down"; //文字向下滚动
    }
</script>
</body>
</html>
