<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>我的推广</em></h1>
</header>
<!-- 内容开始 -->
<section class="points" style="padding-top: 0;margin-top:-.5rem;">
    <div class="points-detail">
        <ul>
            {foreach from=$member_list item=member}
            <li>
                <img class="member-photo" src="{if $member.headimg neq ""}{$member.headimg}{else}{$template_dir}images/wang.jpg{/if}" alt="用户"/>
                <p>微信昵称:{$member.nickname}</p>
                <p>手机号码:{$member.mobile}</p>
            </li>
            {/foreach}
        </ul>
    </div>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
</body>
</html>
