<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>物流跟踪</em></h1>
</header>
<!-- 新增收货地址 -->
<section class="address">
    {if $express_info.status eq 200}
    {foreach from=$express_info.data item=data name=express_info}
        {if $smarty.foreach.express_info.first}
            {if $express_info.state eq 3}
                <div class="express-complete">
            {else}
                <div class="express-incomplete">
            {/if}
        {else}
            {if $smarty.foreach.express_info.last}
                <div class="express-start">
            {else}
                <div class="experss-middle">
            {/if}
        {/if}
        <i></i>
            <span class="express-time">{$data.time}</span>
            <span class="express-context">{$data.context}</span>
        </div>
    {/foreach}
    {else}
        当前没有物流信息
    {/if}
</section>
</body>
</html>
