<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>评价晒单</em></h1>
</header>
<!-- 确定订单 -->
<section class="orderdetail-con">
    <!-- 订单产品详情 -->
    <section class="orders">
        <div class="border_lr trans_div order_action_block border_bottom">
            <div>
                <div>
                    <ul class="product_ul">
                        {foreach from=$order_detail item=od}
                        <li>
                            <div class="box" style="position: relative;">
                                <div class="product_cover">
                                    <img width="100%" src="{$od.img}">
                                </div>
                                <div class="product_info cr_2">
                                    <p class="product_name">{$od.product_name}</p>
                                </div>
                                <div class="fr prd_state">
                                    <!--状态文字-->
                                    <div class="prd_state_title product-comment" onclick="pcomment('{$od.product_sn}')">
                                    {if $od.has_comment lt 1}
                                        产品评价
                                    {else}
                                        追加评价
                                    {/if}
                                    </div>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="order-status-detail border_bottom" id="product_comment_form" style="display: none;">
        <div class="order-comment">
            <div>
                <label>产品评价：</label>
                <div class="star" id="product_star">
                    <li onclick="star(1, 'product_star');"></li>
                    <li onclick="star(2, 'product_star');"></li>
                    <li onclick="star(3, 'product_star');"></li>
                    <li onclick="star(4, 'product_star');"></li>
                    <li onclick="star(5, 'product_star');"></li>
                </div>
            </div>
            <div>
                <label>评价：</label>
                <textarea class="input-comment" name="pcomment" id="pcomment"></textarea>
                <input type="hidden" name="product_star" id="pstar" value="0"/>
                <input type="hidden" name="psn" id="psn" value=""/>
            </div>
            <div class="operation">
                <input type="hidden" name="product_star" value="0"/>
                <a href="javascript:product_comment();" class="orange_hollow">提交评价</a>
            </div>
        </div>
    </section>
    <section class="order-status-detail border_bottom">
        <div class="order-comment">
            <div>
                <label>服务评价：</label>
                {if !$is_comment}
                <div class="star" id="server_star">
                    <li onclick="star(1, 'server_star');"></li>
                    <li onclick="star(2, 'server_star');"></li>
                    <li onclick="star(3, 'server_star');"></li>
                    <li onclick="star(4, 'server_star');"></li>
                    <li onclick="star(5, 'server_star');"></li>
                </div>
                {else}
                已评价
                {/if}
            </div>
            {if !$is_comment}
            <div class="operation">
                <input type="hidden" name="server_star" value="0"/>
                <a href="javascript:comment('{$order_sn}');" class="orange_hollow">提交评价</a>
            </div>
            {/if}
        </div>
    </section>
    <div style="height: 60px;"></div>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    function pcomment(product_sn) {
        if(product_sn != "") {
            $("input[name=psn]").val(product_sn);
            $("#product_comment_form").show();
        }
    }

    function product_comment() {
        var comment = $("#pcomment").val().trim();
        var star = $("#pstar").val();
        var psn = $("#psn").val();
        var msg = "";

        if(psn == "") {
            return false;
        }

        star = parseInt(star);

        if(isNaN(star) || star < 1) {
            msg += "-请选择评价星级<br/>";
        }

        if(comment == "") {
            msg += "-请填写评语<br/>"
        }

        if(msg != "") {
            show_message_dialog(msg);
        } else {
            var url = "order.php";
            var data = { "opera":"product_comment", "product_sn":psn, "star":star, "comment":comment };

            show_mask();
            $.post(url, data, product_comment_handler, "json");
        }
    }

    function product_comment_handler(response) {
        if(response.error == 0) {
            window.location.reload();
        } else {
            hide_mask();
            show_message_dialog(response.msg);
        }
    }

    function comment(order_sn) {
        var star = $("input[name=server_star]").val();
        star = parseInt(star);

        if(isNaN(star) || star <= 0) {
            show_message_dialog("请选择评价星级");
            return false;
        }

        if(order_sn != '') {
            var url = "order.php";
            var data = { "opera":"comment", "order_sn":order_sn, "star":star };

            show_mask();
            $.post(url, data, comment_handler, "json");
        }
    }

    function comment_handler(response) {
        if(response.error == 0) {
            window.location.reload();
        } else {
            hide_mask();
            show_message_dialog(response.msg);
        }
    }

    function star(num, id) {
        var ele = $("#"+id).children();

        for(var i=0; i < num; i++) {
            ele[i].className = "on";
        }

        for(;i < ele.length; i++) {
            ele[i].className = "";
        }

        $("input[name="+id+"]").val(parseInt(num));
    }


    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").html(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
</body>
</html>