<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$product.name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商品详情</em></h1>
</header>
<!-- 产品图片轮播区 -->
<section id="focus" class="focus">
    <div class="hd">
        <ul></ul>
    </div>
    <div class="bd">
        <ul>
            {foreach from=$product.gallery item=gallery}
            <li><a href="#"><img _src="{$gallery}" src="{$template_dir}images/blank.png" /></a></li>
            {/foreach}
        </ul>
    </div>
</section>
<!-- 产品详情页 -->
<section class="product-detail">
    <article>{$product.name}</article>
    <div class="left">
        <b>￥<span id="main_price">{sprintf('%.2f', $product.price)}</span></b>
        <aside>
            <span class="blue"><em class="icon">&#xe60b;</em>返利{ceil($product.reward/2.5)}元</span>
            {if $product.lowest_price}<!--<span class="white">我要砍价</span>-->{/if}
        </aside>
    </div>
    <div class="right">
        <ul>
            <li class="share"><a href="javascript:;" onclick="document.getElementById('mcover').style.display='block';">分享</a></li>
        </ul>
    </div>
    <div id="mcover" onclick="document.getElementById('mcover').style.display='';" style="display: none;">
        <img src="{$template_dir}images/guide.png">
    </div>
</section>
<!-- 推广链接二维码 -->
<!--
<section class="qr-link">
    <div class="top">
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe604;</em>&nbsp;获取推广二维码</a></span>
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe60a;</em>&nbsp;获取推广链接</a></span>
    </div>
    <div class="bottom">
        <span>
            <a href="shop.php?id={$product.business_account}">
                <em class="icon" style="color: #dd2727;">&#xe605;</em>&nbsp;进店逛逛
            </a>
        </span>
        <span>
            <a href="tel:{$product.business.mobile}">
                <em class="icon" style="color: #dd2727;">&#xe608;</em>&nbsp;联系掌柜
            </a>
        </span>
    </div>
</section>
-->
<!-- 产品属性选择 -->
<section class="option">
    <a class="arrow_con title" name="attributes">
        <div class="arrow_d">选择 <span class="size">规格 </span><span class="split">/ </span><span class="packing">包装</span></div>
    </a>
    <div class="option_detail" style="display: none;">
        {foreach from=$attributes item=a}
        <h3 id="attr_{$a.id}">{$a.name}</h3>
        <ul id="attr_options_{$a.id}">
            {foreach from=$a.values item=val name=attr_val key=ak}
            <li id="attr_val_{$ak}_{$a.id}">{$val}</li>
            {/foreach}
        </ul>
        {/foreach}
    </div>
</section>
<!-- 数量开始 -->
<section class="quantity">
    <h4>数量：</h4>
    <div class="number_con">
        <span class="minus" id="minus">-</span>
        <div class="input"><input id="buy_num" name="buy_num" type="tel" value="1"></div>
        <span class="plus on" id="plus">+</span>
    </div>
</section>

<!-- 产品详情 -->
<section class="detail-con">
    <!--
    <div class="detail-con-style">
        <div class="clear"></div>
        <div class="detail-con-style-list">品牌：速来健</div>
        <div class="detail-con-style-list">规格：500mg/粒，60粒/瓶 </div>
        <div class="detail-con-style-list">适用人群：成年男、女性</div>
    </div>
    -->
    <div class="detail-content">
        {$product.detail}
    </div>
</section>
<!-- 产品评论 -->
<section class="comment">
   <div class="title">产品评论</div>
    <ul class="clearfix">
        {foreach from=$product.comments item=comment}
        <li>
            <div class="block">
                <div class="div1">
                    <span class="head_pic">
                        <img src="{if $comment.headimg}{$comment.headimg}{else}{$template_dir}images/default-user.png{/if}" alt="">
                    </span>
                    <span class="user_name">{$comment.nickname}</span>
                </div>
                <div class="message">
                    {$comment.comment}
                </div>
                <div class="pic_list clearfix"></div>
                <div class="time"><span class="c_96 fr">{date('Y-m-d', $comment.add_time)}</span></div>
            </div>
        </li>
        {/foreach}
        {if $comment_count gt 5}
        <div class="more">更多评论</div>
        {/if}
    </ul>
</section>
<div style="height: 49px;">&nbsp;</div>
<!-- 产品页底部 -->
<section class="actionBar-container">
    <div class="action-bar mui-flex">
        <div class="addfav cell {if $collection_flag}addfav-on{/if}" id="collection_btn">
            <i class="icon">&#xe606;</i>
            <span id="collection_desc">{if $collection_flag}取消收藏{else}收藏{/if}</span>
        </div>
        <div class="distribution cell {if $distribution_flag}distribution-on{/if}" id="distribution_btn">
            <i class="icon">&#xe607;</i>
            <span id="distribution_desc">{if $distribution_flag}取消分销{else}分销{/if}</span>
        </div>
        <button class="cart cell" id="add_to_cart_btn" style="margin-bottom: 0;">加入购物车</button>
        <button class="buy cell" id="buy_now_btn">立即购买</button>
    </div>
</section>
<!-- 加入购物车弹窗 -->
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="dialog" style="display: none;">
        <p>宝贝已成功加入购物车！</p>
        <ul class="cd-buttons">
            <li><a href="javascript:window.history.back();">继续购物</a></li>
            <li><a href="javascript:window.location.href='cart.php'">前往结算</a></li>
        </ul>
        <a href="javascript:close_operation_dialog();" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>

<script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="{$template_dir}js/jquery.min.js"></script>
<script type="text/javascript">
    var inventory = {$inventory_json};
    var attributes = {$attributes_json};
    var attributes_mode = {$attributes_mode};//筛选条件表达式
    var pattern = {$attributes_mode};//泛解析表达式

    function add_to_cart(product_sn) {
        var url = "cart.php";
        var buy_num = parseInt($("#buy_num").val());

        if(isNaN(buy_num) || buy_num <= 0) {
            show_message_dialog("请输入购买数量");
            return false;
        }

        if(!select_attributes_complete()) {
            show_message_dialog("请选择产品规格 包装");
            window.location.href = "#attributes";
            arrow_con_toggle();
            return false;
        }

        var data = { "opera":"add_to_cart", "product_sn": product_sn, "number": buy_num, "attributes": attributes_mode };
        show_mask();
        $.post(url, data, add_to_cart_handler, "json");
    }

    function add_to_cart_handler(response) {
        if(response.error == 0) {
            show_operation_dialog();
        } else {
            show_message_dialog(response.msg);
        }
    }

    function buy_now(product_sn) {
        var url = "cart.php";
        var buy_num = parseInt($("#buy_num").val());

        if(isNaN(buy_num) || buy_num <= 0) {
            show_message_dialog("请输入购买数量");
            return false;
        }

        if(!select_attributes_complete()) {
            show_message_dialog("请选择产品规格 包装");
            window.location.href = "#attributes";
            arrow_con_toggle();
            return false;
        }

        var data = { "opera":"add_to_cart", "product_sn": product_sn, "number": buy_num, "attributes": attributes_mode };
        show_mask();
        $.post(url, data, buy_now_handler, "json");
    }

    function buy_now_handler(response) {
        if(response.error == 0) {
            window.location.href= "cart.php";
        } else {
            show_message_dialog(response.msg);
        }
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").text(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_operation_dialog() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog").show();
    }

    function close_operation_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }

    function collection(product_sn) {
        var url = "product.php";
        var data = { "opera":"collection", "product_sn":product_sn };

        show_mask();
        $.post(url, data, collection_handler, "json");
    }

    function collection_handler(response) {
        hide_mask();
        show_message_dialog(response.msg);
        if(response.error == 0) {
            if(response.status) {
                $(".addfav").addClass("addfav-on");
                $("#collection_desc").text("取消收藏");
            } else {
                $(".addfav").removeClass("addfav-on");
                $("#collection_desc").text("收藏");
            }
        }
    }

    function distribution(product_sn) {
        var url = "product.php";
        var data = { "opera":"distribution", "product_sn":product_sn };

        show_mask();
        $.post(url, data, distribution_handler, "json");
    }

    function distribution_handler(response) {
        hide_mask();
        show_message_dialog(response.msg);
        if(response.error == 0) {
            if(response.status) {
                $(".distribution").addClass("distribution-on");
                $("#distribution_desc").text("取消分销");
            } else {
                $(".distribution").removeClass("distribution-on");
                $("#distribution_desc").text("分销");
            }
        }
    }

    function plus() {
        var buy_num = $("#buy_num").val();

        buy_num = parseInt(buy_num);
        if(isNaN(buy_num) || buy_num <= 0) {
            minus_disable();
            $("#buy_num").val(1);
        } else {
            buy_num++;
            $("#buy_num").val(buy_num);
            minus_enable();
        }
    }

    function minus() {
        var buy_num = $("#buy_num").val();

        buy_num = parseInt(buy_num);
        if(isNaN(buy_num) || buy_num <= 1) {
            minus_disable();
            $("#buy_num").val(1);
        } else {
            buy_num--;
            $("#buy_num").val(buy_num);
            if(buy_num <= 1) {
                minus_disable();
            }
        }
    }

    function minus_enable() {
        $("#minus").addClass("on");
        $("#minus").bind("click", minus);
    }

    function minus_disable() {
        $("#minus").removeClass("on");
        $("#minus").unbind("click");
    }

    function plus_enable() {
        $("#plus").addClass("on");
        $("#plus").bind("click", plus);
    }

    function plus_disable() {
        $("#plus").removeClass("on");
        $("#plus").unbind("click");
    }

    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:false,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });

    $(function(){
        var options = $(".option_detail");
        var options_values = options.children().children("li");
        options_values.each(function(i, e) {
            e.onclick = function() {
                select_attribute(this);
            }
        });

        $("#plus").bind("click", plus);
        $("#minus").bind("click", minus);

        $("#collection_btn").bind("click", function() { collection("{$product.product_sn}"); });
        $("#distribution_btn").bind("click", function() { distribution("{$product.product_sn}"); });

        $("#add_to_cart_btn").bind("click", function() { add_to_cart("{$product.product_sn}"); });
        $("#buy_now_btn").bind("click", function() { buy_now("{$product.product_sn}"); });
    });

    function select_attribute(e) {
        var tmp = e.id.split("_");
        var index = tmp[2];
        var aid = tmp[3];

        if(e.className == "on") {
            attributes_mode[aid] = ".*";
            pattern[aid] = ".*";
            e.className = "";
        } else {
            e.className = "on";
            console.info(aid+","+index+":"+attributes[aid]['values'][index]);
            pattern[aid] = attributes[aid]['values'][index];
            attributes_mode[aid] = attributes[aid]['values'][index];

            for (var i in pattern) {
                if (i != aid) {
                    pattern[i] = ".*";
                }
            }
        }

        toogle_options();
    }

    //根据条件开启/关闭可筛选条件
    function toogle_options() {
        var pattern_mode = "/"+JSON.stringify(pattern)+"/";
        console.info(pattern_mode);
        pattern_mode = eval(pattern_mode);
        //检索库存，选出符合当前单一条件的不可选库存条件
        var inventory_keys = [];
        var unavailable_keys = [];
        for(var i in inventory) {
            if(pattern_mode.test(i)) {
                inventory_keys.push(i);
            } else {
                unavailable_keys.push(i);
            }
        }
        console.info("inventory_keys="+inventory_keys);

        for(var i in unavailable_keys) {
            var tmp = unavailable_keys[i];
            tmp = eval("["+tmp+"]");
            tmp = tmp[0];
            for(var aid in tmp) {
                var index = seek_val_index(aid, tmp[aid]);
                console.info("matched:"+JSON.stringify(tmp));
                if(index == -1) continue;
                console.info("attr_val_" + index + "_" + aid);
                var ele = document.getElementById("attr_val_" + index + "_" + aid);
                if(ele != null && ele.className != undefined) {
                    if(ele.className != "on"){
                        ele.className = "disabled";
                        ele.onclick = null;
                    }
                }
            }
        }

        //检索当前组合已选条件是否具有满足的产品
        var attributes_mode_pattern = "/"+JSON.stringify(attributes_mode)+"/";
        attributes_mode_pattern = eval(attributes_mode_pattern);


        for(var i in inventory_keys) {
            if(attributes_mode_pattern.test(inventory_keys[i])) {
                console.info("matched :"+inventory_keys[i]);
                var tmp = inventory_keys[i];
                tmp = eval("["+tmp+"]");
                tmp = tmp[0];
                for(var aid in tmp) {
                    var index = seek_val_index(aid, tmp[aid]);
                    if(index == -1) continue;
                    var ele = document.getElementById("attr_val_" + index + "_" + aid);
                    if(ele != null && ele.className != undefined) {
                        if(ele.className != "on") {
                            ele.className = "";
                            ele.onclick = function() {
                                select_attribute(this);
                            }
                        }
                    }
                }
            }
        }

        var check_inventory_flag = select_attributes_complete();


        if(check_inventory_flag) {
            check_inventory();
        } else {
            var buy_num = $("#buy_num").val();
            if(buy_num <= 1) {
                minus_disable();
            } else {
                minus_enable();
            }

            plus_disable();
            plus_enable();
        }
    }

    function select_attributes_complete() {
        var check_inventory_flag = true;

        for(var i in attributes_mode) {
            if(attributes_mode[i] == ".*") {
                check_inventory_flag = false;
            }
        }

        return check_inventory_flag;
    }

    function check_inventory() {
        var index = JSON.stringify(attributes_mode);
        console.info(index);
        var current_inventory = inventory[index];
        console.info("current inventory:"+current_inventory);

        var buy_num = $("#buy_num").val();

        if(buy_num > current_inventory) {
            $("#buy_num").val(current_inventory);

            if(current_inventory == 1) {
                minus_disable();
            }

            plus_disable();
            return false;
        }

        if(buy_num == current_inventory) {
            plus_disable();
        }

        return true;
    }

    function seek_val_index(aid, val) {
        for(var i in attributes[aid]['values']) {
            if(attributes[aid]['values'][i] == val) {
                return i;
            }
        }

        return -1;
    }
</script>
<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
        $(".arrow_con").click(function(){
            arrow_con_toggle();
        });
    });

    function arrow_con_toggle() {
        if($(".arrow_d").hasClass("up")){
            $(".option_detail").slideUp();
            $(".arrow_d").removeClass("up");
        } else {
            $(".option_detail").slideDown();
            $(".arrow_d").addClass("up");
        }
    }
</script>
</body>
</html>
