<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$product.name}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商品详情</em></h1>
</header>
<!-- 产品图片轮播区 -->
<section id="focus" class="focus">
    <div class="hd">
        <ul></ul>
    </div>
    <div class="bd">
        <ul>
            {foreach from=$product.gallery item=gallery}
            <li><a href="#"><img _src="{$gallery}" src="{$template_dir}images/blank.png" /></a></li>
            {/foreach}
        </ul>
    </div>
</section>
<!-- 产品详情页 -->
<section class="product-detail">
    <article>{$product.name}</article>
    <div class="left">
        <b>￥<span id="main_price">{sprintf('%.2f', $product.price)}</span></b>
        <aside>
            <span class="blue"><em class="icon">&#xe60b;</em>返利{ceil($product.reward/2.5)}元</span>
            {if $product.lowest_price}<span class="white">我要砍价</span>{/if}
        </aside>
    </div>
    <div class="right">
        <ul>
            <li class="share"><a href="#">分享</a></li>
        </ul>
    </div>
</section>
<!-- 推广链接二维码 -->
<section class="qr-link">
    <div class="top">
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe604;</em>&nbsp;获取推广二维码</a></span>
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe60a;</em>&nbsp;获取推广链接</a></span>
    </div>
    <div class="bottom">
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe605;</em>&nbsp;进店逛逛</a></span>
        <span><a href="#"><em class="icon" style="color: #dd2727;">&#xe608;</em>&nbsp;联系掌柜</a></span>
    </div>
</section>
<!-- 产品属性选择 -->
<section class="option">
    <a class="arrow_con title">
        <div class="arrow_d up">选择 <span class="size">规格 </span><span class="split">/ </span><span class="packing">包装</span></div>
    </a>
    <div class="option_detail">
        <h3 id="size_name">规格</h3>
        <ul id="size_options">
            <li>30颗/盒</li><li  class="on">60颗/盒</li><li>120颗/盒</li><li>180颗/盒</li></ul>
        <h3 id="packing_name">包装</h3>
        <ul id="packing_options">
            <li class="on">平装</li>
            <li>精装</li>
        </ul>
    </div>
</section>
<!-- 产品详情 -->
<section class="detail-con">
    <div class="detail-con-style">
        <div class="clear"></div>
        <div class="detail-con-style-list">品牌：速来健</div>
        <div class="detail-con-style-list">规格：500mg/粒，60粒/瓶 </div>
        <div class="detail-con-style-list">适用人群：成年男、女性</div>
    </div>
    <div class="detail-content">
        {$product.detail}
    </div>
</section>
<!-- 产品评论 -->
<section class="comment">
   <div class="title">产品评论</div>
    <ul class="clearfix">
        <li>
            <div class="block"><div class="div1"><span class="head_pic"><img src="{$template_dir}images/default-user.png" alt=""></span><span class="user_name">老王</span></div><div class="message">由于经常工作久坐和熬夜，精神状态很不好，听朋友推荐修正的玛卡片，听说吃了能对身体有所改善，就自己上网上买了1盒，现在已经吃了一段时间，目前感觉白天精神状态很好，很少打瞌睡了，下班回家后稍微休息下又很精神了</div><div class="pic_list clearfix"></div><div class="time"><span class="c_96 fr">2015-02-02</span></div></div>
        </li>
        <li>
            <div class="block"><div class="div1"><span class="head_pic"><img src="{$template_dir}images/default-user.png" alt=""></span><span class="user_name">kkk</span></div><div class="message">今天已收到宝贝，包装很不错，卖家发货很给力哦，物流很快；家人用了后，效果不错，晚上睡眠质量也得到提高，白天精神很多，没有出现副作用，价格也非常实惠，能够在接受的范围在，这款保健品真的很不错！</div><div class="pic_list clearfix"></div><div class="time"><span class="c_96 fr">2015-02-02</span></div></div>
        </li>
        <div class="more">更多评论</div>
    </ul>
</section>
<div style="height: 49px;">&nbsp;</div>
<!-- 产品页底部 -->
<section class="actionBar-container">
    <div class="action-bar mui-flex">
        <div class="addfav cell">
            <i class="icon">&#xe606;</i>
            收藏
        </div>
        <div class="distribution cell">
            <i class="icon">&#xe607;</i>
            分销
            <a href="#"></a>
        </div>
        <button class="cart cell">加入购物车</button>
        <button class="buy cell">立即购买</button>
    </div>
</section>

<script type="text/javascript" src="{$template_dir}js/TouchSlide.1.1.js"></script>
<script type="text/javascript">
    TouchSlide({
        slideCell:"#focus",
        titCell:".hd ul", //开启自动分页 autoPage:true ，此时设置 titCell 为导航元素包裹层
        mainCell:".bd ul",
        effect:"left",
        autoPlay:true,//自动播放
        autoPage:true, //自动分页
        switchLoad:"_src" //切换加载，真实图片路径为"_src"
    });
</script>
</body>
</html>
