<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header" style="position: fixed;">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商品列表</em></h1>
</header>

<!-- 筛选开始 -->
<section class="filter">
    <ul>
        <li {if $state eq "price"}class="on"{/if}><a href="?state=price&id={$id}"><em>价格</em></a></li>
        <li {if $state eq "star"}class="on"{/if}><a href="?state=star&id={$id}"><em>好评</em></a></li>
        <li {if $state eq "add_time"}class="on"{/if}><a href="?state=add_time&id={$id}"><em>最新</em></a></li>
    </ul>
</section>
<!-- 内容开始 -->
<section class="product-list">
    <ul>
        {foreach from=$product_list item=product}
        <li>
            <a href="product.php?id={$product.id}">
                <img class="" src="{$product.img}" alt="{$product.name}">
                <dl class="arrow">
                    <dt> {$product.name} </dt>
                    <dd>￥{$product.price}</dd>
                </dl>
            </a>
        </li>
        {/foreach}
    </ul>
</section>

<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
</body>
</html>
