<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>用户中心</em></h1>
</header>
<!-- 用户基本信息 -->
<section class="home">
    <header class="user-info">
        <section class="user-basic">
            <img class="user-avatar" src="{if $user_info.headimg neq ""}{$user_info.headimg}{else}{$template_dir}images/wang.jpg{/if}" alt="用户"/>
            <div class="user-name">{$user_info.nickname}</div>
            <section class="remaining">
                <a href="balance.php"><em>余额&nbsp;{$user_info.balance}</em></a>
                <a href="reward.php"><em>圈币&nbsp;{$user_info.reward}</em></a>
                <a href="integral.php"><em>积分&nbsp;{$user_info.integral}</em></a>
            </section>
        </section>
        <!--
        <section class="user-stat">
            <a id="shop_collect_number" href="#"><em>0</em>微店收藏</a>
            <a id="product_collect_number" href="#"><em>0</em>商品收藏</a>
            <a id="read_history_count" href="#"><em>5</em>我的足迹</a>
        </section>
        -->
    </header>
    <!-- 我的订单 -->
    <section class="f-section order-section">
        <a class="slide-link" href="order.php">
            <span class="icon">&#xe622;</span>
            我的订单            <em>查看全部购买商品</em>
        </a>
        <nav class="order-nav">
            <ul>
                <li>
                    <a id="onlinepay_orders_count" href="order.php?status=1">
                        <p class="icon">&#xe61a;</p>
                        待付款
                    </a>
                </li>
                <li>
                    <a id="confirm_orders_count" href="order.php?status=6">
                        <p class="icon">&#xe617;</p>
                        待收货
                    </a>
                </li>
                <li>
                    <a id="pd-comment" href="order.php?status=7">
                        <p class="icon">&#xe618;</p>
                        待评价
                    </a>
                </li>
                <li>
                    <a id="refund" href="order.php?status=8">
                        <p class="icon">&#xe615;</p>
                        退货中
                    </a>
                </li>
            </ul>
        </nav>
    </section>
    <!-- 我的资产 -->
    <section class="f-section wealth-section">
        <a class="slide-link" href="account.php">
            <span class="icon" style="background-color: #7dc4fb;">&#xe61c;</span>
            我的资产            <em>查看我的全部资产</em>
        </a>
        <nav class="order-nav">
            <ul>
                <li style="width: 33.333333333333%">
                    <a href="balance.php" >
                        <p class="icon">&#xe614;</p>
                        余额
                    </a>
                </li>
                <li style="width: 33.333333333333%">
                    <a href="reward.php">
                        <p class="icon">&#xe619;</p>
                        圈币
                    </a>
                </li>
                <li style="width: 33.333333333333%">
                    <a href="integral.php">
                        <p class="icon">&#xe616;</p>
                        积分
                    </a>
                </li>
            </ul>
        </nav>
    </section>
    <!-- 个人中心功能菜单 -->
    <section class="f-section">
        <a class="slide-link" href="withdraw.php">
            <span class="icon" style="background-color: #fb9065;">&#xe621;</span>我要提现
        </a>
        <a class="slide-link" href="member.php">
            <span class="icon" style="background-color: #80c269;">&#xe624;</span>我的推广
        </a>
        <a class="slide-link" href="distribution.php">
            <span class="icon" style="background-color: #f29902;">&#xe620;</span>我的分销
        </a>
        <a class="slide-link" href="address.php">
            <span class="icon" style="background-color: #d0c0a6;">&#xe61d;</span>收货地址
        </a>
        <a class="slide-link" href="account.php">
            <span class="icon" style="background-color: #f29ec2;">&#xe623;</span>我的账户
        </a>
        <a class="slide-link" href="bank.php">
            <span class="icon" style="background-color: #f29ec2;">&#xe623;</span>我的银行卡
        </a>
        {if $user_info.business_account eq ""}
        <a class="slide-link" href="apply.php">
            <span class="icon" style="background-color: #c2cb5a;">&#xe61f;</span>我要开店
        </a>
        {/if}
    </section>
    <section class="f-section">
        <a class="slide-link" href="javascript:alert('敬请期待');">
            <span class="icon" style="background-color: #acd697;">&#xe61e;</span>意见反馈
        </a>
    </section>
    <!-- 猜你喜欢 -->
    <!--
    <section class="f-section might-like">
        <h3><i class="icon">&#xe61b;</i>猜你喜欢<a href="#"><span class="icon">&#xe625;</span>&nbsp;换一批</a></h3>
        <ul>
            <li>
                <a href="#">
                    <img src="images/product_1.jpg" alt="产品图">
                    <span>【速来健自营】速来健玛卡片</span>
                    <em>￥160.00</em>
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="images/product_1.jpg" alt="产品图">
                    <span>【速来健自营】速来健玛卡片</span>
                    <em>￥160.00</em>
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="images/product_1.jpg" alt="产品图">
                    <span>【速来健自营】速来健玛卡片</span>
                    <em>￥160.00</em>
                </a>
            </li>
        </ul>
    </section>
    -->
</section>
<div style="height: 2.2rem;"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a class="active" href="user.php"><em class="icon">&#xe600;</em><span>我</span></a></li>
    </ul>
</section>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>

</body>
</html>
