<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>生活圈移动商城</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="生活圈移动商城">
    <link rel="apple-touch-icon-precomposed" href="{$template_dir}images/touch/touch-icon-iphone.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{$template_dir}images/touch/touch-icon-ipad.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{$template_dir}images/touch/touch-icon-iphone4.png">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="www.kwanson.com">
    <meta name="version" content="v.1.0.0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/mobile.css">
    <link rel="stylesheet" href="{$template_dir}css/fonts.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>提现记录</em></h1>
    <a href="withdraw.php" class="edit">提现</a>
</header>
<!-- 订单列表 -->
<section class="order-list" style="padding-top: 0rem;">
    {foreach from=$withdraw_list item=withdraw}
    <div class="block">
        <div class="order_list">
            <!--非当当自营显示店铺入口-->
            <div class="sn_title">
                <a href="#">
                    <!--店铺名称-->
                    <div class="fl">
                        {$withdraw.withdraw_sn}
                    </div>
                    <span class="fr sn_status">
                        {if $withdraw.status eq 0}待处理{else}已处理{/if}
                    </span>
                </a>
            </div>
            <!-- 信息 -->
            <p class="withdraw-info">提现金额: ￥{$withdraw.amount}</p>
            <p class="withdraw-info"> 手 续 费 : ￥{$withdraw.fee}</p>
            <p class="withdraw-info">开户银行: {$withdraw.bank}</p>
            <p class="withdraw-info"> 开 户 人 : {$withdraw.bank_account}</p>
            <p class="withdraw-info">银行卡号: {$withdraw.bank_card}</p>
            <p class="withdraw-info">申请时间: {date('Y-m-d H:i:s', $withdraw.add_time)}</p>
            {if $withdraw.status eq 1}
            <p class="withdraw-info">处理时间: {date('Y-m-d H:i:s', $withdraw.solve_time)}</p>
            {/if}
            <!--操作按键-->
            {if $withdraw.status eq 0}
            <div class="detail3">
                <a href="javascript:delete_withdraw('{$withdraw.withdraw_sn}');">取消申请</a>
            </div>
            {/if}
        </div>
    </div>
    {/foreach}
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();" id="dialog_close_btn">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace" id="dialog_close">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
    function delete_withdraw(sn) {
        if (confirm("您确定要取消该申请?")) {
            cancel_withdraw(sn);
        }
    }

    function cancel_withdraw(sn) {
        var url = "withdraw.php";
        var data = { "opera":"cancel", "withdraw_sn":sn }

        show_mask();
        $.post(url, data, cancel_withdraw_handler, "json");
    }

    function cancel_withdraw_handler(response) {
        hide_mask();
        if(response.error == 0) {
            $("#dialog_close_btn").attr("href", "javascript:void(0);");
            $("#dialog_close_btn").click(function() {
                window.location.reload();
            });
            $("#dialog_close").click(function() {
                window.location.reload();
            });
        }
        show_message_dialog(response.msg);
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").text(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
</body>
</html>
