{include file="library/header.lbi"}
<body style="background: #fff;">
<!-- content -->
<div id="content" style="margin-left: 30px; padding-bottom: 60px;">
    <div class="basicInfo-main">
        {foreach from=$reward_list key=id item=reward}
        <h2>第{$id}轮</h2>
        <table class="table">
            <thead>
            <tr>
                <th>排名</th>
                <th>账号</th>
                <th>昵称</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$reward.detail item=detail}
            <tr>
                <td>{$detail.position}</td>
                <td>{$detail.account}</td>
                <td>{$detail.nickname}</td>
            </tr>
            {foreachelse}
            <tr>
                <td colspan="3">活动进行中</td>
            </tr>
            {/foreach}
            </tbody>
        </table>
        {foreachelse}
        没有获奖记录
        {/foreach}
    </div>
</div>
</body>
</html>