{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">订单管理-发货</h5>
        <div class="pull-right">
            <a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;
        </div>
        <div class="clear"></div>
    </div>
    <div class="basicInfo-main">
        <form id="orderDeliverForm" name="orderDeliverForm" method="post" action="">
            <fieldset>
                <p>
                    <label class="l-title">快递公司：</label>
                    <select class="w150" name="express_id">
                        <option value="0">请选择快递公司</option>
                        {foreach from=$express_list item=express}
                        <option value="{$express.id}">{$express.name}</option>
                        {/foreach}
                    </select>
                </p>
                <p>
                    <label class="l-title">快递单号：</label>
                    <input class="text-input w200" name="express_sn" />
                </p>
                <p>
                    <label class="l-title"></label>
                    <button class="btn btn-primary" type="submit">发货</button>
                    <input type="hidden" name="opera" value="deliver" />
                    <input type="hidden" name="sn" value="{$order.order_sn}" />
                </p>
            </fieldset>
        </form>
    </div>
</div>
{include file="library/footer.lbi"}
</body>
</html>