{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">订单详情</h5>
        <div class="pull-right">
            <button class="btn btn-primary" onclick="preview('{$order.order_sn}')">预览</button>&nbsp;
            <a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;
        </div>
        <div class="clear"></div>
    </div>
    <div class="basicInfo-main">
        <p style="display: inline-block" class="clear">
            <label class="l-title">订单编号：</label>
            <em style="width: 132px;">{$order.order_sn}</em>
        </p>
        <p style="display: inline-block" class="clear">
            <label class="l-title">下单时间：</label>
            <em style="width: 132px;">{$order.add_time_str}</em>
        </p>
        <p style="display: inline-block" class="clear">
            <label class="l-title">支付时间：</label>
            <em style="width: 132px;">{$order.pay_time_str}</em>
        </p>
        <p style="display: inline-block" class="clear">
            <label class="l-title">发货时间：</label>
            <em style="width: 132px;">{$order.delivery_time_str}</em>
        </p> <p style="display: inline-block" class="clear">
            <label class="l-title">确认收货时间：</label>
            <em style="width: 132px;">{$order.receive_time_str}</em>
        </p>
        <p style="display: inline-block" class="clear">
            <label class="l-title">订单状态：</label>
            <em style="width: 132px;">{$order.status_str}</em>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>产品</th>
                    <th>属性</th>
                    <th>单价</th>
                    <th>数量</th>
                    <th>积分</th>
                    <th>返利</th>
                </tr>
            </thead>
            <tbody>
                {foreach from=$order_detail item=detail}
                <tr>
                    <td>
                        <div class="pull-left">
                            <img src="../{$detail.img}" width="50" height="50"/>
                        </div>
                        <div class="pull-left">
                            <em> {$detail.product_name}</em>
                        </div>
                    </td>
                    <td>
                        <em>{$detail.product_attributes}</em>
                    </td>
                    <td>{$detail.product_price}</td>
                    <td>{$detail.count}</td>
                    <td>{$detail.integral}</td>
                    <td>{$detail.reward}</td>
                </tr>
                {/foreach}
            </tbody>
        </table>
        <div class="pull-right">
            合计：{sprintf("%.2f", $order.product_amount+$order.delivery_fee)}（含运费：{$order.delivery_fee}）
        </div>
    </div>
    <div class="content-title">
        <h5 class="pull-left">物流信息</h5>
        <div class="clear"></div>
    </div>
    <div class="basicInfo-main">
        <div class="clear">
            <p style="" class="clear">
                <label class="l-title">收货地址：</label>
                <em>
                    {$order.province_name} &nbsp;
                    {$order.city_name} &nbsp;
                    {$order.district_name} &nbsp;
                    {$order.address}  <br />
                    {$order.consignee}  ( {$order.mobile}  ) <br />
                    {$order.zipcode}
                </em>
            </p>
            <p style="display: inline-block" class="clear">
                <label class="l-title">配送方式：</label>
                <em>{$order.delivery_name}&nbsp;</em>
            </p>
            <p style="display: inline-block" class="clear">
                <label class="l-title">物流公司：</label>
                <em>{$order.express_name}&nbsp;</em>
            </p>
            <p style="display: inline-block" class="clear">
                <label class="l-title">快递单号：</label>
                <em>{$order.express_sn}&nbsp;</em>
            </p>
            <p style="display: inline-block" class="clear">
                <label class="l-title">备注：</label>
                <em>{$order.remark}&nbsp;</em>
            </p>
            {if $order.status eq 6}
            <button class="btn btn-primary" type="submit" onclick="get_express_info('{$order.order_sn}');">物流跟踪</button>
            {/if}
        </div>
        <div class="clear" id="experss_info">
        </div>
    </div>
</div>
<script type="text/javascript">
    function get_express_info(order_sn) {
        if(order_sn == "") {
            alert("参数错误");
            return false;
        } else {
            $.post("order.php", { "opera":"express_info", "order_sn":order_sn }, get_express_info_handler, "json");
        }
    }

    function get_express_info_handler(response) {
        $("#experss_info").html(response.msg);
    }

    function preview(order_sn) {
        var top = (window.screen.height - 400) / 2;
        var left = (window.screen.width - 1000) / 2;
        window.open ('order.php?act=preview&sn=' + order_sn,'newwindow','height=400,width=1000,top='+top+',left='+left+',toolbar=no,menubar=no,scrollbars=no, resizable=no,location=yes, status=no');
    }
</script>

{include file="library/footer.lbi"}
</body>
</html>