{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">订单管理{if $order_status neq ''}-{$order_status}{/if}</h5>
        <div class="pull-right">
            <a class="btn btn-primary" href="order.php">全部</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=1">待支付</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=4">待发货</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=6">已发货</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=7">已收货</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=8">申请退单</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=9">退单中</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=10">已退单</a>&nbsp;
            <a class="btn btn-primary" href="order.php?status=11">无效订单</a>&nbsp;
            <a class="btn btn-primary" href="javascript:history.go(-1);">返回</a>&nbsp;
        </div>
        <div class="clear"></div>
    </div>
    <div class="article-main-header">
        <form action="" method="get" />
        <fieldset>
            <p>
            <div class="pull-left">
                显示
                <select name="count" class="w75">
                    <option value="10" {if $count eq 10}selected="selected"{/if}>10</option>
                    <option value="25" {if $count eq 25}selected="selected"{/if}>25</option>
                    <option value="50" {if $count eq 50}selected="selected"{/if}>50</option>
                    <option value="100" {if $count eq 100}selected="selected"{/if}>100</option>
                </select>
                项结果
            </div>
            <div class="pull-right">
                <label>起始日期：</label>
                <input class="text-input w150" type="text" id="" name="st" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD'})"{/literal} value="{$st}">&nbsp;
                <label>结束日期：</label>
                <input class="text-input w150" type="text" id="" name="et" {literal}onClick="laydate({istime: true, format: 'YYYY-MM-DD'})"{/literal} value="{$et}">&nbsp;
                <button type="submit" class="btn btn-default">搜索</button>
            </div>
            </p>
        </fieldset>
        </form>
        <div class="clear"></div>
    </div>

    <div class="article-main">
        {if $status eq 0}
        <table class="table">
            <thead>
            <tr>
                <th>订单编号</th>
                <th>下单时间</th>
                <th>订单状态</th>
                <th>产品总额</th>
                <th>联系方式</th>
                <th>备注</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {if $total neq 0}
            {foreach from=$order_list item=order}
            <tr>
                <td>{$order.order_sn}</td>
                <td>{$order.add_time_str}</td>
                <td>{$order.status_str}</td>
                <td>{$order.amount}</td>
                <td>{$order.address}&nbsp;{$order.consignee}({$order.mobile})</td>
                <td>{$order.remark}</td>
                <td>

                </td>
            </tr>
            {/foreach}
            {else}
            {if $st eq '' && $et eq ''}
            <tr>
                <td style="padding: 50px 0" colspan="5" align="center">尚未有客户下单！</td>
            </tr>
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="7" align="center">
                    <span class="text-size-24 blue icon-info-1" style="vertical-align: middle"></span>
                    <div class="text-size-18 tip-text inline-block">没有查询到符合条件的记录</div>
                </td>
            </tr>
            {/if}
            {/if}
            <tr>
                <td colspan="7">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&st={$st}&count={$count}&et={$et}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&st={$st}&count={$count}&et={$et}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&st={$st}&count={$count}&et={$et}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&st={$st}&count={$count}&et={$et}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&st={$st}&count={$count}&et={$et}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        {/if}

        {if $status eq 1}

        {/if}
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<script>
    {literal}
    $(function(){
        laydate.skin('yalan');//切换皮肤，请查看skins下面皮肤库
    });
    {/literal}
</script>
<!-- END 日历控件 -->

{include file="library/footer.lbi"}
</body>
</html>